### ISSUE TITLE
关于开发的几点建议

### ISSUE THREAD

**Issue by qingzhenyun** [liupan1890/xiaobaiyang2#1]
您好，这里是清真云官方的开发组。
非常感谢您开发了一个很好用的客户端，也获得了很多用户的欢迎。
请在开发时候注意以下几点。

1、APP应当申请独立的APP ID 以便在登录和加密的时候使用，我们将在不久之后开启APPID和加密认证；
2、严守用户隐私，不要储存用户的任何信息；
3、严格遵守当地法律 不要做类似于分享、订阅、推送秒传建立文件之类的，尤其是不要在第三方储存文件哈希与用户的文件结构，不要自动在用户文件夹里面建立文件，会带来巨大的法律风险（构成《刑法》中“复制、存储” 一项）。

祝您生活愉快！

**Comment by liupan1890** [comment]
1、APP应当申请独立的APP ID
请问我应该如何申请？小白羊版仅仅是UI适配，弥补我在使用时遇到的特定需求

2、会严守用户隐私，因为上线时会开源出来，所有的用户数据均是本地存储，无上报功能，包括运行日志也是本地存储无上报，只有用户有问题时主动留言给我看。


3、
分享：6盘并未开放分享功能，我之后也不会涉及到分享功能
秒传：只涉及到用户上传文件时，6盘自带的秒传功能。并不会利用秒传，发开类似账号间文件互转等功能
储存：我并不会特意解析、复制、存储用户文件数据，所有数据均是用户本地调用6盘公开api获取
自动在用户文件夹里面建立文件：我会注意此问题，并不会自动创建任何文件--也不会自动处理用户文件或数据。所有的文件必须是用户主动上传或者主动离线

如有未尽事宜，请继续留言支持，感谢您的及时协助，避免我上线后再去捉急修正，十分感谢

**Comment by liupan1890** [comment]
另外，我并不是玻璃心，所以沟通时务必详尽清晰直接明了，不需要照顾心理，措辞委婉。可能会词不达意导致误解对吧
