### ISSUE TITLE
第二版，不能离线网盘链接吗？？

### ISSUE THREAD

**Issue by kitkw** [liupan1890/xiaobaiyang2#10]
第二版，不能离线网盘链接吗？？提示订阅会员什么的，种子就没有问题

**Comment by liupan1890** [comment]
6盘只有订阅会员才可以离线百度链接----去6盘官网订阅

**Comment by malou9** [comment]
购买vip才可以

**Comment by holll** [comment]
磁力链离线挺好用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kitkw"<notifications@github.com&gt;; 
发送时间: 2020年10月31日(星期六) 凌晨1:57
收件人: "liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [liupan1890/xiaobaiyang2] 第二版，不能离线网盘链接吗？？ (#10)





  
购买vip才可以
  
那不等同废了！！
 
&mdash;

**Comment by liupan1890** [comment]
呃，这个没办法。缺失部分资源只有百度分享，我也没办法的，小白羊也只是UI，功能还是由6盘决定的
