### ISSUE TITLE
离线下载目录过多显示不全

### ISSUE THREAD

**Issue by anye1998** [liupan1890/xiaobaiyang2#100]
离线下载目录过多（大于1998），在软件的离线任务列表就会出现显示不全的状况（离线列表有些任务会不显示），在网页版显示正常。
清理了一些任务后，软件也显示正常了。

**Comment by liupan1890** [comment]
你好

是的，当前只加载前2页（每页999条）记录，离线任务是按照时间从大到小排序的，也就是只能显示最新的前1998条记录

更早的记录因为性能原因不加载不显示，如果确实需要查看较早的离线记录，可以登录6盘官网查看

**Comment by liupan1890** [comment]
``````
const list = await CALLSixPan(userid, '', 'v3/offline/list', '', {
        skip: i * 999,
        limit: 999,
        orderby: [
          ['ctime', 'desc'],
          ['directory', 'desc'],
        ],
      })
``````
我确认了一下是按照时间排序的。6盘每天最多只能提交100条，也就是会显示最少20天的离线任务记录，
又因为大部分人每天提交不到100条，所以基本上可以认为是显示最近1个月的离线任务记录了

**Comment by anye1998** [comment]
> 
> 
> 你好
> 
> 是的，当前只加载前2页（每页999条）记录，离线任务是按照时间从大到小排序的，也就是只能显示最新的前1998条记录
> 
> 更早的记录因为性能原因不加载不显示，如果确实需要查看较早的离线记录，可以登录6盘官网查看



不是最先的记录不显示。

我发现bug的流程：新添加的一个下载任务没显示，然后又重新添加了一遍，还是没有。到官网查看，有这个记录。之后我添加了98个任务，有部分不显示。在官网清除部分下载任务，恢复正常。

**Comment by liupan1890** [comment]
我去排查一下，看是6盘没有按照时间排序返回数据还是程序的BUG

**Comment by liupan1890** [comment]
确认了，是我不该给6盘传排序参数，默认就是按照时间排序，传参反而乱排了

我会在下个版本修复此BUG

**Comment by anye1998** [comment]
> 
> 
> 确认了，是我不该给6盘传排序参数，默认就是按照时间排序，传参反而乱排了
> 
> 我会在下个版本修复此BUG

好的，感谢感谢。
