### ISSUE TITLE
希望编译一个Arm64/linux的包，自己只能编译2.2.0版

### ISSUE THREAD

**Issue by xiaokaixuan** [liupan1890/xiaobaiyang2#101]

**Comment by liupan1890** [comment]
[6盘小白羊版linux64-arm64.zip](https://github.com/liupan1890/xiaobaiyang2/files/5859647/6.linux64-arm64.zip)

试一下，告诉我结果，是否能正常使用

我没有arm，无法测试

**Comment by xiaokaixuan** [comment]
> [6盘小白羊版linux64-arm64.zip](https://github.com/liupan1890/xiaobaiyang2/files/5859647/6.linux64-arm64.zip)
> 
> 试一下，告诉我结果，是否能正常使用
> 
> 我没有arm，无法测试

刚试了，系统是Armbian。6panserver能用，里面带的aria2c不能用，应该只支持Android。

**Comment by xiaokaixuan** [comment]
还是谢谢作者大佬了。我自己换了个aria2c就可以了。

**Comment by liupan1890** [comment]
把你的aria发我一份啊

**Comment by xiaokaixuan** [comment]
> 把你的aria发我一份啊


[aria2-1.35.0-linux-gnu-arm-rbpi-build1.zip](https://github.com/liupan1890/xiaobaiyang2/files/5859798/aria2-1.35.0-linux-gnu-arm-rbpi-build1.zip)

**Comment by liupan1890** [comment]
ok
