### ISSUE TITLE
加入长时间下载速度过低重启任务的功能

### ISSUE THREAD

**Issue by majiajin2043** [liupan1890/xiaobaiyang2#102]

**Comment by majiajin2043** [comment]
我是会员，今天发现有个任务600kb/s 但是暂停后再开速度又恢复正常。
能否设置一个阈值，比如全局速度低于1Mb/s ，就暂停所有任务，10s后重开。
可以减少长时间下载结果好几个低速任务拖慢全局的几率

**Comment by liupan1890** [comment]
v2.2.3 默认使用aria下载

aria支持下载速度过低自动中断（下载失败）

小白羊支持下载失败后自动重试

所以只要你自己修改一下aria的配置文件就可以实现你的需求了（长时间下载速度过低重启任务）

windows  修改
6盘小白羊版win64\electron\resources\aria2.conf

``````
lowest-speed-limit=1M
``````
说明https://aria2.github.io/manual/en/html/aria2c.html#options

备注：
如果你是6盘免费用户，那么下载速度应该在50kb/s-700kb/s 之间，根文件有关，是6盘的限制，修改了aria也没用
如果你是6盘VIP用户，遇到下载速度不能满速，应该去6盘官网联系客服，而不是修改aria配置。VIP用户都是满速的，我一般20MB/s

**Comment by liupan1890** [comment]
我是会员，今天发现有个任务600kb/s 但是暂停后再开速度又恢复正常。（7Mb/s左右

这个是普遍现象，是6盘的问题，

我理解为你刚下载，6盘缓存节点没有这个文件，去回源拉取（此时你下载速度很慢），但是6盘没有在回源之后增速，

此时你暂停，再开，

6盘缓存节点已经有这个文件，直接返回--满速

6盘的问题

**Comment by majiajin2043** [comment]
> > 我是会员，今天发现有个任务600kb / s但是暂停后再开速度又恢复正常。（7Mb / s左右
> 
> 这个是普遍现象，是6盘的问题，
> 
> 我理解为你刚下载，6盘缓存上游没有这个文件，去回源拉取（此时你下载速度很慢），但是6盘没有在回源之后增速，
> 
> 此时你暂停，再开，
> 
> 6磁盘缓存上游已经有这个文件，直接返回-满速
> 
> 6盘的问题
好的，我试试 ！谢谢！

**Comment by majiajin2043** [comment]
> > 我是会员，今天发现有个任务600kb / s但是暂停后再开速度又恢复正常。（7Mb / s左右
> 
> 这个是普遍现象，是6盘的问题，
> 
> 我理解为你刚下载，6盘缓存上游没有这个文件，去回源拉取（此时你下载速度很慢），但是6盘没有在回源之后增速，
> 
> 此时你暂停，再开，
> 
> 6磁盘缓存上游已经有这个文件，直接返回-满速
> 
> 6盘的问题
👌好的，我试试！谢谢！
