### ISSUE TITLE
 Linux，链接到aria失败，稍后自动重试

### ISSUE THREAD

**Issue by LEGION128** [liupan1890/xiaobaiyang2#103]
Linux 有详细教程吗 俺不会搞

**Comment by LEGION128** [comment]
![image](https://user-images.githubusercontent.com/60326273/105632213-fc85ed80-5e8c-11eb-9f8d-5d209bdf9e6f.png)

**Comment by LEGION128** [comment]
请问这是这么回事 我的系统Debian10 64位

**Comment by LEGION128** [comment]
已是6盘会员

**Comment by Floatingdream12** [comment]
我也多次出现这种情况了，没有什么解决办法，希望大佬能改善一下

**Comment by liupan1890** [comment]
呃，可能是那里有BUG

出现此错误是因为aria进程退出了，不知道为什么退出

临时的解决方案：删除6panserver 同目录下的aria2cz这个文件，重启6panserver ，检测不到aria2c会自动切换回原来的内置下载引擎，就不会出现此错误了

请回复我一下，出现此错误，具体是什么情况呢

是打开6panserver后，已下载就出错，一直不能正常下载，始终显示连接到aria

还是 有时候可以下载，有的时候出错？出错后约1分钟是否可以自动恢复正常继续下载？
还是，下载途中，某一时刻突然就出错了？出错后约1分钟是否可以自动恢复正常继续下载？

**Comment by liupan1890** [comment]
> 我也多次出现这种情况了，没有什么解决办法，希望大佬能改善一下

你也是远程管理模式出错？还是electron环境出错？什么系统？

**Comment by liupan1890** [comment]
如果是，安装了新版后，始终不能下载，一直显示连接到aria

那么可能是aria2c这个文件，请查看此文件的属性，是否勾选了允许作为程序执行的属性（有执行的权限）

**Comment by liupan1890** [comment]
如果是，安装了新版后，可以正常下载，自己修改了aria2.conf，然后就遇到了不能下载，显示连接到aria，那是因为aria2.conf配置错误，修改的不对导致aria2c不能正常启动，替换回原始的aria2.conf即可正常下载

**Comment by liupan1890** [comment]
我又想到了一个与IP有关的，内置的aria2c，已经默认关闭了ipv6，所以如果你的系统没有ipv4的话，也会出现无法链接的错误---但是都有ipv4的，是内网，localhost，不是公网IPv4，

aria2c会绑定到http://localhost:29376/jsonrpc  如果端口29376被其他应用占用，也会出现此错误

**Comment by Floatingdream12** [comment]
您好，我在自家局域网内的openwrt上和Debian系统的vps上都曾出现这样的问题ipv4应该是都有的，端口也没有被占用，aria2.conf没修改过。出现此问题后我尝试将aria2c的属性开到最高，并重启了小白杨，问题没有得到解决。最常出现这种问题是第一次在设备上使用小白杨时会出现，本地曾试过安装小白杨使用没问题，删掉重新安装后却无法连接。vps是第一次安装小白杨就无法连接。经过反复重启是有可能自己变正常的。

**Comment by Floatingdream12** [comment]
出错方式是一下载立刻出错，没有见过下载途中出错

**Comment by liupan1890** [comment]
我想我可能找到哪里的问题了。请尝试
记事本打开 6盘小白羊版linux64\electron\resources\aria2.conf
在最后增加一行,保存，退出小白羊，重新启动小白羊
``````
daemon=true
``````


经我测试，在linux上，aria2c进程会被（不定时出现）休眠，导致无法正常访问的BUG，理论上增加daemon=true转为后台进程不会被休眠，我还要去测试一下是否有效，你也可以先试试

**Comment by Floatingdream12** [comment]
很有效，很有效，目前确实没再出现这种情况。感谢大佬做出这么好用的客户端，目前装在Linux上已经彻底替代官方网页了。

**Comment by xiaokaixuan** [comment]
@liupan1890 这个问题什么情况下会出现，我的就一直没出现问题，需不需要更新？

**Comment by liupan1890** [comment]
> @liupan1890 这个问题什么情况下会出现，我的就一直没出现问题，需不需要更新？

不需要更新，直接手动修改
<br/>
解决方案一：
记事本打开 6盘小白羊版linux64\electron\resources\aria2.conf
在最后增加一行,保存，退出小白羊，重新启动小白羊

daemon=true
  <br/>
  <br/>
就好了

什么时候出现？
这个跟系统有关
1.系统内存不足时会主动休眠一些进程
2.aria2c进程oom
我测试是随机性的，当天第一次测试下载时，约半小时后出现，之后测试再也没出现过。所以我也不知道他的机制是什么，但是加上daemon=true，查看进程的父进程，确实不再是6panserver，会避免出现无法连接到aria2这个出错

**Comment by davelie** [comment]
@liupan1890 你好，我在macos下今天也突然出现这个情况，按上面步骤处理了，目前还未解决。能否帮助一下。谢谢x-D

**Comment by liupan1890** [comment]
mac上你遇到时，请查看一下进程监视器里，有没有aria2c这个进程

我也还没搞懂这个BUG的原因是什么，如果频繁出现此BUG，请按照方案二处理

解决方案二：
删除6panserver 同目录下的aria2c这个文件，重启6panserver ，检测不到aria2c会自动切换回原来的内置下载引擎，就不会出现此错误了


mac的路径是       
``````
6盘小白羊版mac64.app\Contents\Resources\aria2c
6盘小白羊版mac64.app\Contents\Resources\aria2.conf
``````

**Comment by liupan1890** [comment]
> @liupan1890 你好，我在macos下今天也突然出现这个情况，按上面步骤处理了，目前还未解决。能否帮助一下。谢谢x-D

说一下你遇到此错误时的具体操作方式，我看我能否在我的电脑上重现，如果能重现，我就能修正了

**Comment by davelie** [comment]
> > @ liupan1890你好，我在macos下今天也突然出现这个情况，按上面的步骤处理了，目前尚未解决。能否帮助一下。谢谢xD
> 
> 说一下你遇到此错误时的具体操作方式，我看我能否在我的电脑上重现，如果能重现，我可以修正了

俩个方案都试过：1.按路径查看了aria2.conf，发现初始设置有daemon=true，就直接试方案2了
                              2.删除aria2c，重启客户端，尝试下载依然报错，且无aria2c进程
截图：
<img width="1451" alt="截屏2021-02-05 11 00 21" src="https://user-images.githubusercontent.com/40225042/106984232-218a3280-67a2-11eb-9bef-13e5e7fbed2e.png">

**Comment by liupan1890** [comment]
1.我确定在代码里是正确处理删除aria2c使用内置下载引擎的，代码无错误
``````
func RunAria() (bool, error) {
	dir := ExePath()
	aria := dir + "aria2c"
	aria2c := "./aria2c"

	if FileExists(aria) == false {
		return false, errors.New("aria2c not exist " + aria)
	}
``````
2.我测试了删除后是正常下载的
![捕获](https://user-images.githubusercontent.com/67817756/106999072-83599500-67c0-11eb-996d-6ca116f7bd7d.PNG)


3. 尝试一下重启mac。还不行的话，尝试一下重新下载解压
4. 请回复我你遇到无法连接到aria这个错误的操作步骤
5. 是更新了新版就一直报这个错误，还是更新后可以正常下载，然后某一天突然报这个错误？
6. 尝试一下删除配置项里的daemon=true这一行，看是否可以正常使用

**Comment by liupan1890** [comment]
在AppData\debug.log
是运行日志，贴一下debug.log的内容给我看看

**Comment by davelie** [comment]
> 1.我确定在代码里是正确处理删除aria2c使用内置下载引擎的，代码无错误
> 
> ```
> func RunAria() (bool, error) {
> 	dir := ExePath()
> 	aria := dir + "aria2c"
> 	aria2c := "./aria2c"
> 
> 	if FileExists(aria) == false {
> 		return false, errors.New("aria2c not exist " + aria)
> 	}
> ```
> 
> 2.我测试了删除后是正常下载的（使用内置下载引擎下载不使用aria了）
> ![捕获](https://user-images.githubusercontent.com/67817756/106999072-83599500-67c0-11eb-996d-6ca116f7bd7d.PNG)
> 
> 1. 尝试一下重启mac。还不行的话，尝试一下重新下载解压
> 2. 请回复我你遇到无法连接到aria这个错误的操作步骤
> 3. 是更新了新版就一直报这个错误，还是更新后可以正常下载，然后某一天突然报这个错误？
> 4. 尝试一下删除配置项里的daemon=true这一行，看是否可以正常使用

更新后使用几天都正常，昨天突然报错。步骤按你所说的操作的，未有错误。
正好下午更新了下系统，重启后6pan正常下载，未报错了。
日志如下，提示未曾找到aria2c：
<img width="648" alt="截屏2021-02-05 17 48 23" src="https://user-images.githubusercontent.com/40225042/107017651-5dd98500-67da-11eb-8807-5251dfb810f7.png">

最后，谢谢你的帮助～

**Comment by liupan1890** [comment]
嗯，我会在下次更新时，增加针对此错误的判断，遇到此错误时自动重启aria2c进程，就可以自动继续下载了，会彻底解决此问题
