### ISSUE TITLE
新版本手机登录请加入其他国家的区号

### ISSUE THREAD

**Issue by MasterNM2021** [liupan1890/xiaobaiyang2#104]
我是6盘海外（新加坡）用户，旧版本里有+65手机号区号，登入账号没问题。
新版本用用户名登录失败，手机号登录又仅有几个境外国家区号的选项。
v1.2.16版本的境外区号就很多，登入没问题，但这两天使用这个版本已无法连接到服务器。
能否请您在新的版本中加入像v1.2.16版本那样的区号数量？谢谢。

**Comment by liupan1890** [comment]
你好

嗯，下次更新时我会增加+65
如果你需要其他的区号，也说一下，我会一并增加，没想把全部加进去，太多了，也没用

注：虽然没有+65，但是你也可以用用户名+密码登录。用户名可以先登录6盘官网，就可以看到了，默认是随机名，也可以在官网修改为自己喜欢的用户名，就好记了

**Comment by liupan1890** [comment]
>新版本用用户名登录失败

不知道错误提示是什么？

**Comment by foreverAirJordan23** [comment]
能把德国 +49 也加一下吗 感谢！

**Comment by liupan1890** [comment]
20210203 15:05 新版已增加新加坡，德国
