### ISSUE TITLE
Mac版更新完2.2.3后，打开应用后还有版本升级提示

### ISSUE THREAD

**Issue by kingsword** [liupan1890/xiaobaiyang2#105]
RT

**Comment by liupan1890** [comment]
1. 可能是你下载的不对，请重新下载
2. 可能是首次提示，以后就不会提示了（有时候更新完第一次启动会提示一遍）
3. 可能是mac缓存问题，重启mac，先不要运行小白羊，重新解压新版替换文件

**Comment by liupan1890** [comment]
mac对小文件，有缓存加速，如果你启动了小白羊，然后退出小白羊------此时小白羊的文件可能会被mac缓存，

这时候你用新版替换了旧版的文件-----文件确实被替换了，是新的

然后运行小白羊-----因为有缓存，直接执行缓存（已经删除的旧文件），所以是执行旧版。

只有重启mac----缓存被自动清理了  再运行小白羊，就是真的执行新版文件了

这就是我理解的mac缓存

**Comment by kingsword** [comment]
确实重启之后才生效 - -#
