### ISSUE TITLE
Token invalid

### ISSUE THREAD

**Issue by muliu317** [liupan1890/xiaobaiyang2#106]
在点击 离线任务、搜索、新建离线文件等等的操作时，经常会出现拉取回收站内文件列表失败：Token invalid 的报错

**Comment by muliu317** [comment]
而且那个“6”图标对应的页面一直在刷新

**Comment by Qixingchen** [comment]
你的登入方式是 cookie 么,如果是cookie的话,是 cookie 过期了

**Comment by Qixingchen** [comment]
你的登入方式是 cookie 么,如果是cookie的话,是 cookie 过期了

**Comment by muliu317** [comment]
怎么确定登入方式是不是cookie呢？是指我的账号过期了吗？

**Comment by Qixingchen** [comment]
![image](https://user-images.githubusercontent.com/4182240/105966179-4524ed00-60bf-11eb-8c8e-2ec0abb23a9d.png)


看你使用什么方式登入的,或者你直接重新登入一次看看

**Comment by muliu317** [comment]
我是用手机号登陆的，重登之后没有之前的问题了

**Comment by muliu317** [comment]
另外，反应一下百度链接现在不可用了，不知道是不是最近的事情

**Comment by liupan1890** [comment]
嗯，收到，token的错误确实是因为登录状态失效（1.在别的地方重新登录这个6盘账号，2.在本机重新登录6盘网页版，3.长期未操作），登录状态是否失效是6盘管理的，随机性BUG吧

在下载文件时，如果遇到登录状态失效，会自动尝试自动重新登录，保证文件顺利下载
在其他操作时，不会自动重新登录，只会提示错误

下次更新，我会增加其他操作的，登录状态失效的，检查。出错时会尝试自动重新登录
