### ISSUE TITLE
mac版本打开以后是空白的，请问有人遇到一样的问题吗？

### ISSUE THREAD

**Issue by jasonwong1991** [liupan1890/xiaobaiyang2#107]
启动没有被阻止，但是软件打开是白屏！
如图:
![image](https://user-images.githubusercontent.com/8357581/106108070-bbd6ee80-6182-11eb-98cc-f742397f382f.png)

**Comment by liupan1890** [comment]
打开后是空白，说明6panserver这个文件没有正常运行，可以尝试去手动双击运行此文件

6盘小白羊版mac64.app\Contents\Resources\6panserver

![屏幕截图 2021-01-28 171634](https://user-images.githubusercontent.com/67817756/106116284-b41c4780-618c-11eb-88ba-7da3dad71b1b.png)

操作步骤：
1.找到6panserver这个文件
2.双击鼠标左键----正常应该弹出命令行的窗口（如截图）
3.双击运行6盘小白羊.app----正常显示，非白屏


第一次运行需要手动运行，以后应该就可以直接双击6盘小白羊.app正常运行了

和mac的权限有关，和6盘小白羊.app的解压位置有关（不能在download文件夹内解压）

**Comment by liupan1890** [comment]
我一般都是把6盘小白羊mac.zip下载到桌面，然后双击（解压到）桌面。据说有的文件夹权限低，会导致无法启动

如果按照上面步骤2.双击鼠标左键----正常应该弹出命令行的窗口（如截图）

没有正常显示命令行窗口，或者一闪而过（自动关闭退出了），那就是遇到了BUG，需要看运行日志，请回复日志内容

6盘小白羊版mac64.app\Contents\Resources\AppData\debug.log
