### ISSUE TITLE
离线任务能增加一个状态码吗

### ISSUE THREAD

**Issue by 1124714647** [liupan1890/xiaobaiyang2#108]

**Comment by liupan1890** [comment]
你好，什么状态码？我不明白你的意思啊

**Comment by Qixingchen** [comment]
offline/list 接口里面的 status，也就是官网页面中点击操作-详细信息中显示的 状态xxx  
 
![image](https://user-images.githubusercontent.com/4182240/106121502-981ba480-6192-11eb-814d-f206c7509bf2.png)

**Comment by liupan1890** [comment]
哦，显示状态码，下次更新加上

**Comment by 1124714647** [comment]
是的呢 感谢 辛苦了

**Comment by liupan1890** [comment]
20210203 15:05 新版已增加状态码
