### ISSUE TITLE
登入时要求密码长度限制不正确

### ISSUE THREAD

**Issue by Qixingchen** [liupan1890/xiaobaiyang2#11]
要求密码长度为 6~14位,然而我的账号设置的密码大于14位,建议不要限制密码长度.

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97694924-38075a80-1ade-11eb-90a6-7a28fc4e8aa3.png)

嗯，我是看6盘修改密码处限制了，下个版本更新时我会去掉密码长度的最长限制
