### ISSUE TITLE
b站会员番剧

### ISSUE THREAD

**Issue by zsbai** [liupan1890/xiaobaiyang2#110]
账号密码是放在链接后面,但是仍然提示需要登陆

**Comment by liupan1890** [comment]
你好
6盘可以下载部分B站视频，只需要提交B站视频链接即可
例如：https://www.bilibili.com/video/BV1i5411L7QL

6盘不支持使用自己的账号去下载B站视频，所以你把账号密码放在链接后面没有用的


仍然提示需要登陆

我没试过，请直接联系6盘的客服咨询，因为这个是6盘的功能实现，小白羊只是UI，对此无法提供帮助

**Comment by liupan1890** [comment]
6盘相关人员QQ：54379063

**Comment by zsbai** [comment]
> 6盘相关人员QQ：54379063

好的感谢
