### ISSUE TITLE
【建议】继续在GitHub上上传编译后的文件

### ISSUE THREAD

**Issue by RivenNero** [liupan1890/xiaobaiyang2#111]
部分用户可能更偏爱在GitHub上下载，我就是其中之一，感谢。

**Comment by liupan1890** [comment]
编译后的压缩包体积有100*4MB
我在大陆，以我的网络，大概需要几十个小时才能上传到github，所以不太现实，只能上传到蓝奏

同样的，以我的网络，从github下载100MB大概需要1小时甚至无法下载。蓝奏只需要下载几分钟

所以不会上传到github了

如果是只想要6panserver和www.db文件，可以先下载zip再解压查找，如果我只在github上上传6panserver和www.db，大部分用户不知道如何正确使用。总之，上传github我是感觉没有啥必要

**Comment by RivenNero** [comment]
啊... 我以为大大是用机场的... 原来不用的嘛 好叭
