### ISSUE TITLE
可否新增手機號可任意填入地區

### ISSUE THREAD

**Issue by jess5466** [liupan1890/xiaobaiyang2#112]
請問手機號登入可否跟之前版本一樣可以任意填入地區?
需要+370

**Comment by jess5466** [comment]
需要+370

**Comment by liupan1890** [comment]
你把需要的留言，我下次更新会加上

不会全部都加上，因为太乱了，大部分人都用不到，反而会增加选择时的难度。

其实我都是用用户名登陆的，手机号太长了

**Comment by liupan1890** [comment]
留言格式最好是  区号+国家名

因为只留了区号，我也得去一个个找国家名。。。让我偷点懒吧

**Comment by jess5466** [comment]
+370 立陶宛 (Lithuania)
謝謝..麻煩了...

**Comment by liupan1890** [comment]
收到了，我下次更新会加上的

**Comment by liupan1890** [comment]
已加上
