### ISSUE TITLE
下载文件夹里的单个文件，可否不要下载整个文件目录

### ISSUE THREAD

**Issue by yangziqin** [liupan1890/xiaobaiyang2#113]

**Comment by liupan1890** [comment]
你好

不可以，

原因：
当每次下载都按照如下操作
1.点击下载按钮
2.选择下载位置
3.下载
这样可以实现，只按照文件名保存

但是，为了简化下载操作
1.点击下载按钮
这样操作，只能按照完整路径保存

所以，为了简化下载操作，只能按照完整路径保存，无法实现按照文件名保存

**Comment by liupan1890** [comment]
另外，小白羊已经发布4个月了，所有的旧用户已经习惯了按照完整路径去保存，所以也不能修改为按照文件名保存，这样大部分用户会疯掉的

**Comment by liupan1890** [comment]
因长期未回复已被关闭
