### ISSUE TITLE
6panserver指的是6pan官方的server，还是小白🐏自己写的一个server

### ISSUE THREAD

**Issue by tristanyi** [liupan1890/xiaobaiyang2#114]

**Comment by liupan1890** [comment]
你好
6panserver是自己写的调用6盘官方api和自己写的下载模块，已开源，看一下源码就知道了

**Comment by tristanyi** [comment]
感谢回复

**Comment by tristanyi** [comment]
是不是需要向官方申请签名才能进行对应的接口调用，我想重新开发一个好看点的安卓版

**Comment by liupan1890** [comment]
呃，按照官方的说法和推荐，是希望你去联系6盘官方申请一个appid的

但是我是直接使用6盘网页版的appid的，我没有像官方申请appid

注：
所谓appid，就是调用账号登录时，附加的一个字符串，除了登录的接口，其他所有接口都不需要appid，也跟appid没有任何关联

https://account.2dland.cn/login?**appid=3a5654a9ccc9**&destination=https%3A%2F%2F2dland.cn%2Ffiles%2Fall%2F&response=redirect&scope=&state=7il7gphkb&lang=zh-CN

**Comment by tristanyi** [comment]
非常感谢，6盘还是比较好用的，就是客户端太简陋了，官方也不推进。
