### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by q1430517555** [liupan1890/xiaobaiyang2#115]
能否增加一个删除下载任务时，由用户选择是否删除本地文件。

**Comment by liupan1890** [comment]
哦，可能是我没整对，我稍后检查一下代码，理论上应该在删除下载任务时自动删除本地临时文件

不会让用户选择是否删除，因为只有一个删除按钮，点一下就删除了。我不喜欢点一下删除再弹窗提示是否删除临时文件这样的操作。喜欢点1下，不喜欢点2下

**Comment by zxc110** [comment]
白哥，毒盘提取的秒传链接能支持6盘么？

**Comment by liupan1890** [comment]
> 白哥，毒盘提取的秒传链接能支持6盘么？

6盘并不支持百度的秒传链接

从技术上说，百度网盘也不支持秒传链接，所谓的秒传链接是第三方开发者利用百度上传文件时，支持秒传功能，二次开发的变种链接。百度自己都不支持，所以6盘更加不支持了，并且现在6盘官网公告已经不支持百度分享链接了
