### ISSUE TITLE
想问一下为什么我每天离线次数只有一次啊？就我这样吗

### ISSUE THREAD

**Issue by SonogamiTohka** [liupan1890/xiaobaiyang2#116]
想问一下为什么我每天离线次数只有一次啊？就我这样吗

**Comment by liupan1890** [comment]
6盘官方政策

6盘的免费用户每天只有1次离线，并且下载时限速100kb/s并且部分冷门文件不能下载并且不能提交百度链接
6盘的VIP用户每天只有100次离线，并且下载时不限速100kb/s

请参阅6盘官网。小白羊只是第三方UI，和6盘本身无关联

**Comment by SonogamiTohka** [comment]
那要如何购买VIP？我没找到哪里有显示

**Comment by liupan1890** [comment]
在6盘官网购买，打开6盘官网，登录，点击用户名，订阅，选择月付年付，付款

**Comment by liupan1890** [comment]
https://v3-beta.6pan.cn/subscribe/plans
