### ISSUE TITLE
建议增加一个功能——命令行调用

### ISSUE THREAD

**Issue by Andrew201801** [liupan1890/xiaobaiyang2#118]
在登录的情况下，使用命令行调用6panserver，传入下载链接，保存目录，实现自动化下载，配合爬虫食用爽歪歪

**Comment by liupan1890** [comment]
参阅 https://github.com/liupan1890/xiaobaiyang2/issues/83

1.可以通过http调用方式实现   传入下载文件id，实现自动化下载（下载位置不能直接传入）

2.如果想实现每个文件的下载位置都自定义，可以先http调用修改下载保存位置，再http调用传入下载文件id自动下载（最终保存在下载位置+文件在6盘的完整路径）

总之，你懂js，那就可以非常简单的看一下小白羊源码，然后自行开发，但我无法增加命令行支持

**Comment by Andrew201801** [comment]
好哒好哒，我去康康

**Comment by Andrew201801** [comment]
谢谢谢谢

**Comment by liupan1890** [comment]
参阅源码的帮助：
小白羊的架构是，js代码通过http调用6盘官方api，js代码通过http调用6panserver实现下载保存文件
  
  
xiaobaiyang2/source-www/  里面是js源码，包含了调用6盘官方api的源码（http调用），你看一下源码里的参数，就知道怎么调用6盘官方的功能了（列出文件，获取指定文件下载地址）

xiaobaiyang2/source-6panserver/ 里面是golang源码，主要是包含了下载功能、用户登录功能

结合js源码，就知道怎么调用6panserver了

**Comment by Andrew201801** [comment]
我用python[搞好啦](https://github.com/Andrew201801/6panDownloader)，谢谢呀

有一个建议：
我对于js不太熟，电脑上只有node，因此电脑上的js环境可能不太全。在使用xiaobaiyang2/source-www/的过程中，按照说明安装依赖后，无法通过npm启动：
第一次出现can‘t find tsconfig.json的错误提示，通过[这个方法](https://blog.csdn.net/m0_48949576/article/details/111246314)解决了。
第二次出现No ESLint configuration found的错误提示，这次我查阅网上的资料都无法解决，遂放弃了。

因此如果您方便的话可以重新上传一下xiaobaiyang2/source-www/项目，或者将readme写得详细一些。

再次感谢！
