### ISSUE TITLE
6panserver linux64 downfinish.sh 似乎没运行

### ISSUE THREAD

**Issue by yuritry** [liupan1890/xiaobaiyang2#119]
定义了downfinish.sh，跑完download，好像没运行。

**Comment by liupan1890** [comment]
假设你在linux上，小白羊的路径为/6盘小白羊版linux64



1.创建/6盘小白羊版linux64/electron/resources/downfinish.sh
``````
echo `date +%c` GID=[$1]FileNum=[$2]FilePath=[$3]>>1.txt
``````
2.打开小白羊，设置，勾选下载完成后调用xxx
3.下载一个文件
4.此时自动创建了/6盘小白羊版linux64/1.txt内容为
``````
Fri 12 Feb 2021 12:22:24 PM CST GID=[a3e1f8489626027a]FileNum=[1]FilePath=[/home/test/Downloads/down/图片/a (1).jpg]
``````



结论：测试成功执行了脚本。

>定义了downfinish.sh，跑完download，好像没运行
应该是你脚本内容的问题

**Comment by yuritry** [comment]
谢谢。
找到问题了，文件名带括号，截取字符串出错，不知道怎么处理。

**Comment by Qixingchen** [comment]
整个路径加引号就可以吧

**Comment by Qixingchen** [comment]
整个路径加引号就可以吧

**Comment by liupan1890** [comment]
> 文件名带括号，截取字符串出错

是说你在sh里面的代码截取字符串出错吧？不是说命令行传入参数接收到的本身有问题吧？因为我上面的测试，恰好文件名里也有括号，在sh里是可以正确的接收到的。之后执行截取的命令的话，我也不知道了，我对sh没啥了解


上面的测试用sh命令都是我花半小时从网上找的帮助，然后整理的。sh里截取字符串的命令是什么我都不知道。。。。

**Comment by liupan1890** [comment]
参见  http://c.biancheng.net/view/1120.html

**Comment by yuritry** [comment]
> > 文件名带括号，截取字符串出错
> 
> 是说你在sh里面的代码截取字符串出错吧？不是说命令行传入参数接收到的本身有问题吧？因为我上面的测试，恰好文件名里也有括号，在sh里是可以正确的接收到的。之后执行截取的命令的话，我也不知道了，我对sh没啥了解
> 
> 上面的测试用sh命令都是我花半小时从网上找的帮助，然后整理的。sh里截取字符串的命令是什么我都不知道。。。。

是的

**Comment by yuritry** [comment]
我也没啥了解。网上没找到解决办法，Str=$3, Str='$3', Str="$3" 都报错。
估计我这边没办法解决了，看看您那边能不能加上一个引号？

**Comment by liupan1890** [comment]
**不应该由我这边加上引号，你理解的不准确**
  
**1.我这边需要负责把完整的文件路径传入**
Qixingchen commented 21 hours ago  整个路径加引号就可以吧

他是说的我，我在调用sh时，调用命令里应该对路径加上引号，这样在sh里面才能正确接收到文件路径
例如：执行download.sh -/home/test/file name.mp4
输出$1=/home/test/file


例如：执行download.sh -'/home/test/file name.mp4'
输出$1=/home/test/file name.mp4

所以是说的我需要加上引号，我本身就是加上了的。所以现在在sh里，Str=$3 就可以了，$3里接收到的是完整的正确的路径

  <br/><br/>
  
  


**2.你截取字符串，就是截取字符串，跟字符串有没有引号无关**。
并不是有引号就能截取成功，没有引号就截取失败。--理解的不准确

我看了上面url的帮助（参见 http://c.biancheng.net/view/1120.html）截取非常简单，并没有发现，有什么地方可以因为字符串里有括号，导致截取失败，你提到文件名带括号，截取字符串出错可能不准确

（假如加上引号，你截取时需要处理掉引号才能正确截取），所以从sh命令里的截取字符串方法上看，也不能加上引号


最后，shell里截取字符串的方式非常多，有很多种方法都可以实现截取字符串（直接截取、正则、substr 、awk、cut、）总有一种方法你可以顺利的截取到正确的字符串

sh内命令我也不懂，所以需要你自己去研究一下了

**Comment by yuritry** [comment]
ok 谢谢。
