### ISSUE TITLE
两个问题，不能直接下百度了，需先离线再下载

### ISSUE THREAD

**Issue by yagay** [liupan1890/xiaobaiyang2#12]
不能直接下百度云了，只能先离线再下载，，不能像第一版那样直接下，多一个步骤，而且不能选择需要下载的百度云的文件，必须整个离线，操作上比第一版复杂，

**Comment by liupan1890** [comment]
因为某些原因，我已经被迫关闭了第一版的离线百度分享链接的功能。

6盘的离线功能就是这样的，一个链接是一个整体，整体去离线，成功或失败。没有部分离线的功能

而且离线的成功率并不算高，我测试的是提交100条百度链接，大概有30-40条离线失败，

并且失败后无法重试（重新提交离线连接也不管用），可行的方法就是先把链接里的文件转存到自己的百度网盘，然后创建新的百度分享链接，最后提交到6盘离线

这个纯粹是6盘的功能问题，小白羊只是美化的UI，对离线功能无法设置

**Comment by yagay** [comment]
在第一版的时候可以选择百度分享离线里面的文件直接下载，不知道新版为什么不行了 ，，6盘的离线一直有问题，分享链接里面的文件更新了再次离线也没有新文件，但是小白羊第一版可以选择里面的文件，，这样就解决了这个问题，可惜新版没有这个功能了

**Comment by liupan1890** [comment]
6盘离线现在就是这样的啊

针对“”分享链接里面的文件更新了再次离线也没有新文件“”

这个问题只能是先转存到自己百度盘里，然后创建新的分享链接提交给6盘离线。这样绕一下

**Comment by yagay** [comment]
小白羊第一版为什么可以选择呢？是什么原理？第二版有没有可能实现？

**Comment by liupan1890** [comment]
6盘经常更新的啊，旧的接口已经不可用了，第二版没办法实现

**Comment by mcuixilei** [comment]
让订阅会员是什么意思 ？不免费了吗？

**Comment by holll** [comment]
本来就不是免费的，以前是开发者自己购买6盘会员给大家用


 
---原始邮件---
发件人: "崔席蕾"<notifications@github.com&gt;
发送时间: 2020年11月5日 11:23:40
收件人: "liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [liupan1890/xiaobaiyang2] 两个问题，不能直接下百度了，需先离线再下载 (#12)




 
让订阅会员是什么意思 ？不免费了吗？

**Comment by mcuixilei** [comment]
大佬牛逼

**Comment by mcuixilei** [comment]
现在要去哪里订阅啊

**Comment by holll** [comment]
6盘官网，百度的到


 
---原始邮件---
发件人: "崔老板"<notifications@github.com&gt;
发送时间: 2020年11月6日 10:16:43
收件人: "liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"holll"<380460708@qq.com&gt;;
主题: Re: [liupan1890/xiaobaiyang2] 两个问题，不能直接下百度了，需先离线再下载 (#12)




 
现在要去哪里订阅啊

**Comment by liupan1890** [comment]
https://6pan.cn/   https://2dland.cn/
