### ISSUE TITLE
小白羊最近上传速度变得好慢啊，以前是单个文件7-10m/s，现在几百kb/s，网页版上传速度也挺正常的，网络、硬盘和账号都没啥问题啊

### ISSUE THREAD

**Issue by saludossol** [liupan1890/xiaobaiyang2#120]

**Comment by saludossol** [comment]
![QQ截图20210221001121](https://user-images.githubusercontent.com/76832306/108601817-959b1c00-73d9-11eb-8f77-60f4d43c7c87.png)
![QQ截图20210221001223](https://user-images.githubusercontent.com/76832306/108601824-97fd7600-73d9-11eb-9399-4430c2008fe2.png)

**Comment by liupan1890** [comment]
![无标题1](https://user-images.githubusercontent.com/67817756/108618081-1a2b8000-7456-11eb-898f-d7b0b553ec56.png)
![无标题2](https://user-images.githubusercontent.com/67817756/108618083-1d267080-7456-11eb-97c7-23ce87fff38d.png)



我测试了一下我这里，是正常满速上传的（3M+/s）

你提到以前正常，现在不正常。我稍后会检查一下6盘网页端的上传接口是否更新了

**Comment by liupan1890** [comment]
![无标题1](https://user-images.githubusercontent.com/67817756/108618260-a25e5500-7457-11eb-9319-8be8879fe5be.png)
![无标题2](https://user-images.githubusercontent.com/67817756/108618265-a8eccc80-7457-11eb-835a-adbecea3c49d.png)

经检查，6盘并未更新上传接口。网页版和小白羊上传步骤、参数是一致的

**Comment by liupan1890** [comment]
1.我这里测试上传速度正常
2.我没能找到哪里有问题

所以我也无法定位到底是哪里的问题。可能是当时当前网宿cdn节点忙，或者是未知的BUG，如果遇到上传速度慢，试一下退出小白羊重新启动小白羊？

1.上传是调用网宿的上传节点。
网宿有数千个节点，每一次上传，都会智能分配给你一个节点，所以同一时间，上传的不同文件，可能会上传到一个节点，也可能会上传到不同节点。每一秒，节点的负载都不一样，所以会有快有慢，有时候就是单纯的网络问题。如果继续频繁遇到上传速度慢，请再次反馈。
2.问题的关键是在我这里上传速度正常，我遇不到问题所以无从下手

**Comment by liupan1890** [comment]
另外提示一点，6盘对免费用户的上传是限速的（VIP有cdn上传加速功能，免费用户没有加速就等于是被限速了），如果你的VIP过期了，可能就会遇到上传速度较慢的问题

**Comment by saludossol** [comment]
账号是订阅用户，前两天开始小白羊上传的速度就比网页版的慢好多，不知道是什么原因，重启也是一样的
![QQ截图20210222141538](https://user-images.githubusercontent.com/76832306/108669771-9f776900-7518-11eb-8912-00a3407c97c3.png)
![QQ截图20210222141423](https://user-images.githubusercontent.com/76832306/108669774-a1412c80-7518-11eb-989c-bdf0568a518d.png)

**Comment by liupan1890** [comment]
我明天再认真检查看看

**Comment by liupan1890** [comment]
已上传新版本，试试

**Comment by saludossol** [comment]
比上个版本好一些，可能是网宿的问题把
![QQ截图20210223152918](https://user-images.githubusercontent.com/76832306/108813576-45e06e80-75ec-11eb-9a66-641e248e4983.png)
