### ISSUE TITLE
现在一直提示拉取文件内列表失败：token invalid

### ISSUE THREAD

**Issue by wshlyl** [liupan1890/xiaobaiyang2#121]

**Comment by iErics** [comment]
同样的问题

**Comment by liupan1890** [comment]
这是账号登录状态失效了，
方案一：点击添加一个6盘账号按钮，输入用户名密码，重新登录一次账号即可
方案二：点击一下修改账号设置按钮（会自动刷新账号数据，因为此时登录状态已失效，最终会导致自动重新登录）
方案三：退出小白羊重新打开即可

这三个方案，任选其一操作即可

![无标题1](https://user-images.githubusercontent.com/67817756/108802066-57b51800-75d2-11eb-9f58-641d60e275d3.png)

![无标题2](https://user-images.githubusercontent.com/67817756/108802091-6a2f5180-75d2-11eb-84bb-e298a84c680e.png)
