### ISSUE TITLE
ubuntu 16.04 修改权限也无法运行

### ISSUE THREAD

**Issue by 1420125167** [liupan1890/xiaobaiyang2#123]
ubuntu 16.04 修改权限也无法运行，双击6盘小白羊版没有任何反应

**Comment by liupan1890** [comment]
1. 试试旧版
2. 我下一个16去试试

理论上跟系统版本一点关系没有才对

**Comment by liupan1890** [comment]
![屏幕截图 2021-02-24 131906](https://user-images.githubusercontent.com/67817756/108951436-f446eb00-76a2-11eb-8077-b6a8b6fb4e36.png)


1.下载http://mirrors.aliyun.com/ubuntu-releases/16.04/ubuntu-16.04.7-desktop-amd64.iso
2.vm创建虚拟机
3.火狐浏览器 https://github.com/liupan1890/xiaobaiyang2 下载 6盘小白羊版linux64.zip
4.解压到桌面
5.双击执行（没有修改文件权限，默认打包时已赋权）
6.正常运行



所以跟系统无关
在electron\resources\AppData\Debug.log是运行日志，贴上来我看看，可能有错误原因

**Comment by 1420125167** [comment]
> 在electron\resources\AppData\Debug.log是运行日志，贴上来我看看，可能有错误原因
没有这个文件

另外我用的是vps上安装了图形界面的16.04，在我本地的16.04和20.04上能运行，服务器上运行不了

**Comment by liupan1890** [comment]
那我再去试试服务器版

**Comment by liupan1890** [comment]
查了查资料，electron不支持ubuntu server，不用试了
