### ISSUE TITLE
MAC版本有没有可能支持10.14版本系统？

### ISSUE THREAD

**Issue by kahnli** [liupan1890/xiaobaiyang2#124]
MAC版本有没有可能支持10.14版本系统？谢谢，不太想升级10.15。但是软件必须是15才能用？

**Comment by liupan1890** [comment]
为什么软件必须是15才能用？具体的问题是什么？


我手里只有15，理论上跟系统版本无关才对
elcetron支持14
golang支持14

**Comment by kahnli** [comment]
谢谢  刚刚试了最终版可以了 之前的版本都提示系统版本太低 不能打开。
