### ISSUE TITLE
恳请作者添加特定目录下的资源搜索功能

### ISSUE THREAD

**Issue by wellsyue** [liupan1890/xiaobaiyang2#125]
当前搜索功能，范围是整盘，太大了。

多谢作者无私奉献。

**Comment by liupan1890** [comment]
你好

现在的搜索是整个网盘内全部文件都被搜索，
6盘官方API是支持文件夹内搜索功能的
6盘官方网页版也是全盘搜索

我没加上文件夹内搜索，是有顾虑
1.当用户在首页搜索时，输入文字，预期全盘搜索
2.当用户在某个文件夹下，输入文字搜索时，预期是全盘搜索
因为我没有任何地方提示是文件夹内搜索。我的意思是，我应该加上明确的提示---现在搜索是在文件夹内搜索还是在全盘搜索

但是在实际操作中，
1.提示加入的方式，没有位置或者不好看
2.同一个按钮提供不同的功能容易混乱
3.大部分文件夹里并不会嵌套，在文件夹内搜索功能没有必要（一眼就看到此文件夹内的全部文件了，不需要再输入文件名搜索了，打字很累的）
4.搜索功能本身并不常用


为了和官方统一，我并没有增加文件夹内搜索的打算

**Comment by liupan1890** [comment]
![无标题2](https://user-images.githubusercontent.com/67817756/109120651-2f1f5080-7781-11eb-9290-cf118223e63e.png)


比如做成这样，提示太不明显了，同一个按钮提供不同的功能并不合适，
又比如有人就想全盘搜索，所以每次搜索前还要增加一个额外的步骤：点击根目录--输入文字--搜索
又比如在搜索结果页面无法明确的标识出，搜索结果列表是某个文件夹下的结果还是根目录的结果
又比如在搜索结果页面继续搜索（更换搜索关键字），也会比较混乱
![无标题](https://user-images.githubusercontent.com/67817756/109121084-c4224980-7781-11eb-8fb1-9de5a2741a23.png)

最后还有一点，官方的API也在不断更新调整，官方网页版没有提供文件夹内搜索，说明此API并不稳定以后或许会被取消掉
所以多个原因考虑，并不增加此功能

**Comment by wellsyue** [comment]
感谢作者如此详尽的解释！

本人需要此功能的原因是：离线下载了一段时间后，某个文件夹下面有几百个子目录，每个子目录下分别有一部电影，在整理的时候，需要将所有这些电影统一移动到某个目录。
手动移动文件非常低效，故有此需求，望作者见谅。

**Comment by liupan1890** [comment]
没明白你的需求跟文件夹内搜索的关系

>某个文件夹下面有几百个子目录，每个子目录下分别有一部电影,需要将所有这些电影统一移动到某个目录

1.搜索（包括制定文件夹内搜索功能）无法搜索出所有的电影文件

比如有的电影是mp4格式，有的电影是avi格式，通过搜索mp4并不能搜索出所有的电影文件，
或许你保证所有的电影文件里都包含某个关键字,通过搜索关键字可以搜索出全部电影文件
  

2.如果有关键字（只要解决了搜索出全部电影文件），就可以直接全部选中，点击移动到，把所有电影文件移动到指定的位置了（就是支持批量移动搜索结果里的文件）
![无标题](https://user-images.githubusercontent.com/67817756/109143423-fab88e00-779a-11eb-824a-1823d566ace4.png)

 
3.搜索结果还可以根据时间排序一下，更加方便勾选，但是搜索只显示前999条记录

4.可以通过移动文件后，批量重命名功能把关键字替换成空（就是删除关键字）或替换成其新的关键字，避免新旧文件冲突或超过999不显示

**Comment by liupan1890** [comment]
这样的需求属于个人遇到，并非常用需求，不会针对个人需求去增加功能的，因为会导致后期版本迭代时需要检查维护的功能太多。小白羊本身也是开源的，懂js的话可以自己修改编译一份自定义版本，实现自动的批量移动

**Comment by Andrew201801** [comment]
> 离线下载了一段时间后，某个文件夹下面有几百个子目录，每个子目录下分别有一部电影，在整理的时候，需要将所有这些电影统一移动到某个目录
是批量把文件夹下所有子目录下的电影移动到同一目录内吗？可以用python自己实现，或者网上也有对应的软件。

**Comment by liupan1890** [comment]
> > 离线下载了一段时间后，某个文件夹下面有几百个子目录，每个子目录下分别有一部电影，在整理的时候，需要将所有这些电影统一移动到某个目录
> > 是批量把文件夹下所有子目录下的电影移动到同一目录内吗？可以用python自己实现，或者网上也有对应的软件。

他说的是网盘里的某个文件夹下百个子目录，每目录下一个文件
