### ISSUE TITLE
离线下载到一半显示309等待重试什么情况？

### ISSUE THREAD

**Issue by mchotdograp** [liupan1890/xiaobaiyang2#126]
单线程单任务

**Comment by liupan1890** [comment]
你好

> 离线下载到一半
离线下载是6盘的功能，问我，我也不知道啊

> 单线程单任务
说的是小白羊的设置，是在下载6盘内文件时，单线程单任务。这个和**离线**这2个字，一点关系没有


所以其实我没看明白你想问的是什么。请详细描述你的问题

**Comment by mchotdograp** [comment]
不好意思 我的问题 没描述清楚 上图~
![image](https://user-images.githubusercontent.com/48815225/109265093-f34bc000-7840-11eb-83d6-fdc13706e859.png)

Link:
magnet:?xt=urn:btih:3c3d31164314599f648369e957246f31c37b0137&dn=[联合动漫发布][漫友之家&异域动漫&章魚动漫联合压制发布][黑礁Black_Lagoon][BDrip][1-24+OVA7][x264_AAC][1280x720]&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://opentracker.i2p.rocks:6969/announce&tr=udp://47.ip-51-68-199.eu:6969/announce&tr=udp://explodie.org:6969/announce&tr=http://tracker3.itzmx.com:6961/announce&tr=http://open.acgnxtracker.com:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://www.torrent.eu.org:451/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.ds.is:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://retracker.lanta-net.ru:2710/announce&tr=udp://tracker.moeking.me:6969/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://valakas.rollo.dnsabr.com:2710/announce&tr=udp://opentor.org:2710/announce&tr=http://rt.tace.ru:80/announce&tr=udp://cdn-2.gamecoast.org:6969/announce&tr=http://tracker.bt4g.com:2095/announce

**Comment by Qixingchen** [comment]
离线任务是6pan提供的 要查的话去给[6pan发工单](https://2dland.cn/).

根据[知识库](https://0e0e083932c23d0f.kf5.com/hc/kb/article/1411440/) 

309 是 文件下载缓慢，持续12小时无法获取meta或者无进度

**Comment by liupan1890** [comment]
详细解释一下
1.当你提交磁力链接，创建离线任务时，是让6盘去离线下载
2.有的任务6盘会离线失败，你截图中的【86% 309 等待重试】就是6盘显示的离线任务状态信息
3.小白羊只是UI，显示，所以离线任务状态，为什么显示309错误，需要你去咨询6盘
4.磁力链接下载，本身就不是百分百成功的，遇到离线失败是正常的。取决于这个链接的热度、你使用什么工具下载（迅雷、比特精灵、6盘）、你在什么时间下载、你在什么地方下载、你使用什么网络、你是用什么tracker等等因素，如果你稍微连接一下什么是磁力链接，BT的工作原理，你就明白了


总之：跟小白羊程序本身无关

**Comment by mchotdograp** [comment]
好的 明白了 谢谢
