### ISSUE TITLE
下载到本地出现证书错误

### ISSUE THREAD

**Issue by kahnli** [liupan1890/xiaobaiyang2#127]
错误如下，无法进行下载

SSL/TLS handshake failure: Invalid certificate chain

![image](https://user-images.githubusercontent.com/36909175/109382405-34b09e00-791b-11eb-9682-2558a1128b75.png)

**Comment by liupan1890** [comment]
可能是你用了代理，或者系统时间不对，或者你用的linux但内置ssl库版本不符

你没说是啥系统，用win64举例

解决方案一:
在aria的配置文件末尾增加一行
6盘小白羊版win64\electron\resources\aria2.conf
``````
check-certificate=false
``````

解决方案二：
删除  6盘小白羊版win64\electron\resources\aria2c.exe  这个文件，使用内置golang下载引擎下载

任选一个，重启小白羊生效

**Comment by kahnli** [comment]
用的是MAC 10.14版本系统  关闭代理还是一样的报错  时间是对的  而且咱们软件没有选择是不是使用代理 
这个可以增加吗？

**Comment by liupan1890** [comment]
1. 关闭代理 还要重启才能生效
2. 请按照上面解决方案一，或者解决方案二操作，如果还不行请继续反馈
3. 咱们软件没有选择是不是使用代理这个可以增加吗？
 -------抱歉不可以，因为aria2+代理出错几率很高，另外代理有很多种（pac，ie代理，全局代理，vpn），增加代理配置后，很容易出错，我也没经验去测试各种代理的兼容性，所以不会增加代理支持

**Comment by kahnli** [comment]
你说的重启是重启电脑吗？
退出了代理跟6pan软件  重新开6PAN也是不行。
那软件默认会去用代理链接吗？一般开的选的PAC，根据服务器地址去判断是否走代理。

**Comment by kahnli** [comment]
刚刚测试了 关闭代理后  重启电脑才行，然后先打开6PAN  再开代理就不会有影响了
只能这样解决了  看来

**Comment by kahnli** [comment]
刚刚测试了 关闭代理后  重启电脑才行，然后先打开6PAN  再开代理就不会有影响了
只能这样解决了  看来

**Comment by liupan1890** [comment]
嗯，解决了就好，但是你也没告诉我你是否按照解决方案一试过，一般代理导致的证书错误，按方案一操作就好了，不管怎样解决了就好

**Comment by kahnli** [comment]
谢谢支持，已经修改，测试后结果再反馈。
