### ISSUE TITLE
小白羊的聚合搜索是如何实现“把用户上传的文件被搜索出来的？”

### ISSUE THREAD

**Issue by Sailing168** [liupan1890/xiaobaiyang2#128]
小白羊的聚合搜索是如何实现“把用户上传的文件被搜索出来的？”我有发现聚合搜索会出现自己搬运的文件，这样是否过于透明？聚合搜索的信息是源于哪里？源文件的删除，是否还能在聚合搜索中下载？文件名称的更改，能否避免被搜索出来？

**Comment by liupan1890** [comment]
1. 聚合搜索搜索出的都是磁力链接
你在聚合搜索内，能够搜索出来的结果，全部是磁力链接和百度分享链接，而不是
>用户上传的文件

所以你为什么在这里误导？
![无标题](https://user-images.githubusercontent.com/67817756/109907791-ff6ecc00-7cdd-11eb-93d1-f69d8382f947.png)

2. 聚合搜索的链接来源是采集网络中的公开资源，主要是一些磁力搜索网站
包括：雨花阁，磁力工厂，大圣盘，云盘精灵等等等等，但是因为他们的资源太多了，并不是全部收录---我也没有方式去全部收录，只是根据用户的搜索关键词，定期去这些网站爬到一部分数据


3.磁力链接和百度分享链接是公开资源，不涉及用户隐私
磁力链接你跟我说隐私那就搞笑了，你想挑毛病，那拿磁力链接的版权来说事，比你拿用户隐私来说事有依据


4.用户自己上传的文件，无法自动生成磁力链接，也无法分享给其他人下载
BT的原理是 做种，发布，生成磁力链接。而不是上传文件生成磁力链接。6盘是无法做种的，做种是需要宽带的，你明白了吗？详细的可以搜索一下BT协议，我说的比较简单

**Comment by liupan1890** [comment]
![捕获](https://user-images.githubusercontent.com/67817756/109909339-e3205e80-7ce0-11eb-80d7-8ab867bb239e.PNG)

**Comment by Sailing168** [comment]
谢谢作者的回复，我提到的“用户上传”指代的是百度分享的代下服务。当我把代下的文件删除后（回收站内删除），仍然可以在聚合搜索中实现秒离线的功能。是否意味着6盘内的个人下载文件哪怕是删除后，仍然留在六盘的储存库内（而自己看不到）？也就是说，六盘的开放性很高。当我们每个人提交磁力下载和百度分享时，聚合搜索自然可以搜索所有的信息，并提供秒离线功能，望解答。

**Comment by Qixingchen** [comment]
百度 115 6盘都是一样的,文件不做用户隔离,你上传了就会被储存为全局文件块,别人提交一样的链接或者进行上传就能"秒传"

**Comment by liupan1890** [comment]
> 百度 115 6盘都是一样的,文件不做用户隔离,你上传了就会被储存为全局文件块,别人提交一样的链接或者进行上传就能"秒传"

说得对。


### 说一下我对6盘的分析：

不管是百度分享链接还是磁力链接、电驴链接。
1.当你提交离线任务，此时6盘会去离线下载并保存到6盘的服务器上
2.成功后，6盘会对此链接缓存，即其他人再次提交这一条链接。会直接秒传，6盘不需要再次去重新离线下载（是为了避免重复的离线同样的链接）
3.此时不论你对你自己6盘里下载的文件（这一条链接包含的文件），进行删除、重命名操作，都不影响6盘的缓存。只要有人再次提交这一条链接，就会秒传成功离线，你对自己网盘内的文件操作，只对自己生效。跟6盘缓存无影响
4.你无法控制6盘何时会清理掉这一条链接的缓存，你也无法删除这一条链接的缓存（比如你提交的是一条百度分享链接，即使此链接现在已经失效了打不开了，6盘仍然可以秒传离线成功---有缓存）


特别针对百度分享链接，比如你第一次用6盘离线成功了，然后更新百度分享链接内的文件，再次用6盘重新离线此链接，会发现，秒传成功并且文件未更新。说明6盘使用的缓存数据，不是真的去百度离线下载了

**Comment by Sailing168** [comment]
收到
