### ISSUE TITLE
为什么现在好多文件，我无法通过这个软件下载，尤其是很大的文件，2G以上的。

### ISSUE THREAD

**Issue by 2Bsister** [liupan1890/xiaobaiyang2#129]
一些大文件，一下载就报错，远程主机强迫关闭了一个连接，非常小的文件倒是没有问题。然后文件生成的下载连接倒也可以用IDM下载，就是自身无法下载。这个问题是6盘那里的问题吗？

**Comment by 2Bsister** [comment]
有时候也会突然报错 IDM  无法下载此文件 备注：  SSL_connect error 5

**Comment by liupan1890** [comment]
看到你的留言，我去测试了一下，不论是VIP，还是免费账号，都可以正常下载，所以不知道你为什无法下载

>远程主机强迫关闭了一个连接
1.网络不好  2.连接数太多被强制关闭

>非常小的文件倒是没有问题
下载和文件体积无关才对，都能下，或者都不能下

>SSL_connect error 5
错误原因是ssl证书校验失败，一般是你挂代理时容易出现

总之，我没能遇到不能下载的报错，所以不知道是哪里的问题，看看是否有其他人反馈不能下载吧


注：如果你是免费用户，多线程下载就会失败

**Comment by 2Bsister** [comment]
> 看到你的留言，我去测试了一下，不论是VIP，还是免费账号，都可以正常下载，所以不知道你为什无法下载
> 
> > 远程主机强迫关闭了一个连接
> 
> 1.网络不好 2.连接数太多被强制关闭
> 
> > 非常小的文件倒是没有问题
> 
> 下载和文件体积无关才对，都能下，或者都不能下
> 
> > SSL_connect error 5
> 
> 错误原因是ssl证书校验失败，一般是你挂代理时容易出现
> 
> 总之，我没能遇到不能下载的报错，所以不知道是哪里的问题，看看是否有其他人反馈不能下载吧
> 
> 注：如果你是免费用户，多线程下载就会失败

我又测试了几次，具体情况我也不知道，但的确不是软件的问题，应该是6盘和我这里的资源网络出现了问题。多谢回复

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/110564281-88c34a00-8187-11eb-8839-23b58cc44104.png)


嗯，昨晚测试的免费账号下载，5.7GB，成功下载没有报错---下了6个多小时
