### ISSUE TITLE
是否增加下载完成后 移动到指定位置?

### ISSUE THREAD

**Issue by iLaoDi** [liupan1890/xiaobaiyang2#13]
批量下载 比较大的文件夹的时候, 机子硬盘不够大 . 所以想着作者是否可以加上 任务下载后 将文件移动到指定文件夹 (如挂载的谷歌盘), 或者直接调用rclone 上传到指定网盘.

**Comment by iLaoDi** [comment]
主要是懒. 是可以自己手动完成 比如分批下载 然后上传到网盘里面.

**Comment by liupan1890** [comment]
嗯，我想想

1. 下载后移动到指定文件夹
我主要是想一点就下，所以没有添加点击下载后弹窗选择下载位置的功能，我下个版本加上这个功能，就是下载时可以选择下载位置。这样就不需要下载后移动到指定文件夹了

2. 下载后移动到挂载的谷歌盘
这个肯定是不行的，因为你是挂载的谷歌盘（或者其他盘），如果直接移动到盘里，会需要很长很长时间（你从C盘复制文件到D盘，5GB文件可能需要几十秒复制完，这几十秒程序要一直等待复制完成再删除文件。同理你从C盘复制文件到挂载的谷歌盘，5GB文件可能需要十几分钟--看你网速了，那程序要等十几分钟上传成功了再删除文件，这个功能不合适）（ps：也要看你是用什么软件挂载的，大部分挂载工具，对小文件都是先缓存到临时目录再上传，所以复制也是几秒就完了，大文件需要看挂载软件的临时文件的设置了）

3. 下载后调用rclone 上传到指定网盘
像aria是下载结束后，调用一个xxx.sh文件，运行命令。xxx.sh里面又去调用rclone上传和结束删除文件。这个xxx.sh文件一般都是rclone自带的，你也可以自己修改

那我在后期，会尝试加上下载完成调用命令的设置项，你填一下xxx.sh的路径就跟aria一样了，这个功能要比较靠后了，耐心等等看

**Comment by iLaoDi** [comment]
感谢作者的辛苦开发.

**Comment by liupan1890** [comment]
新版已支持下载完自动执行脚本

1. 下载完成后 移动到指定位置
2. 直接调用rclone 上传到指定网盘

都可以实现了，试试看
