### ISSUE TITLE
提一个BUG

### ISSUE THREAD

**Issue by Andrew201801** [liupan1890/xiaobaiyang2#130]
当批量操作对象过多时，软件将提示对象过多，正在异步操作。
但这个提示框无法关闭，停留时间也很久，覆盖了搜索框，影响下一步的搜索操作

![示例](https://ftp.bmp.ovh/imgs/2021/03/ddf52a0bd249fcb1.png)

版本：2.2.3，win10

**Comment by liupan1890** [comment]
看你的截图，应该是高DPI环境吧

1.这个提示，正常应该是6秒后自动关闭（鼠标移动到此提示上就会一直不关闭，移出后6秒自动关闭）
2.这个提示，后面有关闭按钮，可以点击手动关闭提示
![无标题](https://user-images.githubusercontent.com/67817756/110481653-c346cb80-8122-11eb-98e9-67c508038621.png)


3.界面使用的是antd界面库，如果你遇到点击关闭按钮都不能关闭，可能是antd本身的BUG，反正我在本机测试是可以手动关闭和自动关闭的

总结：这个不应该出现，可能只是偶发BUG，下次更新时会更新一下antd的版本

**Comment by Andrew201801** [comment]
嗯嗯，我这边出现的情况是点击X从来都无法关闭，然后等待它自动消失需要等比较久的时间。

由于无法关闭的问题无法复现，不好修复。**因此我有一个建议，能否将显示时间改短一点？**

比如第一次触发这个提示的时候显示六秒（方便不知道的人阅读提示），但之后再触发就只需要显示三秒了，因为此时不需要阅读提示的文本内容，看到提示弹出就明白了。

或者干脆直接都改成三秒，应该也够时间阅读提示了。
