### ISSUE TITLE
有没有考虑做Android版

### ISSUE THREAD

**Issue by RheumGitHub** [liupan1890/xiaobaiyang2#131]
小白羊真的好用，有没有计划整个手机版？
另外，大佬的rss订阅怎么样了，非常期待

**Comment by liupan1890** [comment]
1. 安卓版，github上已经有了，搜一下---不是我！！不是我做的！！不是我做的！！
2. rss现在我没精力去做了，因为年前失业后找不到工作，已经转行送外卖了，每天太忙了

**Comment by RheumGitHub** [comment]
那个手机版试用了下，有点简陋啊，完全比不上小白羊，而且作者好像随性更新。
那现在也只能希望大佬尽快从失业浪潮中摆脱出来了，外卖确实忙啊，忙到可能根本没时间想其他的了……

**Comment by pongfcnkl** [comment]
这个简陋吗？
https://github.com/TigerBeanst/Rn6Pan
