### ISSUE TITLE
exe程序或者linux程序的源代码有没有？

### ISSUE THREAD

**Issue by gk4589210** [liupan1890/xiaobaiyang2#134]
exe程序或者linux程序的源代码有没有？

**Comment by liupan1890** [comment]
全部源码 https://github.com/liupan1890/xiaobaiyang2

**Comment by liupan1890** [comment]
哦，可能是你误会了，win/linux/mac使用的是同一份代码，只是最终打包时的命令不同，分别打包成3个平台的文件了
