### ISSUE TITLE
Webui管理密码长度过长

### ISSUE THREAD

**Issue by Theergold** [liupan1890/xiaobaiyang2#135]
现在的密码长度要求是要大于16位数,如果要讲其作为一个跑在Linux-Server上的后台服务的话,这么长的密码长度显然是很难记住的,所以可以让这个密码长度短一点嘛?比如大于6位就好了
(我是将其放在内网的,所以也不需要担心安全性问题

**Comment by Theergold** [comment]
再补一个问题吧,不想新开issue了
为啥下载地址有长度限制...
Linux挂载硬盘之后我要下到的文件位置有七十多个字符...

**Comment by liupan1890** [comment]
你好

1.密码长度要求是要大于16位，跑在Linux-Server上的后台服务，很难记住的
你可以创建一个文本文件，命名为run.sh 里面写入命令 sudo ./6panserver --isremote=true  --password=abcdefghij123456
就是创建一个脚本文件去启动，这样  **以后直接运行此脚本文件**  就可以了，不用记住密码。16位长度是出于安全考虑，才这么长


2.为啥下载地址有长度限制...
因为windows限制256字符啊，linux限制多少我记不住了可能是不限制。总之因为要考虑到跨平台，所以有长度限制，因为windows最短，所以是按照254限制的

**Comment by liupan1890** [comment]
Linux挂载硬盘之后我要下到的文件位置有七十多个字符...

可以通过软连接解决

1.你的硬盘文件位置 例如/desk/xxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxx  (总之很长)
2.在桌面打开终端命令，输入ln -s /desk/xxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxx  gdown  (这样就在桌面创建了一个软链接)
3.在小白羊，选择下载位置为桌面的gdown文件夹（或直接输入正确的路径/home/用户名/Desktop/gdown）保存

这样，以后下载就会直接下载到/desk/xxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxx下面，但是小白羊里的保存路径却很短（/home/用户名/Desktop/gdown）

如果还想更短一点，那就在根目录打开终端命令，输入ln -s /desk/xxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxx  d
这样下载保存位置就是   /d   (比/home/用户名/Desktop/gdown短很多)
