### ISSUE TITLE
能否增加排序方式

### ISSUE THREAD

**Issue by ymg0827965** [liupan1890/xiaobaiyang2#136]
加一个文件名排序的方式吧，有些剧集啥的有序号这样就能按集数排列对于视频观看比较方便

**Comment by liupan1890** [comment]
![捕获](https://user-images.githubusercontent.com/67817756/111906517-d09d7780-8a8b-11eb-8b95-ab1f1d90c50d.PNG)

现在有按文件名排序（可正序、可倒序），文件大小排序（可从小到大，可从大到小），下载时间排序（可从新到旧，可从旧到新）
所以我没明白你的意思，可能你说的剧集文件名比较特殊没有正常排序？那需要你贴出名字来啊，


如果确实是你的剧集文件名比较特殊没有正常排序，可以通过批量重命名功能，一键去掉那些无用的字符，然后就可以正常排序了，比如上面截图，重命名后：
![捕获2](https://user-images.githubusercontent.com/67817756/111906638-676a3400-8a8c-11eb-8bfe-7b37a644213a.PNG)

**Comment by ymg0827965** [comment]
> ![捕获](https://user-images.githubusercontent.com/67817756/111906517-d09d7780-8a8b-11eb-8b95-ab1f1d90c50d.PNG)
> 
> 现在有按文件名排序（可正序、可倒序），文件大小排序（可从小到大，可从大到小），下载时间排序（可从新到旧，可从旧到新）
> 所以我没明白你的意思，可能你说的剧集文件名比较特殊没有正常排序？那需要你贴出名字来啊，
> 
> 如果确实是你的剧集文件名比较特殊没有正常排序，可以通过批量重命名功能，一键去掉那些无用的字符，然后就可以正常排序了，比如上面截图，重命名后：
> ![捕获2](https://user-images.githubusercontent.com/67817756/111906638-676a3400-8a8c-11eb-8bfe-7b37a644213a.PNG)

谢谢回复，是我没看仔细居然没看到那的根据文件名排序，只看到了右上方的时间和大小排序，以为排序方式都在一个位置，是我眼拙了，麻烦你花时间进行回复.

**Comment by liupan1890** [comment]
没事，太客气
