### ISSUE TITLE
[Error] 22:The response status is not successful. status=429

### ISSUE THREAD

**Issue by HsuMsix** [liupan1890/xiaobaiyang2#137]
首先謝謝開源，辛苦了。

我在追加下載時遇到了 status=429 的錯誤，我的想法這應該是 cold cdn 的下載限制對嗎？

建議可以針對各 Error  code 增加說明文字。

ＰＳ：此帳號為 VIP 帳號

![Image of Error](https://i.imgur.com/L2w4PjM.png)

**Comment by liupan1890** [comment]
https://cloud.tencent.com/developer/section/1190189
> HTTP 429 Too Many Requests响应状态码指示用户在给定时间内发送了太多请求（“限速”）。

可能是并发数太高导致的---我不知道，只是瞎猜

你设置的 几个文件同时启动？每文件几个线程？

我只知道免费账号限制总共2个链接（2个文件+1个线程，或1个文件+2线程）
VIP账号我也不知道6盘的限制是多少个线程

1.可能是并发数太高
2.可能是文件拉取问题

感觉随后自动重试就可以下载了（默认会1分钟左右自动重试）


> 建議可以針對各 Error code 增加說明文字
因为会遇到的网络错误状态码太多了，感觉还是原始错误信息更加直观，我翻译的不准确的话会误导用户
