### ISSUE TITLE
作者大大可以增加一个 “将选中文件名一键全大写” 的功能吗

### ISSUE THREAD

**Issue by Anza7i** [liupan1890/xiaobaiyang2#139]
谢谢作者提供这么好用的客户端，感谢

**Comment by Anza7i** [comment]
可以加在编辑名称的面板里🤭

**Comment by Andrew201801** [comment]
不懂就问，这个功能的应用场景是什么呢？（我不是作者）

**Comment by liupan1890** [comment]
将选中文件名一键全大写
这个使用场景不常见，特定性的功能不会添加，是为了以后维护更简单一些

仅仅从日常使用上说，有的时候只是想一部分文字全部大写（直接批量替换就可以了，输入www，替换为WWW，点击批量替换），很少有需要全部文件名全部大写的时候---我很少用到，准确的说我日常使用没有遇到这个需求。

另外还必须强调，即使是全部转换为大写，也只能做到支持文件名全部转换为大写，不能转换文件路径为大写
这是因为6盘在修改文件路径时会导致异步长时间处理，设置几分钟后才能提示重命名成功，用户体验非常差。无法合理的实现批量修改文件路径的功能，这样一来，批量大写功能更加难以用到了

**Comment by Anza7i** [comment]
> 将选中文件名一键全大写
> 这个使用场景不常见，特定性的功能不会添加，是为了以后维护更简单一些
> 
> 仅仅从日常使用上说，有的时候只是想一部分文字全部大写（直接批量替换就可以了，输入www，替换为WWW，点击批量替换），很少有需要全部文件名全部大写的时候---我很少用到，准确的说我日常使用没有遇到这个需求。
> 
> 另外还必须强调，即使是全部转换为大写，也只能做到支持文件名全部转换为大写，不能转换文件路径为大写
> 这是因为6盘在修改文件路径时会导致异步长时间处理，设置几分钟后才能提示重命名成功，用户体验非常差。无法合理的实现批量修改文件路径的功能，这样一来，批量大写功能更加难以用到了

哈哈，的确挺小众的，谢谢作者，辛苦了

**Comment by Anza7i** [comment]
> 不懂就问，这个功能的应用场景是什么呢？（我不是作者）

有时统一文件格式，得一个一个改，工作量有亿点点大

**Comment by liupan1890** [comment]
> > 不懂就问，这个功能的应用场景是什么呢？（我不是作者）
> 
> 有时统一文件格式，得一个一个改，工作量有亿点点大

这个真的就用简单的批量替换就好了，
先替换.avi--->.AVI
再替换.mp4-->.MP4
等等等等

因为你会用到的文件格式就那么几个，最多也就十来种吧？平均替换个4-5次的事

![捕获](https://user-images.githubusercontent.com/67817756/112740670-4c7a5100-8fb1-11eb-8950-47fc3bb9a14c.PNG)

**Comment by Andrew201801** [comment]
我受到了启发，作者可以搞一个插件接口，然后一些小众的功能可以让我们用插件来做，作者不用来维护。
不过插件接口可能工作量会很大

**Comment by Qixingchen** [comment]
6pan 可以用 webdav 挂载为文件夹 然后你自己写脚本就行了

**Comment by liupan1890** [comment]
> 6pan 可以用 webdav 挂载为文件夹 然后你自己写脚本就行了

最方便可行的方法了，插件的话，你又要学习我给出的接口，又要熟悉js。webdav的话什么编程语言都可以，形式上也更方便

**Comment by Andrew201801** [comment]
搜嘎，谢谢谢谢！
