### ISSUE TITLE
关于公告提一个思路

### ISSUE THREAD

**Issue by anye1998** [liupan1890/xiaobaiyang2#14]
看到程序的公告是由你手动更新的，所以我想能不能从 https://www.cnblogs.com/6pan/ 上把第一个文章标题抓取下来，这不就是公告了吗，甚至还能采集到文章时间作为公告发布时间。而且还可以抓取其他的可以作为历史公告。

不知道能不能实现，我就是提一个思路。

**Comment by liupan1890** [comment]
嗯，思路是正确的，我原来想的是定时拉取6盘的一个js，在里面截取出公告信息来。

并不是因为没想好怎么提取导致公告，导致现在要手动更新

1. 除了6盘的公告，在后期可能也会显示我的公告--比如版本更新之类，肯定是比较重要的信息才会公告显示
2. 公告信息会和RSS订阅里的公告板块联动，包括操作教程现在也只是发了几个gif，后期也都会完善补齐

所以我想的是等以后正式版本发布了再上线服务器，加上自动更新公告。现在只是测试版，后期变动可能会比较大，我就只是简单地写死了公告，导致需要我手动更新。后期会改成及时的自动更新公告的
