### ISSUE TITLE
关于文件名排序功能的BUG

### ISSUE THREAD

**Issue by Andrew201801** [liupan1890/xiaobaiyang2#140]
当同一文件夹下文件数量较多时（我的这个文件夹有743个文件），会出现根据文件名排序功能出现错误的BUG
具体来讲就是在一部分区间内是有序的（从A-Z）但之后又会从A重新开始排序

区间有序：
![](https://gitee.com/AndrewYu/pictures/raw/master/img/image_51.png)

这个貌似乱序了？：
![](https://gitee.com/AndrewYu/pictures/raw/master/img/image_52.png)

是拉取文件时的limit设置得比较小的原因吗？但这个值没有上限，因为也会有人文件夹里有几千个文件。那么可以拉取完文件后，重新排序一次？

**Comment by liupan1890** [comment]
嗯，看截图，这是个BUG，我还没想到BUG的原因，容我想一想

**Comment by liupan1890** [comment]
确实是BUG，已修正，重新下载最新版覆盖安装即可

**Comment by Andrew201801** [comment]
好的，谢谢作者！
