### ISSUE TITLE
localhost 密码问题

### ISSUE THREAD

**Issue by ColderCoder** [liupan1890/xiaobaiyang2#141]
当以localhost访问时，密码不生效:
1. -isremote true，反代到本地，无需密码
2. -isremote false，密码设置无效

对于不想把端口暴露给公网，或本地访问需要密码的用户来说，目前的策略比较难受。

**Comment by liupan1890** [comment]
-isremote true 远程管理模式，远程通过IP+密码访问6panserver服务。不支持localhost访问
-isremote false 本地模式，不需要密码

1.不想把端口暴露给公网
直接本地使用小白羊

2.本地访问需要密码
本地访问不支持密码，本地就是本机，已经在你电脑上了，不需要密码了（有密码有什么用呢，下载的文件在我的电脑都能看到）（如果是考虑6盘账号的问题，可以每次使用后都退出账号，下次启动需要重新输入账号+密码重新登录）

**Comment by liupan1890** [comment]
补充一句，
> 对于不想把端口暴露给公网
第一种：手动命令启动远程管理模式
实际上国内绝大多数人，家庭，公司，都是**入户宽带--路由器--电脑**这样，
此时命令行启用小白羊暴露的都是局域网地址，无法通过外网IP+端口访问。

只有在**购买的VPS、云主机、虚拟服务器**上，才可以直接通过公网IP+端口访问。

家庭用户如果想通过公网IP+端口形式远程访问，必须自己手动设置路由器的端口映射


第二种：直接双击小白羊程序运行
此时是运行在本地模式，绑定了localhost，本身并不支持IP+端口形式访问。也就彻底没有任何暴露端口的隐患

**Comment by xiaokaixuan** [comment]
@liupan1890  他的意思应该是部署在云主机或VPS时，通过公网IP:29375会提示需要输入密码。但是用端口转发工具将本地的29375端口转发至公网的29375端口，然后通过localhost:29375访问能直接绕过密码。这块确实有问题，好像。。。

**Comment by xiaokaixuan** [comment]
> 本地端口转发应该自己鉴权吧

如果我将我本地的29375端口转发至别人的公网IP:29375，然后通过localhost:29375访问，不是可以自由出入

**Comment by Qixingchen** [comment]
> > 本地端口转发应该自己鉴权吧
> 
> 如果我将我本地的29375端口转发至别人的公网IP:29375，然后通过localhost:29375访问，不是可以自由出入？

你确定有这样的情况？而不是两边用了同样的密码

**Comment by ColderCoder** [comment]
这里可能有一些误解，我的应用情景是，在无图形界面的vps上运行小白羊，远程使用。我想要通过反代，使用域名访问，并不想公网通过29375端口访问。
反代到localhost，密码不生效，反代到vps公网IP，似乎也不生效。

**Comment by xiaokaixuan** [comment]
@Qixingchen 我用浏览器无痕模式测试过了，你可以自己试下。

**Comment by liupan1890** [comment]
> 如果我将我本地的29375端口转发至别人的公网IP:29375，然后通过localhost:29375访问，不是可以自由出入？

是的，你说得对，在此情况下（别人使用命令行手动启动6panserver.exe --isremote=true --password=1111111111111111，你使用本地端口转发映射到别人的公网IP:29375，然后通过localhost:29375访问），这是一个严重的安全BUG，

利用此BUG可以查看别人6盘的的文件列表，下载别人6盘内的文件到  **别人的**  电脑，删除别人6盘内文件
所以此BUG危害最大的场景是删除别人6盘内的文件

幸运的是，入侵者需要满足以下条件：
1.知道别人的公网IP
2.别人是VPS（直接绑定的公网IP），不是家庭宽带用户（电脑不是连接的路由器）
3.别人手动命令行启动远程管理模式

因为小白羊现在的用户并不多，我从每个版本的下载量上分析大约有1000人在使用小白羊。这1K人中又大部分人是直接使用的小白羊，而没有使用远程管理模式。入侵者想要通过随机的IP端口扫描方式碰撞出别人的IP也不是一件容易的事


所以此BUG的实际危害性并不高

**Comment by liupan1890** [comment]
>上传文件显示需要electron环境，但我已经正确安装
提示需要electron环境，是我提示信息不够准确，实际上，**上传功能只支持本机使用小白羊（不能用浏览器）直接上传本机的文件**。
远程管理模式下无法上传文件（上传队列需要6panserver这个文件去管理上传，远程管理时本机没有6panserver，他是运行在VPS上）


>之后在tg群组听说不支持Ubuntu/Debian，所以我当前没有在Linux使用小白羊了
小白羊支持Ubuntu/Debian，只有无UI的linux需要使用远程管理模式，有UI的linux大部分都能直接运行小白羊Electron，

但确实有用户反馈说有的linux，无法启动Electron，导致无法使用

**Comment by ColderCoder** [comment]
我想要做的工作：将VPS的文件上传到6pan。
webdav限制上传，six-cli上传文件分块过小(4MB) 导致上传速度极慢。很遗憾小白羊目前无法做到这一点，期待更新

________________________________
发件人: liupan1890 ***@***.***>
发送时间: 2021年3月31日星期三 19:40
收件人: liupan1890/xiaobaiyang2
抄送: ColderCoder; Author
主题: Re: [liupan1890/xiaobaiyang2] localhost 密码问题 (#141)


上传文件显示需要electron环境，但我已经正确安装

提示需要electron环境，是我提示信息不够准确，实际上，上传功能只支持本机使用小白羊（不能用浏览器）直接上传本机的文件。
远程管理模式下无法上传文件（上传队列需要6panserver这个文件去管理上传，远程管理时本机没有6panserver，他是运行在VPS上）

之后在tg群组听说不支持Ubuntu/Debian，所以我当前没有在Linux使用小白羊了
小白羊支持Ubuntu/Debian，只有无UI的linux需要使用远程管理模式，有UI的linux大部分都能直接运行小白羊Electron，

但确实有用户反馈说有的linux，无法启动Electron，导致无法使用

―

**Comment by liupan1890** [comment]
> 我想要做的工作：将VPS的文件上传到6pan。 webdav限制上传，six-cli上传文件分块过小(4MB) 导致上传速度极慢。很遗憾小白羊目前无法做到这一点，期待更新

需要你的VPS使用的是Ubuntu 16.04桌面版系统
![屏幕截图 1604](https://user-images.githubusercontent.com/67817756/113240360-26212200-92df-11eb-82c5-d211f05e6ccf.png)


方便的话回复我一下你使用的VPS的官网，我最近在寻找大流量又便宜的VPS做文件中转，可能你对这方面有经验？推荐给我几个厂家吧

**Comment by ColderCoder** [comment]
vps一般是server版系统，我没试过安装桌面环境后能不能正常使用。

你的需求可能不仅仅是大流量，可能还需要大存储。
注意，廉价是有代价的，自行斟酌，我只是列举我使用过且尚能接受的：
仅仅是便宜大流量可以去看看racknerd，或者收一个二手，超流量限速10Mbps不停机。
存储型的目前在用hotlineserver，打折入的，现在价格可能不太好。hosthatch最近有好价的话可以看看。

拿不定主意就buyvm(frantech)，无限流量，可以加购storage slab，有卢森堡机房。不是很追求廉价的话我推荐这个。

________________________________
发件人: liupan1890 ***@***.***>
发送时间: 2021年4月1日星期四 11:41
收件人: liupan1890/xiaobaiyang2
抄送: ColderCoder; Author
主题: Re: [liupan1890/xiaobaiyang2] localhost 密码问题 (#141)


我想要做的工作：将VPS的文件上传到6pan。 webdav限制上传，six-cli上传文件分块过小(4MB) 导致上传速度极慢。很遗憾小白羊目前无法做到这一点，期待更新

需要你的VPS使用的是Ubuntu 16.04桌面版系统
[屏幕截图 1604]<https://user-images.githubusercontent.com/67817756/113240360-26212200-92df-11eb-82c5-d211f05e6ccf.png>

方便的话回复我一下你使用的VPS的官网，我最近在寻找大流量又便宜的VPS做文件中转，可能你对这方面有经验？推荐给我几个厂家吧

―

**Comment by liupan1890** [comment]
非常感谢
