### ISSUE TITLE
作者考虑加个阿里云盘的功能吗

### ISSUE THREAD

**Issue by LuJiaWeiwei** [liupan1890/xiaobaiyang2#142]
阿里云盘的网页版也有点拉胯，不支持多文件下载

**Comment by liupan1890** [comment]
阿里云盘说会在4月上线PC版（win/mac）
等官方版上线后再说吧，如果功能很完善，就没有开发的必要，再官方版上线后，我会跟进一下，对小部分资源，6盘用户可以转存到阿里网盘

这都是以后的事，等等看
