### ISSUE TITLE
Mac版下载报错了

### ISSUE THREAD

**Issue by HaitaoShi** [liupan1890/xiaobaiyang2#144]
可能是证书的问题。4:SSL/TLS handshake failure: Invalid certificate format

**Comment by liupan1890** [comment]
请参阅 https://github.com/liupan1890/xiaobaiyang2/issues/127


可能是你用了代理，或者系统时间不对，或者你用的linux但内置ssl库版本不符

你没说是啥系统，用win64举例

解决方案一:
在aria的配置文件末尾增加一行
6盘小白羊版win64\electron\resources\aria2.conf
``````
check-certificate=false
``````

解决方案二：
删除  6盘小白羊版win64\electron\resources\aria2c.exe  这个文件，使用内置golang下载引擎下载

任选一个，重启小白羊生效

**Comment by liupan1890** [comment]
有的时候ssl错误是6盘CDN上配置的证书过期了，等一点时间，CDN会自动更新证书，就会自动恢复，不报ssl错误了。

所以就是说：
1.以前可以正常下载，今天突然ssl，明天可能就又自动恢复了。根本不需要修改任何配置
2.通过方案一修改后可以彻底解决此问题---不检查ssl了就不会报错

**Comment by HaitaoShi** [comment]
谢谢！

**Comment by HaitaoShi** [comment]
我生活在英国，时区不同，但是之前一直用没有问题。我用的是M1的Macbook pro，使用了方案一并没有解决问题。。。

**Comment by liupan1890** [comment]
> 我生活在英国，时区不同，但是之前一直用没有问题。我用的是M1的Macbook pro，使用了方案一并没有解决问题。。。

注意要重启电脑才生效（实际上是重启aria进程才生效，需要你手动的结束进程，干脆就直接重启电脑吧，最稳妥）

**Comment by HaitaoShi** [comment]
谢谢！我什么都没改，电脑重启一次就正常了！

**Comment by liupan1890** [comment]
ok
