### ISSUE TITLE
提一个BUG

### ISSUE THREAD

**Issue by Andrew201801** [liupan1890/xiaobaiyang2#145]
有时候点击回收站后，右侧的文件列表就会无法刷新。
以前的版本就出现过，不过重启一下客户端就会解决，就没有提BUG，今天无聊就过来提一下BUG

![](https://gitee.com/AndrewYu/pictures/raw/master/img/Snipaste_2021-04-07_12-32-45.png)

![](https://gitee.com/AndrewYu/pictures/raw/master/img/Snipaste_2021-04-07_12-32-56.png)

![](https://gitee.com/AndrewYu/pictures/raw/master/img/Snipaste_2021-04-07_12-33-12.png)

**Comment by liupan1890** [comment]
呃，说的不是很仔细，
![无标题](https://user-images.githubusercontent.com/67817756/113979348-b7603d80-9877-11eb-8467-c3aaeefc8b28.png)

如图，点击回收站后，然后怎么操作？会触发BUG

>有时候点击回收站后，右侧的文件列表就会无法刷新


1.是说如上图，已经点击了回收站，然后不操作，等半个小时，这半个小时内右侧文件列表都不会刷新（比如中间有离线任务下载完了），是这个意思吗？

2.是说点击了回收站后，又点击了侏罗纪世界2，不能显示出侏罗纪世界2下面的子文件夹？

**Comment by Andrew201801** [comment]
> 呃，刚看到图，我研究一下
> 
> 就是点击了Python爬虫，此时右边还是一直显示回收站的文件列表
> 
> 那么
> 
> 1. 必须要重启才能生效吗？点击右侧文件列表顶部的“”刷新“”按钮呢？刷新按钮管用吗？
> 2. 点击其他文件夹呢？比如点击Harray Potter，点击全新老男孩，是再点击其他的文件夹就正常显示了还是点啥都不管用必须重启呢？

今天捣鼓了一下，把这个BUG复现了，结论是只能重启，其他方法都不好使。
我把复现过程录屏成gif了，图片太大，gitHub加载不出来，链接：
https://gitee.com/AndrewYu/pictures/raw/master/img/%E7%A4%BA%E4%BE%8B.gif

**Comment by liupan1890** [comment]
简单检查了一下，是因为文件太多时，可能会有重复键
``````
[Vue warn]: Duplicate keys found during update: "48dc42618052dd2261575a87e1968466" Make sure keys are unique.
``````

遇到重复键时，会导致这个文件一直显示，不会被刷新掉。

当你点击回收站，1万个文件，有100个重复的。
当你点击其他的文件夹时（比如点击Python爬虫），此时右侧文件列表会显示回收站100个+Python爬虫内的文件列表

看起来就是一直显示回收站，没有显示Python爬虫内的文件。实际上此时你往下滚动到底部，就看到Python爬虫内的文件了。前100个是回收站内的文件

总之，我知道BUG在哪了，下次更新时会修复此BUG，一般回收站内文件不是那么多时，就不会遇到此BUG了
