### ISSUE TITLE
可以注明下token的完整格式嘛，软件内的说明链接打不开

### ISSUE THREAD

**Issue by zhezhe168** [liupan1890/xiaobaiyang2#146]
可以注明下token的完整格式嘛，软件内的说明链接打不开

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/113980821-83861780-9879-11eb-92f6-510ffa3bfdb9.png)

如果你是说的这里的cookie，请查看操作教程

![无标题2](https://user-images.githubusercontent.com/67817756/113980839-884acb80-9879-11eb-9316-cd8571c75667.png)
