### ISSUE TITLE
希望加入下载完成自动关机的选项

### ISSUE THREAD

**Issue by llj1998** [liupan1890/xiaobaiyang2#148]
经常\在夜里挂机下资源，希望加入下载完成自动关机的选项

**Comment by liupan1890** [comment]
你好

这个功能暂不考虑，因为我技术有限，需要考虑3种系统的关机api，可能还需要考虑运行权限，
实际上是因为我现在没有这么多时间去维护小白羊，等我以后找到稳定的工作了，有时间了再考虑吧，抱歉

**Comment by Andrew201801** [comment]
> 经常\在夜里挂机下资源，希望加入下载完成自动关机的选项

![image](https://user-images.githubusercontent.com/35620837/114339868-d6691300-9b88-11eb-83a6-72b3a0527ffa.png)
可以用批处理脚本实现，不会写的话网上也有现成的

**Comment by Qixingchen** [comment]
> > 经常\在夜里挂机下资源，希望加入下载完成自动关机的选项
> 
> ![image](https://user-images.githubusercontent.com/35620837/114339868-d6691300-9b88-11eb-83a6-72b3a0527ffa.png)
> 可以用批处理脚本实现，不会写的话网上也有现成的

这个是在每个文件下载完后就调用的 除非只下一个文件不然没法用（或者还要对比下文件列表）
