### ISSUE TITLE
这是啥？

### ISSUE THREAD

**Issue by saludossol** [liupan1890/xiaobaiyang2#149]
![QQ截图20210409201827](https://user-images.githubusercontent.com/76832306/114178955-f920df00-9970-11eb-9c9a-f317df8ae224.png)

**Comment by saludossol** [comment]
版本是2.2.3，。。。。

**Comment by liupan1890** [comment]
百度得到：
>429 Too Many Requests (太多请求)
当你需要限制客户端请求某个服务的数量，也就是限制请求速度时，该状态码就会非常有用。在此之前，有一些类似的状态码。例如“509 Bandwidth Limit Exceeded”。
如果你希望限制客户端对服务的请求数，可使用 429 状态码，同时包含一个 Retry-After 响应头用于告诉客户端多长时间后可以再次请求服务。

简单说就是6盘感觉你短时间内并发请求太多（小白羊设置，n个文件同时启动X每个文件n个线程）
稍后再下载即可。
推荐3文件X2线程


总结：6盘的限制，非程序BUG

**Comment by liupan1890** [comment]
以我平时使用的经验看，有的时候是你线程数设置的太高，有的时候是6盘CDN回源缓慢，在这一秒你要下载的这个文件它没回源拉取到（或速度慢），就会返回429，等几分钟、几十分钟、几小时  以后再下载，就可以正常下载不报错了

**Comment by saludossol** [comment]
哦哦，感谢解答
