### ISSUE TITLE
CD包付费主题不可见

### ISSUE THREAD

**Issue by 0x8000FFFF** [liupan1890/xiaobaiyang2#152]
随便找了几个例子：
http://121.5.144.84/https/www.cdbao.net/thread-1469555-1-1.html
http://121.5.144.84/https/www.cdbao.net/thread-1450499-1-1.html
http://121.5.144.84/https/www.cdbao.net/thread-1452654-1-1.html
http://121.5.144.84/https/www.cdbao.net/thread-1452655-1-1.html

**Comment by liupan1890** [comment]
因为需要碟币，我的账号已经没有碟币了，所以无法购买。

**Comment by 0x8000FFFF** [comment]
明白了，谢谢！
