### ISSUE TITLE
关于下载文件的存储一个建议

### ISSUE THREAD

**Issue by ldqs365** [liupan1890/xiaobaiyang2#153]
例如我想下载一个文件，我想要直接把这个文件/文件夹下到指定的一个区域，不构建目录树，比如，我要下载aaa->bbb->ccc->test.mp4到E;/，我希望直接下载test.mp4文件，不要创建aaa->bbb->ccc目录，同理，我想下ccc文件夹，不要创建aaa->bbb

**Comment by liupan1890** [comment]
嗯，我明白你的意思。
但实际操作中也会有各种问题，假设我们把搜有文件都下载到D:\Down\下
``````
6盘根目录/aaa/bbb/ccc/test.mp4

1.我点击到6盘根目录/aaa/bbb/ccc/，点击test.mp4的下载按钮
最终得到D:\Down\test.mp4
2.我导航到6盘根目录/aaa/bbb，点击ccc的下载按钮
最终得到D:\Down\ccc\test.mp4
``````

如上，冲突来了，同一个文件，会被下载2次。并没有实际意义，仅仅是因为我导航到哪里点击的下载按钮

``````
6盘根目录/aaa/bbb/20200101/test.mp4
6盘根目录/aaa/bbb/20200303/test.mp4
6盘根目录/aaa/bbb/20200505/test.mp4
1.我点击到6盘根目录/aaa/bbb/20200101/，点击test.mp4的下载按钮
最终得到D:\Down\test.mp4
2.我导航到6盘根目录/aaa/bbb/20200303/，点击test.mp4的下载按钮
最终得到D:\Down\test.mp4
``````

如上，又冲突了，我明确知道我下载的是2个不同版本的文件，但因为最终的文件名（test.mp4），有冲突了。假如自动重命名为（test.mp4，test(1).mp4）虽然能下载，但我根本不知道test.mp4是哪个版本

所以操作上必须注意要点击到6盘根目录/aaa/bbb/，然后点击/20200101/和/20200303/的下载按钮
最终得到D:\Down\20200101\test.mp4    和  D:\Down\20200303\test.mp4

类似的各种冲突还有很多（比如文件名重名），这个时候就需要用户注意自己的操作，在哪里点下载，保存到哪里，哪些文件已经下载了不能重新下载父文件夹（会导致一个文件下载2遍）。

你看，最安全的，最简单的，就是完全按照6盘路径去保存。下载完怎么移动都是用户自己的事，不用考虑下载操作

**Comment by ldqs365** [comment]
确实可能存在这种问题

**Comment by ldqs365** [comment]
然后现在我发现了一个新的关于下载的问题，就是文件夹会显示0b，但文件夹内是存在文件的，进行批量下载的时候会提示创建0个文件下载任务

**Comment by liupan1890** [comment]
1.文件夹会显示0b
是6盘本身对文件夹体积计算有延时，一般是你新离线成功的文件夹，过几天才会显示正确的文件夹体积

2.批量下载的时候会提示创建0个文件下载任务
那么你留意没留意，是仅仅是提示错误（应该提示创建XXX个文件下载任务），还是根本没有下载里面的文件？
就是看一下，文件最终下载了没？

**Comment by ldqs365** [comment]
哦，体积这方面我知道了。

我看过了，批量下载0b文件夹的时候，文件最终没有被添加到下载列表里面，也就是文件没被下载

**Comment by liupan1890** [comment]
我看到这两天6盘似乎无法正常使用，等它恢复了，我会测试一下这个问题，看是否是有未知的BUG

**Comment by Andrew201801** [comment]
> 我看到这两天6盘似乎无法正常使用，等它恢复了，我会测试一下这个问题，看是否是有未知的BUG

对，批量下载文件的时候是正常的，但批量下载文件夹就无法下载
