### ISSUE TITLE
RaspberryPi arm64版本无法执行编译的server

### ISSUE THREAD

**Issue by Annier-z** [liupan1890/xiaobaiyang2#154]
使用RaspberryPi 4B，官方64位系统，无法执行编译的server，请问是否存在兼容性设置或者如何正确运行？

**Comment by Annier-z** [comment]
内核版本aarch64，与arm64存在一定差异

**Comment by liupan1890** [comment]
我实在Ubuntu16.04上使用如下命令编译的：
``````
set CGO_ENABLED=0
set GOOS=linux
set GOARCH=arm64
go build -ldflags="-s -w -extldflags '-static -fpic'" -o ./6panserverarm64.exe ../src/
pause
``````

所以是适合arm64，所以无法在aarch64运行，我稍后试一下看能否编译aarch64版本

**Comment by liupan1890** [comment]
1.在我的电脑上是编译不通过的（ubu20.04 / intel i5）（cmd/go: unsupported GOOS/GOARCH pair linux/aarch64）
所以应该就是通用arm64
2.我没接触过树莓派，无法帮到你，我也不知道是否是因为编译目标平台原因
3.可以自行尝试编译https://github.com/liupan1890/xiaobaiyang2/tree/main/source-6panserver
如果你是在你自己的树莓派上编译，那理论上就肯定可以运行了，之前有用户说过树莓派，可以正常运行，但不知道他是安装的什么系统。也不知道他的版本。只能你自己编译测试了
