### ISSUE TITLE
6盘管理员希望开发者不要做有关SHA1分享或调用秒传接口的相关功能 

### ISSUE THREAD

**Issue by ChenBill900703** [liupan1890/xiaobaiyang2#155]
管理员有明确表示这样会造成法律问题 希望开发者能够收手 不要让6盘变成下个百度网盘

**Comment by gk4589210** [comment]
购买源代码，给个联系方式

**Comment by liupan1890** [comment]
> 购买源代码，给个联系方式

小白羊是开源的，也是完全免费的，现在并没有任何的收费形式

如果你是想要商业使用源码，随便用就好，不需要购买

**Comment by gk4589210** [comment]
购买最新版的源码，这上面好像没有推送？

**Comment by gk4589210** [comment]
并且我编译也遇到了困难，没编译成功，有一些错误，你看留个V信或者QQ可否？
