### ISSUE TITLE
软件已经不再开源了吗？

### ISSUE THREAD

**Issue by RivenNero** [liupan1890/xiaobaiyang2#156]
查看最近的提交记录，发现全都是关于 README.md 和 Changelog 的 commit，关于源码的 commit 几乎没有了。不开源的话建议在 README.md 中写出。

**Comment by liupan1890** [comment]
是因为当前发布的安装包版本为2.2.3，开源代码版本也是2.2.3

自2.2.3版本发布后（当天也上传了开源代码），并没有发布新的版本，只是一些小的问题修正，并没有更新版本号，所以就没有新的commit

我在大陆，更新github很卡，没有代理，经常失败，懒得更新。只有在版本更新时才会同步一次

**Comment by liupan1890** [comment]
截图


![捕获](https://user-images.githubusercontent.com/67817756/115242143-2e3ce680-a154-11eb-8cca-1b9f7769f210.PNG)

**Comment by RivenNero** [comment]
嗷嗷好的，如果需要代理的话我可以免费提供，可以直接邮件联系我，或者 telegram 联系我，支持一波小羊毛。
