### ISSUE TITLE
6盘挂了，问下各位大佬还有类似的软件推荐吗？

### ISSUE THREAD

**Issue by hsiayuchih** [liupan1890/xiaobaiyang2#159]
先在此谢过了，一开始用6盘就是看上了他能下百度云，现在挂了真不知道还有什么软件能下百度云...

**Comment by pongfcnkl** [comment]
官方客户端 开svip

**Comment by hsiayuchih** [comment]
> 官方客户端 开svip

开过，一样不能满速，速度不稳定，恶心的要死

**Comment by windfsy** [comment]
> 先在此谢过了，一开始用6盘就是看上了他能下百度云，现在挂了真不知道还有什么软件能下百度云...
油猴脚本“百度网盘简易下载助手（直链下载复活版）”，这个挺好用的，基本是满速

**Comment by windfsy** [comment]
> 先在此谢过了，一开始用6盘就是看上了他能下百度云，现在挂了真不知道还有什么软件能下百度云...

油猴脚本“百度网盘简易下载助手（直链下载复活版）”，这个挺好用的，基本是满速

**Comment by hsiayuchih** [comment]
> > 先在此谢过了，一开始用6盘就是看上了他能下百度云，现在挂了真不知道还有什么软件能下百度云...
> 
> 油猴脚本“百度网盘简易下载助手（直链下载复活版）”，这个挺好用的，基本是满速

是要配合IDM下载吗？
