### ISSUE TITLE
离线任务时间点卡在10-28

### ISSUE THREAD

**Issue by wsx0963** [liupan1890/xiaobaiyang2#16]
![圖片](https://user-images.githubusercontent.com/42093236/97800990-7e8ebd80-1c74-11eb-8e76-47f6bfb0454a.png)
可以添加离线任务，但是小白羊版的时间到10-28之后就不会显示了，刷新也没用
官方的显示正常。

**Comment by liupan1890** [comment]
我这里倒是正常显示11-01的离线任务，我翻了一下代码，发现BUG可能是出在任务数量上，小白羊是默认拉取了500条（从旧到新）离线任务记录，假如你的任务累积比较多（超过500），那最新的都看不到了，我改一下，下个版本会修正此BUG

但是不知道你的BUG是不是这个原因导致的，请问是离线任务数》500了吗？

**Comment by wsx0963** [comment]
> 
> 
> 我这里倒是正常显示11-01的离线任务，我翻了一下代码，发现BUG可能是出在任务数量上，小白羊是默认拉取了500条（从旧到新）离线任务记录，假如你的任务累积比较多（超过500），那最新的都看不到了，我改一下，下个版本会修正此BUG
> 
> 但是不知道你的BUG是不是这个原因导致的，请问是离线任务数》500了吗？

![圖片](https://user-images.githubusercontent.com/42093236/97805061-bf93cb80-1c8e-11eb-8886-c59dbf0af1e3.png)
似乎是的

**Comment by liupan1890** [comment]
OK！
