### ISSUE TITLE
作者大大你好，AppData目录下的个人信息有保存离线历史记录吗

### ISSUE THREAD

**Issue by Anza7i** [liupan1890/xiaobaiyang2#160]
6盘暂时还是未能开放，过去的磁力记录获取不到。如果使用客户端有记录这些信息的话，希望能提供个小工具把数据反序列化出来。

**Comment by liupan1890** [comment]
https://github.com/liupan1890/xiaobaiyang2/tree/main/source-6panserver/src/data

``````
Down.go  下载记录
Upload.go 上传记录
User.go 账号
Setting.go 设置
Range.go 断点上传，断点下载记录
WWW.go UI资源文件
``````

所以，在AppData，user.db里面，没有保存用户的离线记录，都是时时联网显示的

因为像文件列表，离线记录，都是需要频繁刷新的

**Comment by Anza7i** [comment]
> https://github.com/liupan1890/xiaobaiyang2/tree/main/source-6panserver/src/data
> 
> ```
> Down.go  下载记录
> Upload.go 上传记录
> User.go 账号
> Setting.go 设置
> Range.go 断点上传，断点下载记录
> WWW.go UI资源文件
> ```
> 
> 所以，在AppData，user.db里面，没有保存用户的离线记录，都是时时联网显示的
> 
> 因为像文件列表，离线记录，都是需要频繁刷新的

好可惜，谢谢作者
