### ISSUE TITLE
双击打开文件夹

### ISSUE THREAD

**Issue by Lwife** [liupan1890/xiaobaiyang2#162]
**希望可以添加双击打开文件夹功能。**
单击选择文件夹确实很方便，但是相较之下打开文件夹的动作远比选择文件夹的动作多，但是目前只支持点击文件夹的名字或者通过左侧的目录树打开文件夹，甚至是点击文件夹名字上下方的空白部分都不可以。
所以希望可以点击文件夹的任意地方打开文件夹。

**Comment by liupan1890** [comment]
在阿里云盘小白羊版的设置里，已经提供了双击整行打开的选项

另：应该发在阿里云盘小白羊版项目里，6盘很早就停服了
