### ISSUE TITLE
文件夹大小显示异常

### ISSUE THREAD

**Issue by Lwife** [liupan1890/xiaobaiyang2#163]
在打开一个文件夹之前显示的文件夹大小一直为0，打开文件夹后退出变为正常。

打开文件夹之前：
![打开文件夹之前](https://user-images.githubusercontent.com/44720162/142520818-d5526291-977f-4ea7-866a-0f6efa72f328.png)

打开文件夹之后：
![Snipaste_2021-11-19_08-48-34](https://user-images.githubusercontent.com/44720162/142520932-0cdc1cfd-8bf0-450d-a34b-6070494952a7.png)

**Comment by liupan1890** [comment]
请参阅设置里的提示

文件夹体积是后台异步慢慢计算的（让用户无感，1秒最多计算3个文件夹的体积--不包括子文件夹）

当你进入文件夹时，也会同步计算更新一下这个文件夹的体积--不等后台异步计算了

一般，第一次登陆这个账号，5000个文件夹，需要等约半个小时以后，才能计算完全部的文件夹体积

注：应该发在阿里云盘小白羊项目里，这是6盘项目，已停服
