### ISSUE TITLE
Mac版调用播放器后不播放视频

### ISSUE THREAD

**Issue by hangxu0304** [liupan1890/xiaobaiyang2#17]
试过IINA和ominiplayer，都是点击播放按钮后会打开对应的播放器app，但不播放视频文件

**Comment by liupan1890** [comment]
我去测试一下

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97828517-43d36680-1d02-11eb-9adf-336003ff18d3.png)

因为之前开发的时候测试过很多次了，这次就随便找了个视频测试，没有问题的可以正常播放


#### 重点说一下原理：
1. 获取视频的下载地址
2. 把下载地址给播放器播放  iina.app "https://xxxxxxxxxxxxxxx"

这个功能非常的简单，只要播放器能弹出来，就说明程序**功能**上没问题

#### 那么为什么不能播放呢？

1. 网络问题-----可能因为网络问题播放器下载不下来视频，这是跟你的网络、设置、播放的文件有关的，我这里网络测试没问题可以正常播放
（我是VIP账号，并且肯定没因为下载量过多或者线程过多被6盘限速，播放的视频是英语学习教程不涉及版权、黄、的问题）

2. 视频格式问题-----可能你现在播放的视频文件损坏，或者不是视频（比如是压缩包伪装的），或者格式比较特殊播放器不支持

#### 检查步骤
1. 找一个其他的mp4视频试试，明确是所有视频（和音频mp3.flac,ape,wav）都不能播放？还是这一个不能？
2. 我不用mac，mac是否允许播放器联网？我记得安装了iina默认就是可以联网的，mac有安全软件吗？（360？）
3. 针对不能播放的这个视频，直接下载看看能否正常下载，看一下 下载速度是否太慢
4. 直接点击“”复制下载链接“”按钮，复制这个视频的URL，然后打开iina，点击播放网络输入url


#### 总之，跟程序关系不大，并不是功能性BUG，我没办法帮到你啊

**Comment by hangxu0304** [comment]
感谢作者及时回复。
我刚刚试着把IINA从1.0.7更新到了1.1.0最新版，就可以正常播放了。
然后又测试了一下VLC，也可以正常播放。
再次感谢。
