### ISSUE TITLE
手机登录和用户名登陆都失败, cookies登陆成功

### ISSUE THREAD

**Issue by Jacobax** [liupan1890/xiaobaiyang2#18]
前两者都失败显示404, 确认手机用户名密码都没错, 最后用不推荐的cookies才成功登陆

**Comment by liupan1890** [comment]
嗯，已经发布最新版，是因为6盘今天调整了域名，之前小白羊里是写死的，新版已调整为动态更新了，

总之，使用新版替换旧版文件就好了
