### ISSUE TITLE
请问会有提取资料夹内所有档案下载连结的功能吗

### ISSUE THREAD

**Issue by yi0332** [liupan1890/xiaobaiyang2#19]
档案数量一多起来,一个一个提交到aria2太痛苦了
谢谢你

**Comment by liupan1890** [comment]
你好，这个功能不会有

6盘限制，当短时间内创建了3个下载链接后，就不能继续创建下载链接，返回文件系统忙（需要等几秒或几十秒或几分钟以后，才可以继续创建，看6盘的限制了）

你想要点击文件夹，复制文件夹内全部文件的下载链接，
如果是从程序上实现，那可能需要你点击复制按钮后等几秒钟到几分钟甚至更长
（就是循环去创建下载链接，创建了几个就要等不知道多长时间，再创建几个，再等，再创建，再等以此循环）

要看文件夹内具体有几个文件，比如有300个文件，那可能要等十几分钟了-------重点是这个时间我不知道是多久

这个功能从程序上讲很难看，不够优雅，所以我也不会做这个功能


另外，6盘的限制是一直在动态调整的，总体上是越来越严

最开始，免费线路满速
后来，VIP才满速
再后来5文件，5线程
再后来短时间内创建3个以上会返回“”文件系统忙“”的错误
再后来创建下载链接的IP和实际下载的IP必须相同（你的电脑创建下载链接，发给VPS下载，不行了，必须同IP）

所以也说不定以后会出现更加严格的限制，所以我不想去刺激6盘

**Comment by liupan1890** [comment]
补充一句，短时间内创建多条链接，是指程序循环创建，基本上是1秒一条的速度，肯定会触发文件系统忙得错误，我也不知道6盘具体的是怎么限制的，比如几秒内几条？比如怎么限速。我都不知道的

**Comment by yi0332** [comment]
作者想请教你linux 版本的直链提取是不会开放吗?
被应用提示远程操作暂不支援此功能
另外想问会考虑支援提交到aria2吗
因为aria2可以接脚本转存到onedrive之类
谢谢你

**Comment by liupan1890** [comment]
#### linux 版本的直链提取是不会开放吗?

不是啊，你误解了，你用带UI的linux啊，比如Ubuntu。跟windows，mac，完全一样，全部功能。你给VPS装上UI就行了（就是执行一条命令，具体我忘了，但基本上大部分版本的linux，比如centos什么的，原来没有UI的话 一条命令就可以装好ui环境了）

#### 只有远程管理时不支持 直连提取（包括在线预览图片音视频）

win,linux,mac上安装的小白羊，都不支持远程模式下直连提取，
原因上面提到了，现在6盘现在限制不能换IP

详细解释一下，

假设  你在vps上安装了小白羊，在win上管理---远程模式对吧

你在win上点击下载链接，这个时候，小白羊会生成一条下载链接复制到你的剪切板里了
（！！注意小白羊是安装在linux上，所以生成链接操作也是在linux上生成的）

然后这条下载链接，你在win上根本不能下载---6盘限制不能换IP，
你的linux的IP可能是202.12.17.1  你win的IP可能是192,168.1.11，哪个IP创建的链接，只能哪个IP下载

*** 你可以把这条链接提交给linux上的aria2去下载，是的，我明白，也是你的目的。***

但是从程序设计上来讲，我就要一遍一遍的告诉每一位用户：注意，这条链接win不能用，你要用linux去执行下载。因为你是远程模式

同理，视频预览，也是先生成下载链接，然后给播放器，让他去联网播放。远程模式下生成的下载链接，只有linux才能播放，你给win上的播放器没用

例外，你的linux和win在一个路由下，外网IP是一样的，那就不受6盘限制了，可以远程获得链接，linux或win都可以下载，因为外网IP没变。但是小白羊无法检测出你远程管理时，是否属于同一个外网IP，所以例外情况被忽略了

可能有点绕，linux和win也不是重点，重点只有一个，为了避免远程模式下用户遇到复制了下载链接却不能下载，然后找我反馈BUG。我直接关闭远程模式下的创建链接功能了


#### 另外想问会考虑支援提交到aria2吗 因为aria2可以接脚本转存到onedrive之类

在下一个版本（或者下下个）我会直接支持下载完成调用脚本功能，回调会完全参照aria的回调(GID,FileNum,FilePath)


不会开发调用aria下载的功能，因为6盘的限制问题。

**Comment by 67538201xyz** [comment]
作者你好,我现在的情况是在vps的debian上用6panlinux64,但有部份档案下载中途会出现unexpected EOF
但改用vps上的aria2没有出现下载失败
所以想询问直链提取

另外功能上想建议

离线下载能批量提交连结(100条连结)

下载到本机这功能另加选项
1.下载完成将源档案移到另一个目的地
2.下载完成将源档案删除

(单/全)任务完成支援以电邮发信提示

抱歉又劳烦你了

**Comment by yi0332** [comment]
作者你好,我现在的情况是在vps的debian上用6panlinux64,但有部份档案下载中途会出现unexpected EOF
但改用vps上的aria2没有出现下载失败
所以想询问直链提取

另外功能上想建议

离线下载能批量提交连结(100条连结)

下载到本机这功能另加选项
1.下载完成将源档案移到另一个目的地
2.下载完成将源档案删除

(单/全)任务完成支援以电邮发信提示

抱歉又劳烦你了

**Comment by liupan1890** [comment]
嗯，就是这样，把你的需求说明白，我能更针对性的帮到你

#### 有部份档案下载中途会出现unexpected EOF

这个问题我也发现了，调试了很久，发现是网络问题（莫名的网络错误---非预期的结尾，就是tcp包接受失败---可能是网络丢包，也可能是远程服务器发送错误，比如故意断开限速），aria2并不是没有发生过此错误，而是它出错后主动重新下载了。

但是长期测试我确实发现go更容易发生unexpected EOF，aria就很少。所以我最后也弄不清问题在哪，这个BUG以后再说吧

我也发现因为6盘的限制，导致很多任务都挺容易出错

下个版本我已经添加了全部任务完成后，自动重试出错的任务。
就是全部能下载的都下完了，没事干了，就会自动的把之前出错的任务重新下载一遍（总共是5遍），只有用户手动暂停的任务不会自动重试，总之基本上有什么错误也都自动解决了，你睡一觉起来，之前的任务基本都已经下载完了

#### 直链提取

我已经调整了下个版本的远程模式下的直连功能，可以提取了，复制后会弹一个提示6盘限制链接可能无法使用这种，忽略提示就好


#### 离线下载能批量提交连结(100条连结)

下个版本已经支持批量提交离线链接了，至于多少条是随意的


#### 下载完成将源档案移到另一个目的地

这个功能不会有，没有意义，你在设置里勾选，每次下载都要求我选择下载位置，不就好了，直接填写目的地，而不是下载完再复制到目的地。这个功能逻辑我之前回复过，复制文件的时间不可控，所以不会做

#### 下载完成将源档案删除

这个功能不会有，我理解的是“”原档案“”是指6盘里的文件，你从6盘下载一个文件然后自动把6盘里的文件删除掉？这个是个危险操作，需要用户手动删除文件，自动操作删除文件--不管是6盘里的文件还是你本机的文件，都是危险的
---你明确的知道你要删除这个文件，但是其他的用户可能会误操作，然后就会回来骂我了


#### (单/全)任务完成支援以电邮发信提示
这个功能不会有，发邮件的前提是我要设置一个邮箱，并且这个邮箱不会因为频繁发邮件而被屏蔽
或者你自己设置好一个邮箱，然后发邮件，这个功能问题非常多---邮箱账号的安全问题，邮箱的线路问题，邮箱的pope设置问题等等等等，总之这个功能太麻烦，不会有

**Comment by yi0332** [comment]
下载完把源档案移动的目的是
我提交100个离线任务
可能当中有20个任务完成了
我直接把20个任务下载完再上传到OneDrive
回头一看发现80个离线任务有50个已完成
那就变成了在6pan里有20个已下载的档案和50未下载的档案混在同一个资料夹
我需要自己逐一对档案进行确认去把20个已下载的档案删除/移出那个资料夹
才能进行下载的动作

另外报告出现unexpected EOF情况的档案
我把linux 资料夹内的档案rm了重新下载还是一样出现EOF,大约尝试了4次

有劳你了

**Comment by liupan1890** [comment]
#### 下载完把源档案移动的目的是
我其实一直看成下载完把档案移动了，原来是想移动6盘里的文件
还是不行，我尽量避免自动操作用户网盘内的文件这种功能，怕有用户误操作丢失文件

#### unexpected EOF
我还在跟踪，因为之前这个问题调试了很久（首先他不是必出的，很偶然，其次他不是简单地程序逻辑错误，还没搞明白），我的时间也很紧张，就先放放，以后再说了。先完善其他容易做的功能

#### 像aria2支援下载完成执行特定动作
新版已支持，去下载试试看

**Comment by xibaibai9527** [comment]
@liupan1890  403之后的等待时间是几秒啊？昨晚上下载美剧，一季24集只下载了6集，今天起床后重新下载，依旧是全部403，等待了不止8个小时了
还有，就算没有下载成功，依旧提前创建好了文件，占据了全部的硬盘空间，这一点希望可以改一下

**Comment by yi0332** [comment]
> #### 下载完把源档案移动的目的是
> 我其实一直看成下载完把档案移动了，原来是想移动6盘里的文件
> 还是不行，我尽量避免自动操作用户网盘内的文件这种功能，怕有用户误操作丢失文件
> 
> #### unexpected EOF
> 我还在跟踪，因为之前这个问题调试了很久（首先他不是必出的，很偶然，其次他不是简单地程序逻辑错误，还没搞明白），我的时间也很紧张，就先放放，以后再说了。先完善其他容易做的功能
> 
> #### 像aria2支援下载完成执行特定动作
> 新版已支持，去下载试试看


能考虑以archive list去实现跳过下载重覆档案吗？
当档案下载完成时，把它的md5值加到archive list
只要下载任务时会跳过和archive list相同md5值的档案就好了
最好就是把archive list这功能放到预设不启用
防止小白误用

有劳作者你了

**Comment by yi0332** [comment]
> #### 下载完把源档案移动的目的是
> 
> 我其实一直看成下载完把档案移动了，原来是想移动6盘里的文件
> 
> 还是不行，我尽量避免自动操作用户网盘内的文件这种功能，怕有用户误操作丢失文件
> 
> 
> 
> #### unexpected EOF
> 
> 我还在跟踪，因为之前这个问题调试了很久（首先他不是必出的，很偶然，其次他不是简单地程序逻辑错误，还没搞明白），我的时间也很紧张，就先放放，以后再说了。先完善其他容易做的功能
> 
> 
> 
> #### 像aria2支援下载完成执行特定动作
> 
> 新版已支持，去下载试试看

脚本功能好了

**Comment by liupan1890** [comment]
> @liupan1890 403之后的等待时间是几秒啊？昨晚上下载美剧，一季24集只下载了6集，今天起床后重新下载，依旧是全部403，等待了不止8个小时了
> 还有，就算没有下载成功，依旧提前创建好了文件，占据了全部的硬盘空间，这一点希望可以改一下

有问题最好是发新的issue，因为有时候回复我看不到

### 403的问题我不知道时间是多久

这个是6盘的设置，6盘也没公开---这种设置估计经常调整也不会公开
估计跟免费、vip有关，另外也跟文件有关，一般遇到403，你这样操作试试，
1. 停止全部任务
2. 断网换IP
3. 重新下载
如果还不行，
4. 删除掉所有任务
5.重新到网盘里点击下载，就是重新创建任务

推荐2-3文件，5线程下载，我昨晚测试，3文件5线程一晚上（5个小时）下载了900个文件，共480GB，没有遇到限速，全部下载下来了，6盘还是很良心的


### 没有下载成功，依旧提前创建好了文件

这是故意这样设计的，因此还会导致任务刚开始时下载速度很慢，等几十秒-1分钟才能提速的问题。
但就是故意要这样设计的

**Comment by liupan1890** [comment]
#### 能考虑以archive list去实现跳过下载重覆档案吗？
不会有这个功能，这个功能一般人都用不到，下载文件时，如果这个文件已经下载过（本地硬盘上有这个文件），下载开始后会自动跳过（直接显示下载完成）的，不会真的重新下载

另外，比如我下载了，我删除了，我要重新下载。这个功能就冲突了，总之一般情况用不到，没有增加的意义

做软件就是这样，保证基础的功能好用就行了，一些特殊的需求耗时不说还可能会互相影响到其他功能，并且以后升级、维护的时候也是问题，所以一些小众的功能并不会添加，请谅解

**Comment by yi0332** [comment]
作者抱歉又劳烦你了
EOF问题下载失败的档案超过4小时后可以在小白羊内重新下载吗？
因为显示连接被拒绝

**Comment by liupan1890** [comment]
呃，，，其实我也不知道啊

我平时下载很少会遇到403的情况，因为开发小白羊，我基本上每天都会下载100GB以上的文件，有几天更是每天下载400-500GB的文件--------每天都是找不同的高清3D视频、或者大型单机游戏安装包、或者XXX视频教程，不是重复下载相同的文件

我感觉我这就是大流量了，但我很少遇到403，因为遇不到，所以也测试、研究不了

403是6盘官方的问题，还是以官方答案为准   https://0e0e083932c23d0f.kf5.com/hc/kb/article/1427139/
