### ISSUE TITLE
搜索链接

### ISSUE THREAD

**Issue by realVegetable** [liupan1890/xiaobaiyang2#2]
尊敬的开发者：

您好！

非常感谢您开发了 6盘小白羊 UI！

我有两个请求，不知您可否满足我。

一个是，我最喜欢的是 6盘小白羊 上的搜索功能，这是继pandownload之后我用到最舒服的度盘资源搜索器了。
不知道您可否告诉我这个搜索平台的网址？（我自己在网络上搜索 猪猪盘 ，目前无法打开）
又或者能否在搜索的结果中能够提取度盘链接。

第二个是，能否在下载功能上进行分类，一个是使用您的账号，一个是使用自己个人的账号。（毕竟有时候您的账号会离线次数不够）

很抱歉冒然提出这两个请求，见谅。

祝好，

一个 6盘小白羊 的用户

**Comment by liupan1890** [comment]
抱歉这两天内看github，，我平时也不怎么看。。。。


1 猪猪盘的地址
猪猪盘实际上很早就挂掉了，后来我又换过几次（程序发布了，就改不了名字了，只有更新版本时才能改，但版本一致没更新），不过类似的网站总挂，太不稳定了

2 因为某些原因，我已经被迫关闭掉了内置的账号，现在使用小白羊是无法使用内置账号的，又因为我写死了百度链接调用内置账号，所以下载的小白羊是无法离线百度连接的，只能离线磁力、电驴等。（你可以在6盘官网提交百度链接，然后用小白羊下载）

3 因为某些原因，小白羊第二版（还没发布），已经彻底屏蔽了搜索功能，你可以自己搜索链接提交，但不能使用小白羊搜索了
