### ISSUE TITLE
VIP账号的在线播放

### ISSUE THREAD

**Issue by wsx0963** [liupan1890/xiaobaiyang2#20]
因为VIP账号在线播放用的视频源画质较差，能否新增选项和之前一样调用的是下载的链接呢

**Comment by liupan1890** [comment]
好，下个版本会增加选项

**Comment by liupan1890** [comment]
不过为什么说VIP账号在线播放用的视频源画质较差呢？
我测试了一下，一个高清的视频，6盘的转码后分辨率是1920*1080啊，，画质较差？？
6盘的转码是根据原视频来的，原视频清晰，转码就清晰啊，这两个的差异肉眼应该看不出才对

**Comment by wsx0963** [comment]
> 
> 
> 不过为什么说VIP账号在线播放用的视频源画质较差呢？
> 我测试了一下，一个高清的视频，6盘的转码后分辨率是1920*1080啊，，画质较差？？
> 6盘的转码是根据原视频来的，原视频清晰，转码就清晰啊，这两个的差异肉眼应该看不出才对

因为我这里看的时候一个分辨率是1280*720（直接点击播放调用播放器），一个是1920*1080（下载链接）
![圖片](https://user-images.githubusercontent.com/42093236/98461834-72fa4400-21ea-11eb-9447-8dfcb6e227e2.png)

**Comment by liupan1890** [comment]
嗯，可能我的视频比较大（6GB），我看的是1920*1080

估计晚上10点左右会更新版本，设置里就有这个选项了
