### ISSUE TITLE
请求加入百度云盘资源搜索功能

### ISSUE THREAD

**Issue by Zhao-Peng-Hui** [liupan1890/xiaobaiyang2#21]
开发者您好：
        我是一个忠诚得小白羊用户，希望开发者加入那个百度云资源搜索得功能，显示一下搜索出来的连接地址和提取码。希望开发者加入此功能，谢谢。

**Comment by liupan1890** [comment]
因环境问题，不会提供百度云资源搜索类功能

**Comment by hsiayuchih** [comment]
> 因环境问题，不会提供百度云资源搜索类功能

请问那个VLC是什么版本？
