### ISSUE TITLE
关于小白羊 listen 2020 port 失败的分析

### ISSUE THREAD

**Issue by bookyue** [liupan1890/xiaobaiyang2#23]
debug.log: 

`Server.go:47: Start ServerError:  listen tcp :2020: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

这其实并不是小白羊本身的问题，是 win 没有更新 dynamic port range
默认为：
```
PS C:\> netsh int ipv[46] show dynamicport tcp

协议 tcp 动态端口范围
---------------------------------
启动端口        : 1024
端口数          : 64512
```

这就造成了小白羊有时 bind 2020 port 失败，有时成功的原因。这也是为什么重启后大概率成功的原因（因为2020 port 还未分配出去）。

将 dynamic port range 改为 49152 至 65535，则可以解决此类问题。
```
PS C:\> netsh int ipv[46] set dynamic tcp start=49152 num=16384

PS C:\> netsh int ipv[46] show dynamicport tcp

协议 tcp 动态端口范围
---------------------------------
启动端口        : 49152
端口数          : 16384
```

亦或者作者考虑换一个更大更不常用的port？

参考链接：
https://github.com/docker/for-win/issues/3171#issuecomment-554587817
[The default dynamic port range for TCP/IP has changed since Windows Vista and in Windows Server 2008](https://support.microsoft.com/en-ca/help/929851/the-default-dynamic-port-range-for-tcp-ip-has-changed-in-windows-vista)

**Comment by liupan1890** [comment]
呃，我对端口没啥了解，所以看到你的问题我去百度了一下。。。。。

我理解的是，当程序需要访问网络时，需要绑定端口

#### 绑定端口的操作分为2种，
1. 第一种是绑定到*，就是动态端口，此时程序跟系统说：给我个随机端口，系统会按照设置，在动态端口范围内随机分配一个

win7
C:\Users\vmpc>netsh int ipv4 show dynamicport tcp

协议 tcp 动态端口范围
---------------------------------
启动端口        : 1025
端口数          : 13976

就是说1025-15001 范围内随机分配

win10
C:\Users\vmpc>netsh int ipv4 show dynamicport tcp
协议 tcp 动态端口范围
---------------------------------
启动端口        : 49152
端口数          : 16384

就是说49152-65536 范围内随机分配

2. 第二种是指定端口，程序跟系统说：给我:2020，系统会直接绑定到2020（如果被占用，自然就出错了）

第一种好处是99.9%肯定可以获得一个端口，缺点是端口号随机  
第二种好处是端口号固定，缺点是容易出错（被占用）  

#### 亦或者作者考虑换一个更大更不常用的port？

所以，仅从我理解的角度看，我想要用固定的端口，使用大端口反而是不对的，比如使用49152，很容易被别的程序占用，应该使用1025以内的，比如123，这样不管是win7还是win10,只要没有其他程序也指定了使用123，那就是安全的，但是实际上，1025以内的大部分端口都有很多软件指定了，比如21,80,443,3389

我是感觉2020已经是不常用的端口了。整个1999？有啥建议不？

**Comment by liupan1890** [comment]
嗯，如果我下个版本更新一下，改成动态端口，但是远程管理时就不知道输入哪个端口了，而且吧，第一次运行的时候一般会弹出防火墙的警告---因为要绑定端口使外网可以访问，如果使用动态端口，是不是每一次启动（换端口时）都会有防火墙的警告呢？我去测试一下

**Comment by bookyue** [comment]
事实上，请不要使用小端口号（1023以内的）因为那是 `well-known ports`，被各种系统服务所占用。

49152~65535也是不推荐的，因为这一般被用作临时端口（[Ephemeral ports](https://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html)）

从实践上来说，动态端口号也大可不必，使用`1024~49151`之间的，**不常用的**（不是各种有名的软件所占用的 例如：3000），即可以解决问题（99.9%不会碰到占用问题）。
比如你提出的1999(9)或者7888之类的都是可以的。

PS: 参考其它实践，我个人觉得比较好的解决方法是，将端口号写在配置文件里，如有冲突，这样用户可以自己选择合适的，不与自己其它本地服务冲突的端口号。

> **Well-known ports**: 0 to 1023 (used for system services e.g. HTTP, FTP, SSH, DHCP ...)
**Registered/user ports**: 1024 to 49151 (you can use it for your server, but be careful some famous applications: like Microsoft SQL Server database management system (MSSQL) server or Apache Derby Network Server are already taking from this range i.e. it is not recommended to assign the port of MSSQL to your server otherwise if MSSQL is running then your server most probably will not run because of port conflict )
**Dynamic/private ports**: 49152 to 65535. (not used for the servers rather the clients e.g. in NATing service)

参考链接：
[List of TCP and UDP port numbers](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)
[The Ephemeral Port Range](https://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html)

**Comment by liupan1890** [comment]
嗯，首先2020本身也不是常用端口，然后我在下个版本，我会修改为2020+2021，总不可能这2个端口都会被占用吧，几率太小了

先用2020，绑定失败就切换2021，再失败就不管了，这样
