### ISSUE TITLE
开发者能提供一下目前调用的百度网盘资源搜索的api 或者 网站么

### ISSUE THREAD

**Issue by Zhao-Peng-Hui** [liupan1890/xiaobaiyang2#24]
开发者能提供一下目前调用的百度网盘资源搜索的api 或者 网站么  谢谢

**Comment by liupan1890** [comment]
这个接口已经失效了啊

**Comment by Zhao-Peng-Hui** [comment]
目前不是还可以搜索的吗？
![image](https://user-images.githubusercontent.com/71930169/98623513-d1d4d000-2346-11eb-80d7-55285ec8ac54.png)

**Comment by liupan1890** [comment]
是这样，在最开始的时候，我找的猪猪盘，但大概一个月吧，猪猪盘就不能用了，我就换了一个，后来又不行了，我又换了一个

在第三次的时候我就直到这个太不稳定了（稳定的都是收费的），另外搜索时网络有时候也很不稳定，我就在换第三个的时候，配置了本地缓存，第三个也早就挂了，你现在能搜到的都是我本地缓存的数据。。。。

**Comment by liupan1890** [comment]
现在第一版因为某些原因，我已经被迫关闭了内置账号不能使用了，第二版也同样因为某些原因，已经不再提供搜索功能了。所以没有第四个了。。。第一版也不再维护了，没让我整个删掉已经是对我的宽容了

**Comment by Zhao-Peng-Hui** [comment]
好的 谢谢开发者
