### ISSUE TITLE
请问一直403是6盘免费用户的限制吗？

### ISSUE THREAD

**Issue by xibaibai9527** [liupan1890/xiaobaiyang2#25]
从前天开始我发现下载很多东西都开始403了，最开始是美剧200集从头到尾全部403，等了两天也没恢复，切换IP，重启光猫路由都试过了没用，再到小电影也开始了，全部403
删了重新离线，也没用

我想是不是因为我下了好几百G的美剧，带宽太贵，6盘直接把我这一片的ip都给禁用了？我用的是移动网络

这种情况下，开会员能拯救吗？

6盘连个论坛都没有，不知道在哪里交流，斑竹勿怪

**Comment by jzysl123** [comment]
cold3服务器坏了  白嫖用户离线的老文件都是转到这个服务器 所以403
开会员就会转到cold2服务器  可以正常下载

**Comment by xibaibai9527** [comment]
原来是这样，经过ls的提醒，我观察了一下的确403的都是cold3服务器
官网发公告说损坏服务器已经修好了，看来并没有
以前我判断能否下载，就是直接用ALC在线预览一下，但似乎现在全都不能预览了，只能复制一下地址然后手动输入地址栏，才能看到是否真的403。

**Comment by liupan1890** [comment]
近期6盘应该是针对vlc做了屏蔽了，我试了一下，用Potplayer是可以在线预览的---应该是6盘还没屏蔽Potplayer的UserAgent

最后吧，我发现mpv player是支持直接修改UserAgent的，vlc想要修改UserAgent的话需要自己编译，太麻烦了，等我测试好mpv会全部替换成mpv就好了

**Comment by liupan1890** [comment]
403的问题啊，我真的不了解。。。。。。。
