### ISSUE TITLE
资源站投稿

### ISSUE THREAD

**Issue by anye1998** [liupan1890/xiaobaiyang2#26]
https://www.pianku.tv/
片库 影视磁力

**Comment by liupan1890** [comment]
收到！！

**Comment by jzysl123** [comment]
国外的影视采集https://rarbgprx.org/torrents.php就行了   不知道能不能根据imdb号到豆瓣搜索
采集的时候附上中文名称
小姐姐 https://sukebei.nyaa.si
国内影视没好的站点 都是些小圈子  要么付费 要么pt  6盘都不好下载

**Comment by liupan1890** [comment]
收到，去研究，这两天都没干活。。。。。懒病烦反复发作，怎么治？？？

**Comment by anye1998** [comment]
> 收到，去研究，这两天都没干活。。。。。懒病烦反复发作，怎么治？？？

这个不是商业项目，开源项目而已，大家一起完善，不必追求进度，没必要当成一个任务，当然能快一点更好😂

**Comment by lmr1194399818-github** [comment]
http://pianyuan.la/

**Comment by RheumGitHub** [comment]
> https://www.pianku.tv/
> 片库 影视磁力

更新：最新网址https://www.pianku.la/
