### ISSUE TITLE
资源站

### ISSUE THREAD

**Issue by helianchichi** [liupan1890/xiaobaiyang2#28]
目前IT知识最专一集中的瑞客论坛应该算一个，ruike1.com

**Comment by helianchichi** [comment]
如果也能转存到我的六盘里的话我愿意提供瑞客论坛账号

**Comment by liupan1890** [comment]
收到，因为RSS刚做，所以开始时间会比较长，预计RSS功能大概一周后会上线吧，之后增加网站速度就快了，

我RSS的思路是
1. 找一些资源丰富的网站
2. 我注册账号开通VIP（针对那种包年xx元随便看的）
3. 批量采集下来资源，并以后随着更新
4. 之后大家可以免费在小白羊里下载了
5. 6盘对离线过的链接，别人再次离线都是用的缓存，就是很快就离线成功了，这样只要有人离线过同一个资源，其他人都是基本等于秒传了


所以，RSS网站

1. 免费的，更新快的，原创的  上的多
2. 收费的可能要我多考虑考虑价钱、资源是否合适 上的少
3. 有很多人其实有各种网站的账号，如果支援的人多，那很多收费网站都可以加进来


最后感谢提交，我先看看去
