### ISSUE TITLE
开发者大大，能否加入批量选择文件的功能？

### ISSUE THREAD

**Issue by hsiayuchih** [liupan1890/xiaobaiyang2#29]
在进行文件或文件夹的复制移动时，只能复制完一个再复制另一个，如果文件数量过多的话就比较费时间。想问下作者能否考虑加个批量选择的功能呢？就是比如可以使用鼠标进行拖拉选择，亦或是ctrl+鼠标点击文件，再或者是shift+鼠标的快捷键。谢谢！

**Comment by liupan1890** [comment]
我明白你的意思了，我一直没有增加批量移动、批量删除功能，是因为6盘的逻辑问题

1. 6盘逻辑问题
6盘现在操作移动，复制到。。。和删除到回收站时，假如你要删除的是一个巨大的文件夹，先会卡主10多秒，然后返回结果提示异步操作，此时源文件还显示在原来的位置并没有移动，几秒或几分钟之后，刷新才能看到文件已经被移动、删除了

总之就是，6盘的逻辑问题，导致移动、复制、删除、重命名这几个操作，时间不可控，批量操作时跟用户的预期不一致（你点了移动了，提示成功了，但看不到结果，等xxx时间以后才能看到结果），我没想好怎么处理这个时间的同步问题

2. UI布局问题
我没想好把 “”批量移动“” “”批量复制“”  “”批量删除“” 放到哪了，因为界面上已经没有空白的地方了


所以现在是没有的，我之后想一下，怎么安排，以后会加上这个功能的

**Comment by hsiayuchih** [comment]
了解了，开发者大大辛苦了！

**Comment by liupan1890** [comment]
新版已发布，实现了批量功能
