### ISSUE TITLE
aria2c远程下载

### ISSUE THREAD

**Issue by wnbh** [liupan1890/xiaobaiyang2#3]
第一版本中的调用aria2c远程下载还会有吗？
如果有，远程下载能否支持自行决定并行任务数，若考虑到程序稳定，可以设定一个最大值，自行决定的并行任务数不得大于这个值。

**Comment by liupan1890** [comment]
1 aria2c远程下载

第二版刚刚开发，aria2c远程下载不是重点，所以第一次发布时肯定不会有了，之后看我时间吧。等第二版开发完平稳了，我会加上aria2c远程下载

2 自行决定并行任务数
第二版可以的，以后加上aria2时也可以的

**Comment by wnbh** [comment]
好的

**Comment by liupan1890** [comment]
最新的进度，
在整理aria，发现了点问题，说一下，不打算做aria了

Q1. 6盘现在限制，创建下载链接的IP和下载的IP必须一致，否则403
Q2. 6盘一直限制，如果使用第三方工具，控制线程在5个线程以下，同时下载的文件不要超过3个


关于Q1，就是说在你的电脑复制下载地址，把地址给VPS上的aria去下载是不行的会403，
同理，在你的电脑复制下载地址，重启你的光猫（你的外网IP会更新），在你的电脑下载也是不行的会403.
总之IP不能变

关于Q2，就是说aria的多文件同时下载，或者单文件开多线程并发下载，都没用。最多3*5。
实际测试发现，
1. 一分钟内生成3个下载链接后，再生成下载链接就会返回文件系统忙的错误。
2. 一个文件开很多线程下载，达到一定时间或流量后会被限速


总之，按照6盘官方限制去下载，满速，无限制。反之VIP也会短时间限速之类。

所以aria的作用就没有体现出来。我也不打算开发远程调用aria功能了，你可以直接点击复制下载链接的按钮，复制下载链接，然后手动提交给本机的aria去下载，因为是你自己提交，所以可以随意的设置并发数等。




![无标题](https://user-images.githubusercontent.com/67817756/97526596-715b9f80-19e4-11eb-8bfc-33ebf37e145e.png)

**Comment by wnbh** [comment]
行吧

**Comment by jzysl123** [comment]
线程高没用的  用第一版就行了
