### ISSUE TITLE
关于自动重试下载的次数和时间间隔能允许自定吗？

### ISSUE THREAD

**Issue by yi0332** [liupan1890/xiaobaiyang2#30]
主要是403/502/EOF出现得太多了
想让他相隔1分钟重试

谢谢

**Comment by liupan1890** [comment]
当403/502/EOF出现得太多了时，你应该考虑修改为2文件同时下载，每个文件5个线程，我经常使用和测试，很少遇到403,502这些问题，这些问题都是并发数太高导致的6盘限制，并不是程序功能原因

比如当出现403时，你隔一分钟重试这个操作本身并没有作用，是反作用的，

首先6盘限制你了，时会根据IP，文件，UserID去限制，同时6盘有好几个线路（二级域名），每个文件可能存储在其中一个线路里，这些线路是单独计算403限制的，所以有时候你下载这个文件没事，下载另外一个文件就403.

然后403是会持续较长时间的，（最起码几分钟），在这几分钟内，都是403，此时你隔一分钟重试，并没有用，反而会增加6盘的访问计数，增加限制

EOF我测试出来一般是出现在6盘的cdn回源拉取较慢，跟不上你下载速度的时候


总之并不是线程多就好的，反而会403和限速

**Comment by liupan1890** [comment]
基于403后这个文件要等很长时间之后才能重试这个限制，我才做成先下载其他的文件，等全部文件都下载完（已经过了几分钟了），再重试出错的文件这样，重试并没有时间间隔，纯粹是看有没有其他文件，重试次数是5次，当连续下载5次都无法成功下载，说明需要等较长时间以后（几个小时以后），再重新下载才对，一直重试并没有用的，而几个小时以后，你肯定会来看一眼，会手动点击重新开始的，所以也不需要等待几个小时后自动重试功能

**Comment by yi0332** [comment]
好的明白了
我会把任务数改成2看什么情况
谢谢

**Comment by liupan1890** [comment]
我这边平时下载，一般开到5线程下载速度就可以达到25-28MB/s,因为我的网速就这么快了，如果是多个文件同时下载，就有有的10MB/s,有的500kb/s，有的2-3MB/s这样，总速度也差不多是满速的，网络时有波动，计算速度本身也有时差，所以显示的只是粗略的速度，

不知道你那里下载速度怎么样？是因为速度慢所以调高了线程数吗？

另外注意一点，因为需要预分配因硬盘空间，所以任务刚启动时会出现，第一秒3-6MB/s，之后速度突然变慢1-200kb/s,大约几十秒之后慢慢恢复到满速这样的表现，是在等待硬盘，并不是没有速度，根据文件的大小，等1-2分钟吧速度就比较稳定了

**Comment by yi0332** [comment]
> 我这边平时下载，一般开到5线程下载速度就可以达到25-28MB/s,因为我的网速就这么快了，如果是多个文件同时下载，就有有的10MB/s,有的500kb/s，有的2-3MB/s这样，总速度也差不多是满速的，网络时有波动，计算速度本身也有时差，所以显示的只是粗略的速度，
> 
> 不知道你那里下载速度怎么样？是因为速度慢所以调高了线程数吗？
> 
> 另外注意一点，因为需要预分配因硬盘空间，所以任务刚启动时会出现，第一秒3-6MB/s，之后速度突然变慢1-200kb/s,大约几十秒之后慢慢恢复到满速这样的表现，是在等待硬盘，并不是没有速度，根据文件的大小，等1-2分钟吧速度就比较稳定了

3任務有60-75MB/s
但是現在6pan好像加了限制
下載100任務會有部份出現EOF
即使相隔24小時還是繼續EOF

另想請問webui能相容手機版的瀏覽器？
因為手機版用webui必須以電腦網站打開才能左右拉動
還有就是左側選單能像ariang收縮嗎
正在下載中能顯示檔案在6pan上的路徑和到達的目的地嗎
方便按順序分類去管理3任务有60-75MB/s
但是现在6pan好像加了限制
下载100任务会有部份出现EOF
即使相隔24小时还是继续EOF

另想请问webui能相容手机版的浏览器？
因为手机版用webui必须以电脑网站打开才能左右拉动
还有就是左侧选单能像ariang收缩吗
正在下载中能显示档案在6pan上的路径和到达的目的地吗
方便按顺序分类去管理

谢谢

**Comment by yi0332** [comment]
还有想问关于离线下载
小白羊有没有指令能提交离线任务？
我想自己写个shell脚本
定时执行提交100种子去离线任务
谢谢

**Comment by liupan1890** [comment]
#### webui能相容手机版的浏览器？
这个还真的不好实现，  
手机屏幕是竖的，就是窄，那么开发UI时逻辑是从上到下，  
电脑屏幕是横的，就是宽，开发逻辑是从左到右，
举个例子，针对手机开发，那我会把文件名弄成2行，因为一般的文件名一行都显示不了，并且那些操作按钮（下载，复制链接，在线预览等等），都会另起一行，像这样
``````
梦幻天堂·龙网(LWgod.cc).1080p.异形：契约
.异形：圣约.普罗米修斯2.mkv

----------------下载--复制---删除--预览
``````
我从来没考虑过手机使用，在UI的排版上也没考虑过会兼容手机，因为“”远程管理的“”人不多，只要考虑兼容手机，那排版布局会有非常多的限制。所以一开始就没关手机，以后也不会开发手机的版本，想要一套UI适配多个设备，针对网盘这种文件、操作比较多的项目不合适。应该开发2套独立的软件，一个是电脑版，一个是手机版才对。我不会开发手机版



#### 左侧选单能像ariang收缩吗
针对电脑版，收缩的目的、作用是什么？



#### 正在下载中能显示档案在6pan上的路径和到达的目的地吗
1. 当你把鼠标移动上去，会显示完整的保存路径
2. 完整的保存路径就是 下载文件夹+6盘完整路径
所以只要你把鼠标移动到文件名上面，就能看到 “”档案在6pan上的路径“”  和 “”本地硬盘路径“”


#### 小白羊有没有指令能提交离线任务？
这个功能没有，
1. 离线任务并不是必然成功提交
比如你提交了一个百度分享链接，可能提交时链接已失效，会返回错误。你以为你提交了100条，实际上不知道
2. 小白羊的后台服务并不支持命令行形式，只支持URL访问的形式
3. 你可以直接通过自动访问URL的形式实现自动提交任务。小白羊UI是开源的，去看一下UI调用后台服务提交离线的URL和参数，就可以自己定时自动模拟提交了----（比如用任何语言编写一个定时自动访问URL和参数的小程序）

**Comment by liupan1890** [comment]
shell我不知道是否可以直接访问URL，我总感觉你直接复制100条然后粘贴提交，只需要点5-8下，耗时20秒。就成功了。没有必要专门整一个定时自动提交100的程序，

你要留意到，比如你今天已经提交了100条，可用离线次数=0。6盘并不是每天晚上12:00就清零，恢复成100条的，不是的，是在不知道几点---比如凌晨2点？突然就清零恢复100条。在此之前（12:00-2:00），你不能提交离线任务（可用离线次数=0）

**Comment by yi0332** [comment]
> #### webui能相容手机版的浏览器？
> 这个还真的不好实现，  
> 手机屏幕是竖的，就是窄，那么开发UI时逻辑是从上到下，  
> 电脑屏幕是横的，就是宽，开发逻辑是从左到右，
> 举个例子，针对手机开发，那我会把文件名弄成2行，因为一般的文件名一行都显示不了，并且那些操作按钮（下载，复制链接，在线预览等等），都会另起一行，像这样
> ``````
> 梦幻天堂·龙网(LWgod.cc).1080p.异形：契约
> .异形：圣约.普罗米修斯2.mkv
> 
> ----------------下载--复制---删除--预览
> ``````
> 我从来没考虑过手机使用，在UI的排版上也没考虑过会兼容手机，因为“”远程管理的“”人不多，只要考虑兼容手机，那排版布局会有非常多的限制。所以一开始就没关手机，以后也不会开发手机的版本，想要一套UI适配多个设备，针对网盘这种文件、操作比较多的项目不合适。应该开发2套独立的软件，一个是电脑版，一个是手机版才对。我不会开发手机版
> 
> 
> 
> #### 左侧选单能像ariang收缩吗
> 针对电脑版，收缩的目的、作用是什么？
> 
> 
> 
> #### 正在下载中能显示档案在6pan上的路径和到达的目的地吗
> 1. 当你把鼠标移动上去，会显示完整的保存路径
> 2. 完整的保存路径就是 下载文件夹+6盘完整路径
> 所以只要你把鼠标移动到文件名上面，就能看到 “”档案在6pan上的路径“”  和 “”本地硬盘路径“”
> 
> 
> #### 小白羊有没有指令能提交离线任务？
> 这个功能没有，
> 1. 离线任务并不是必然成功提交
> 比如你提交了一个百度分享链接，可能提交时链接已失效，会返回错误。你以为你提交了100条，实际上不知道
> 2. 小白羊的后台服务并不支持命令行形式，只支持URL访问的形式
> 3. 你可以直接通过自动访问URL的形式实现自动提交任务。小白羊UI是开源的，去看一下UI调用后台服务提交离线的URL和参数，就可以自己定时自动模拟提交了----（比如用任何语言编写一个定时自动访问URL和参数的小程序）
> 

理解了
那离线任务完成后能显示已下载的档案所在路径吗
因为刚刚去了官网，看到新增了（我离线任务卡了999，所以要去官网去看

有劳作者

**Comment by yi0332** [comment]
> shell我不知道是否可以直接访问URL，我总感觉你直接复制100条然后粘贴提交，只需要点5-8下，耗时20秒。就成功了。没有必要专门整一个定时自动提交100的程序，
> 
> 你要留意到，比如你今天已经提交了100条，可用离线次数=0。6盘并不是每天晚上12:00就清零，恢复成100条的，不是的，是在不知道几点---比如凌晨2点？突然就清零恢复100条。在此之前（12:00-2:00），你不能提交离线任务（可用离线次数=0）

想大量塞离线任务还是得手动
无论如何谢谢你了看来

**Comment by liupan1890** [comment]
那离线任务完成后能显示已下载的档案所在路径吗

离线任务，你把鼠标移上去，会显示创建离线任务时选择的位置，
比如创建离线任务时你选择根目录，会显示/

我离线任务卡了999

我没预料到会有这个需求，因为我都是下完了就删了。。。我下次调成1999怎么样？

**Comment by yi0332** [comment]
> 当403/502/EOF出现得太多了时，你应该考虑修改为2文件同时下载，每个文件5个线程，我经常使用和测试，很少遇到403,502这些问题，这些问题都是并发数太高导致的6盘限制，并不是程序功能原因
> 
> 比如当出现403时，你隔一分钟重试这个操作本身并没有作用，是反作用的，
> 
> 首先6盘限制你了，时会根据IP，文件，UserID去限制，同时6盘有好几个线路（二级域名），每个文件可能存储在其中一个线路里，这些线路是单独计算403限制的，所以有时候你下载这个文件没事，下载另外一个文件就403.
> 
> 然后403是会持续较长时间的，（最起码几分钟），在这几分钟内，都是403，此时你隔一分钟重试，并没有用，反而会增加6盘的访问计数，增加限制
> 
> EOF我测试出来一般是出现在6盘的cdn回源拉取较慢，跟不上你下载速度的时候
> 
> 
> 总之并不是线程多就好的，反而会403和限速
> 
> 

抱歉还是想请问能加入相隔自动全部开始吗
我10多个档案 502/EOF都2天了
相隔24小时一样报错

谢谢

**Comment by liupan1890** [comment]
呃，没注意到你留言，
如果频繁出现502/EOF，我推荐你复制下载链接使用浏览器直接下载试试，或者使用6盘官方客户端试试

请问是特定的这几个文件频繁502，还是全部文件都这样？

我自己运行、调试的时候，遇不到502、EOF  （这几天我也没空调试，可能是我下载的文件太少），我也确实没办法针对这个问题去研究它。

另外502是明确的6盘的问题，比如6盘cdn回源失败，这个错误不是小白羊功能BUG

EOF的问题我还没想明白


#### 相隔1小時自动全部开始吗
作用不大，你说了24小时都不行

**Comment by liupan1890** [comment]
我的网速最快就是28MB/s  也可能是网速太慢，达不到触发条件

**Comment by yi0332** [comment]
> 呃，没注意到你留言，
> 
> 如果频繁出现502/EOF，我推荐你复制下载链接使用浏览器直接下载试试，或者使用6盘官方客户端试试
> 
> 
> 
> 请问是特定的这几个文件频繁502，还是全部文件都这样？
> 
> 
> 
> 我自己运行、调试的时候，遇不到502、EOF  （这几天我也没空调试，可能是我下载的文件太少），我也确实没办法针对这个问题去研究它。
> 
> 
> 
> 另外502是明确的6盘的问题，比如6盘cdn回源失败，这个错误不是小白羊功能BUG
> 
> 
> 
> EOF的问题我还没想明白
> 
> 
> 
> 
> 
> #### 相隔1小時自动全部开始吗
> 
> 作用不大，你说了24小时都不行

我下载一个资料夹的档案（150+）
然后会有10个档案出现502/EOF

特定时间重新开始就算出现502/EOF,最少有2-5秒可以有1-8MB/s
所以就是想让他这样慢慢的把档案下载

**Comment by yi0332** [comment]
> 我的网速最快就是28MB/s  也可能是网速太慢，达不到触发条件

还有想新增预计下载完成时间
谢谢你

**Comment by liupan1890** [comment]
嗯，下个版本我会增加，
1. 失败间隔1小时重试功能
2. 新增预计下载完成时间

不过我最近开始版本大改，所以下个版本上线会比较晚

**Comment by yi0332** [comment]
> 嗯，下个版本我会增加，
> 
> 1. 失败间隔1小时重试功能
> 
> 2. 新增预计下载完成时间
> 
> 
> 
> 不过我最近开始版本大改，所以下个版本上线会比较晚
> 
> 

还有能新增黑色主题吗？
白色主题晚上看太痛苦了
平板不能装插件反转颜色
谢谢你

**Comment by liupan1890** [comment]
不会增加黑色主题。

1. 现在的版本，源码开放程度在50%这样，部分源码是golang未开放
2. 下个版本会把绝大部分代码转移成js，源码开放程度提升为90%了
3. 基于现在github上的开源代码你可以自己定制黑色主题
4. 下个版本上传后，基于github上的开源代码你可以完全自由定制了
5. 最后剩余的10%源码不开源是因为这些代码是下载和上传的代码，js性能不足，必须用golang，不开源

**Comment by liupan1890** [comment]
新版已上传，
失败间隔1小时重试功能----新版是无限次重试
新增预计下载完成时间-----已增加
