### ISSUE TITLE
百度云盘

### ISSUE THREAD

**Issue by 1723080114** [liupan1890/xiaobaiyang2#32]
那个百度云盘离线下载的话，一般要多久才开始下载的？

**Comment by liupan1890** [comment]
1. 如果你的连接，别人以前已经提交过，那就本上都是秒传--300GB的文件1分钟内完成

2. 以前全新的链接基本会在1-2分钟内开始下载（你提交了100条，大概有2-3条并发去下载，别的显示等待），下载速度很快

3. 失败率很高

4. 最近几天全新链接全部失败


我不是6盘，你问我这类问题我只能瞎答，6盘的服务类问题你应该在6盘里发工单问6盘的客服
