### ISSUE TITLE
关于localhost连接不上

### ISSUE THREAD

**Issue by John21211** [liupan1890/xiaobaiyang2#33]
是哪里设置的不对吗，点开exe就是显示不能连接

**Comment by liupan1890** [comment]
最好能截个图

1. 是下载的11月13日的版本吗？
2. 试过11月8号的旧版吗？
3. 默认不需要设置，双击即可，如果显示不能连接，刷新一下呢？
4. 是什么系统呢？
5. 在AppData/debug.log 这个文件里是日志，可能有错误信息，有的话贴上来我看看

**Comment by John21211** [comment]
刚才试了一下旧版没有问题
2020/11/07 10:36:24 DBHelper.go:28: Start Path C:\Users\YZ\Downloads\Compressed\6盘小白羊版win64VLC\AppData

2020/11/07 10:36:24 Server.go:33: Start Server :2020

2020/11/07 10:40:31 Server.go:59: Shutting down server:  interrupt

**Comment by liupan1890** [comment]
那你先用旧版，新版可能是有BUG，我再调试看看

**Comment by liupan1890** [comment]
你贴的日志是旧版的日志啊

6盘小白羊版win64VLC---旧版

6盘小白羊版win64MPV--新版

你帮我贴一下新版的日志，我才能看到是什么错误
