### ISSUE TITLE
老哥，如何获取6盘cookie？

### ISSUE THREAD

**Issue by llj1998** [liupan1890/xiaobaiyang2#34]
老哥，如何获取6盘cookie？

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/99770847-14ff2200-2b43-11eb-85b3-d9e6e39bbfec.png)

**Comment by HappyLittlePill** [comment]
请问这个下载文件和操作教程是在哪里呢？文叔叔吗？其他地方找到的文叔叔链接都挂了，求补~

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/99896361-f3c93d80-2cca-11eb-9e38-ff8ccaa1b803.png)
