### ISSUE TITLE
能别依赖浏览器，做个独立客户端吗

### ISSUE THREAD

**Issue by liveskai** [liupan1890/xiaobaiyang2#36]
# 能别依赖浏览器，做个独立客户端吗

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/100224002-2dae7400-2f57-11eb-85cd-2ac097846441.png)

**Comment by Qixingchen** [comment]
后续还会考虑提供无 electron 的版本么
