### ISSUE TITLE
什么时候更新呢

### ISSUE THREAD

**Issue by liveskai** [liupan1890/xiaobaiyang2#37]

**Comment by liupan1890** [comment]
不知道 现在的版本  你遇到了什么问题，需要我更新？

1. 从js转ts基本上就是全部代码重写一遍
2. 从golang转ts的代码比较多，也需要很长时间
3. vue3刚发布，很多插件不支持vue3,或者是bate版本，需要测试一些插件的稳定性、寻找替代插件
4. 套electron后体积暴增，我需要思考设计一个合理的简洁的更新方式
zip体积           小白羊 3MB，MPV 30MB，electron 76MB==100MB
原始文件体积 小白羊 10MB，MPV 88MB，electron 170MB==268MB


预计是在12月中旬更新

**Comment by liveskai** [comment]
> 不知道 现在的版本 你遇到了什么问题，需要我更新？
> 
> 1. 从js转ts基本上就是全部代码重写一遍
> 2. 从golang转ts的代码比较多，也需要很长时间
> 3. vue3刚发布，很多插件不支持vue3,或者是bate版本，需要测试一些插件的稳定性、寻找替代插件
> 4. 套electron后体积暴增，我需要思考设计一个合理的简洁的更新方式
>    zip体积           小白羊 3MB，MPV 30MB，electron 76MB==100MB
>    原始文件体积 小白羊 10MB，MPV 88MB，electron 170MB==268MB
> 
> 预计是在12月中旬更新

现在的问题就是浏览器操作不好
