### ISSUE TITLE
Macos版 Big Sur系统安装后无法使用

### ISSUE THREAD

**Issue by jasonlee69** [liupan1890/xiaobaiyang2#38]
安装后，点击没有任何反应，界面无法打开。

**Comment by liupan1890** [comment]
11月8日20点00 https://wws.lanzous.com/b01nqc4gd 旧版链接备用


试一下旧版

另外，在你解压的位置，比如   6盘小白羊版.app\Contents\MacOS\AppData\debug.log  这个文件是日志，可能有错误信息，有的话贴一下给我看

**Comment by liupan1890** [comment]
11月8日20点00 https://wws.lanzous.com/b01nqc4gd 旧版链接备用


试一下旧版

另外，在你解压的位置，比如   6盘小白羊版.app\Contents\MacOS\AppData\debug.log  这个文件是日志，可能有错误信息，有的话贴一下给我看

**Comment by jasonlee69** [comment]
感谢，旧版可以打开浏览器页面，但显示无法连接页面，http://localhost:2020。运行后在6盘小白羊版.app\Contents\MacOS\AppData\目录只有www.db文件，没有debug.log的日志文件

**Comment by liupan1890** [comment]
我的测试机是macOS 10.15，Big Sur不知道是哪版，一会我去查一下。我没有mac，只有虚拟机，所以可能测试的不够全面

能打开浏览器页面，说明小白羊可以运行（6盘小白羊版.app\Contents\MacOS\6盘小白羊版）跟系统版本关系就不大了

没有debug.log，说明服务没能正常运行（6盘小白羊版.app\Contents\MacOS\6panserver）

就怕这种，因为不知道他是为什么不能运行，可能是端口2020被别的程序占用了，也可能是别的bug

我暂时也没有办法----因为是在你的电脑上不能运行，我没法调试，找不到错误在哪，所以没法修正

如果可以的话，耐心等我12月10日左右会发布新版本，新版本会套electron，另外代码也全部重构了，理论上会减少很多莫名的BUG

**Comment by jasonlee69** [comment]
我用的版本是 macOS Big Sur 11.0.1 ,我查看了2020端口，没有程序占用，可能是别的原因。
我把这个问题关闭，期待你的新版本发布，希望可以使用。再次感谢！

**Comment by liupan1890** [comment]
新版本已发布，试一下吧

**Comment by jasonlee69** [comment]
感谢，我12号第一时间测试了，出现了备注中提到的白屏，依旧没有debug.log文件，我想是因为服务没有启动的缘故。
