### ISSUE TITLE
离线百度出问题了吗？一直是排队中，我购买了付费服务的

### ISSUE THREAD

**Issue by a1798636524** [liupan1890/xiaobaiyang2#39]
如图所示上一个是度盘的一个文件夹，后一个是一个单独的文件，貌似都是排队中
![屏幕截图 2020-11-29 132904](https://user-images.githubusercontent.com/33086354/100534233-8deb3180-3247-11eb-85ab-b581e9b1dd3a.png)

**Comment by liupan1890** [comment]
抱歉，排队中这种问题，是6盘的问题，你应该在6盘网站发工单，或者在6盘官方博客留言，或者在6盘官方问答留言

一般是发工单

小白羊跟6盘官方没有关联，无法解答6盘的问题

**Comment by liupan1890** [comment]
工单   https://2dland.cn/ticket/add

博客  https://www.cnblogs.com/6pan/p/13956333.html

问答  https://0e0e083932c23d0f.kf5.com/hc/community/topic/
