### ISSUE TITLE
视频播放可以加入倍速播放么

### ISSUE THREAD

**Issue by Zhao-Peng-Hui** [liupan1890/xiaobaiyang2#40]
开发者您好：
视频播放可以加入倍速播放么

**Comment by liupan1890** [comment]
你的理解似乎有误

小白羊的在线播放，是调用你本地播放软件播放，默认推荐MPV

既然是你本地的播放软件，那就自己调整一下倍速喽。MPV 调整的快捷键是  **]** 或  **}**

![无标题](https://user-images.githubusercontent.com/67817756/100569556-5f358f80-3309-11eb-8d79-18f99ca2645b.png)

如果你自己设置的是其他的播放软件，比如Potplayer,那也是一样的，自己看一下软件倍速调整的按钮

**Comment by liupan1890** [comment]
百度搜索到的

https://blog.csdn.net/qq_32719871/article/details/80475737

作为个人认为最好用的播放器之一的MPV播放器，其开源，体积小，支持的格式多样等等非常优秀的功能。但其中也有部分麻烦的地方，因为功能太过强大，导致不知道某些功能的快捷键是什么，这就非常需要一个可以查阅的表了。但是官方给的说明太过长了，我还是自己整理一下吧，也主要是自己常用到的快捷键。

1对比度 -

2对比度+

3亮度 -

4亮度+

5伽马 -

6伽马+

7饱和度 -

8饱和度+

9音量减小

0音量增加

上方向键播放进度快进1分钟

下方向键播放进度快退1分钟

左方向键播放进度后退5秒

右方向键播放进度前进5秒

ctrl与 - 号组合 音轨和视频的调节（音轨快进一些）

CTRL与+号组合 音轨和视频的调节（音轨减慢一些）

p或者空格 暂停

i  显示视频的详情参数

m 静音

z 字幕后退

x 字母前进

f全屏

q 退出

＃切换音频轨，多音频的可以用

j 切换字幕，多字幕的时候可以使用

J 大写，反方向的切换字幕

【或{   播放速度减慢，变化速度不一样

】或}   播放速度加快，倍速变化速度不一样

backspace 播放速度返回到一倍速

< 逐帧播放

> 按下播放，回弹暂停



可以看看官方的文件，有点多

mpv keybindings

**Comment by liupan1890** [comment]
因为每个播放软件的快捷键都不一样，我不会在小白羊提供调整倍速的功能（我懒得去安装几十款常用播放软件，一个一个的测试他的快捷键是什么），所以，请在播放时自己调整播放软件的倍速。

倍速，亮度，声音大小，字母，音轨  这些设置，不论那一款播放软件，都支持随意设置的
