### ISSUE TITLE
下载提示无效操作

### ISSUE THREAD

**Issue by yayaleslie** [liupan1890/xiaobaiyang2#41]
最近下载一直提示 无效操作，不知是否是bug
![image](https://user-images.githubusercontent.com/19268555/101232024-1f482100-36ea-11eb-99e5-cce89fea78ce.png)

**Comment by liupan1890** [comment]
我翻了一下代码，确认，“”无效操作“”这个错误提示并不是小白羊里面的提示，所以说明是6盘返回的错误信息

我又试了一下用小白羊去下载文件和文件夹，并没有遇到此提示

逻辑上就是，
正常情况 你点击下载，调用6盘接口获取下载链接，6盘返回下载链接
错误情况 你点击下载，调用6盘接口获取下载链接，6盘返回无效操作

我猜测，
1. 是否你要下载的文件已经删除？（比如你昨天创建的下载任务，今天把文件删除了，但还没下载完）
2. 是否因为下载太频繁6盘返回限制？（一般是503,403错误而不会提示无效操作）
3. 是否你当前账号的登录状态已失效？（需要重新登录6盘）


请问
1. 出现此提示，是在点击下载按钮创建新的下载任务时，还是在点击现有任务的开始按钮时？
2. 当前登陆的是VIP账号还是免费账号？
3. 以前没出现过，最近才出现的？

**Comment by yayaleslie** [comment]
这个最近出现的，不知是否是6盘返回的，但是我把www.db替换后，现在可以了

**Comment by liupan1890** [comment]
我也刚想到，你是不是升级的时候文件没复制全啊----就是只复制了exe,没复制AppData里面的www.db

因为exe版本和www.db版本不一致导致的
