### ISSUE TITLE
mac打开后显示无法显示网页

### ISSUE THREAD

**Issue by ElvenP** [liupan1890/xiaobaiyang2#42]
无法访问此网站localhost 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by liupan1890** [comment]
请使用11月8日20点00 https://wws.lanzous.com/b01nqc4gd 旧版链接备用

最新版似乎有BUG。。。争取周日会发布新版本

**Comment by liupan1890** [comment]
经测试发现，发生此错误是因为6panserver这个文件没有正常运行，我稍后会尝试修复此问题。可能是mac的权限限制比较多
