### ISSUE TITLE
问题&建议

### ISSUE THREAD

**Issue by YKYCYKYC** [liupan1890/xiaobaiyang2#43]
大佬，想问下远程管理可以实现权限限制吗，比如只读；然后还有一个就是能否实现指定的单个文件夹远程管理。

**Comment by liupan1890** [comment]
你好

#### 远程管理可以实现权限限制吗
远程管理的目的不是多人共用，所以并没有设计权限管理功能

#### 能否实现指定的单个文件夹远程管理
这个功能我之前没考虑过，所以现在没有这个功能


#### 远程管理的功能
其实远程管理仅仅是为了我管理vps上的下载和转发，就是完全个人使用的。小白羊只是个下载软件啊喂，不要考虑那么复杂。

**Comment by iPixelOldC** [comment]
> 
> 
> 你好
> #### 远程管理可以实现权限限制吗
> 
> 远程管理的目的不是多人共用，所以并没有设计权限管理功能
> #### 能否实现指定的单个文件夹远程管理
> 
> 这个功能我之前没考虑过，所以现在没有这个功能
> #### 远程管理的功能
> 
> 其实远程管理仅仅是为了我管理vps上的下载和转发，就是完全个人使用的。小白羊只是个下载软件啊喂，不要考虑那么复杂。

说到远程管理这个，能否出个arm64的版本呢？我家的一堆小服务，都扔树莓派4上的（便宜嘛，并且功耗也低)，本来瞅着开源了自己去编译一份，但后端没开源，这就尴尬了，所以拜托了，如果有空闲时间，麻烦出份arm64v8或aarch64的，谢谢了

**Comment by YKYCYKYC** [comment]
好的，只是想提个小建议，感谢小白羊的开发，很好用，赞👍

**Comment by liupan1890** [comment]
> > 你好
> > #### 远程管理可以实现权限限制吗
> > 远程管理的目的不是多人共用，所以并没有设计权限管理功能
> > #### 能否实现指定的单个文件夹远程管理
> > 这个功能我之前没考虑过，所以现在没有这个功能
> > #### 远程管理的功能
> > 其实远程管理仅仅是为了我管理vps上的下载和转发，就是完全个人使用的。小白羊只是个下载软件啊喂，不要考虑那么复杂。
> 
> 说到远程管理这个，能否出个arm64的版本呢？我家的一堆小服务，都扔树莓派4上的（便宜嘛，并且功耗也低)，本来瞅着开源了自己去编译一份，但后端没开源，这就尴尬了，所以拜托了，如果有空闲时间啥的，麻烦出份arm64v8或aarch64的，谢谢了

过几天我会上传一份arm64的

**Comment by iPixelOldC** [comment]
谢谢 :D




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liupan1890"<notifications@github.com&gt;; 
发送时间: 2020年12月12日(星期六) 晚上6:01
收件人: "liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;; 
抄送: "iPixelOldC "<ipixeloldc@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [liupan1890/xiaobaiyang2] 问题&amp;建议 (#43)





   
你好
 
远程管理可以实现权限限制吗
 
远程管理的目的不是多人共用，所以并没有设计权限管理功能
 
能否实现指定的单个文件夹远程管理
 
这个功能我之前没考虑过，所以现在没有这个功能
 
远程管理的功能
 
其实远程管理仅仅是为了我管理vps上的下载和转发，就是完全个人使用的。小白羊只是个下载软件啊喂，不要考虑那么复杂。
  
说到远程管理这个，能否出个arm64的版本呢？我家的一堆小服务，都扔树莓派4上的（便宜嘛，并且功耗也低)，本来瞅着开源了自己去编译一份，但后端没开源，这就尴尬了，所以拜托了，如果有空闲时间啥的，麻烦出份arm64v8或aarch64的，谢谢了
  
过几天我会上传一份arm64的
 
&mdash;

**Comment by liupan1890** [comment]
> 谢谢 :D

呃今天编译，遇到了个问题，就是你是要linux的arm64是吧？因为我没用过树莓派，只知道是linux，但不知道版本什么的，我试过windows上go只能编译arm，不能编译arm64,不知道是为啥。。。等2周后，版本稳定了（鬼知道会有什么BUG），我会上传ui的源码，同时也会新开一个resp，上传go的源码，全部开源出来，你自己折腾去吧，我最近在找工作，实在是忙得一匹

**Comment by iPixelOldC** [comment]
> > 谢谢 :D
> 
> 呃今天编译，遇到了个问题，就是你是要linux的arm64是吧？因为我没用过树莓派，只知道是linux，但不知道版本什么的，我试过windows上go只能编译arm，不能编译arm64,不知道是为啥。。。等2周后，版本稳定了（鬼知道会有什么BUG），我会上传ui的源码，同时也会新开一个resp，上传go的源码，全部开源出来，你自己折腾去吧，我最近在找工作，实在是忙得一匹
> 
> ![无标题](https://user-images.githubusercontent.com/67817756/102002813-1a631d00-3d3b-11eb-88ea-971bc0719515.png)

- 对，是要Linux的
- 看上去go这边应该是只有arm的，我也不太情况他这个是32位的，还是64位的。像其他语言会分更清楚点，比如隔壁rust的是aarch64-unknown-linux-gnu。我太久没弄过go，所以说错了...反正是arm就行
- 题外话：可以试试这个 ![gox](https://github.com/mitchellh/gox) 直接把能编译的平台，全部给你编译一遍。看结果，里面也是只有arm的。并且说不定有人也想在mips的路由器上跑这个软件呢

**Comment by liupan1890** [comment]
嗯，收到，计划就是2周后，会全部放出，这样其他人也可能会想自己编译其他版本，系统+CPU组合太多，我就偷懒只编译win,linux
,mac了，中间等BUG修BUG。我先关了这个issue了，有问题发新的issue
