### ISSUE TITLE
新版本无法登录账号！！

### ISSUE THREAD

**Issue by hsiayuchih** [liupan1890/xiaobaiyang2#44]
不管使用手机号还是账号密码登陆均提示“账号登陆失败：loginstatus Error”

**Comment by liupan1890** [comment]
不是这么惨吧，刚发布就重大BUG？？

**Comment by liupan1890** [comment]
我在蓝奏下载了6盘小白羊版win64.7z测试，手机号+密码正常登录，用户名+密码正常登录，Cookie没测试

1. 请问你下载的哪一个？？（win64、win32、linux、mac？？？）
2.账号登陆失败：loginstatus Error  这个报错，我去翻一下
3.测试了如果是用户名+错误的密码，报错Login Failed

**Comment by liupan1890** [comment]
我测试了全部系统，是正常的，你先用cookie登录吧

loginstatus Error这个错误我知道是在登陆成功后，获取同步cookie的时候发生的错误

但我不知道为什么会发生错误，已经登陆成功了，刷新就给cookie了，但是你遇到了刷新不给cookie

为什么不给呢？？不知道。。。。。所以我还要去研究研究，但问题是我这里测试他就是给cookie了啊，很正常啊。。。。遇不到错误这怎么测试呢、、、、

**Comment by hsiayuchih** [comment]
> 我在蓝奏下载了6盘小白羊版win64.7z测试，手机号+密码正常登录，用户名+密码正常登录，Cookie没测试
> 
> 1. 请问你下载的哪一个？？（win64、win32、linux、mac？？？）
>    2.账号登陆失败：loginstatus Error  这个报错，我去翻一下
>    3.测试了如果是用户名+错误的密码，报错Login Failed

下的是win64版，刚刚测试发现又可以了...就挺突然的

**Comment by liupan1890** [comment]
嗯，归类为网络问题吧
