### ISSUE TITLE
windows客户端根目录选择多个文件可以按住shift多选文件

### ISSUE THREAD

**Issue by jzysl123** [liupan1890/xiaobaiyang2#45]
可以增加这个功能吗
win7 关闭界面后 右下角图标双击不能显示主界面 得右键。。。

**Comment by liupan1890** [comment]
#### windows客户端根目录选择多个文件可以按住shift多选文件可以增加这个功能吗
你问的我有点懵，我又特意去测试了一下，本来就可以的啊，增加什么功能？？
1. 上传文件时，可以在同一目录下一次性选择多个文件（鼠标托选、按住Ctrl多点，按住shift多选）
2. 上传文件夹时，同理可以在同一目录下一次性选择多个文件夹

唯一的限制就是不能同时选择文件夹和文件

跟根目录有什么关系？

windows，mac，linux都可以多选

#### win7 关闭界面后 右下角图标双击不能显示主界面 得右键
这是个BUG，下次更新时会修复

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/102008153-6dec5f80-3d69-11eb-892f-761e4c3ff111.png)

**Comment by jzysl123** [comment]
不是上传文件多选 我说是在软件中选择文件操作 比如选择多个文件移动到另一个文件夹

**Comment by liupan1890** [comment]
在软件中选择文件操作 比如选择多个文件移动到另一个文件夹

不需要按住shift，直接用鼠标点击不就行了？？？你是说想这样一次选择多个文件吧？（文件+文件夹）
![无标题](https://user-images.githubusercontent.com/67817756/102010039-536cb300-3d76-11eb-9e92-8a7352b3a02c.png)

**Comment by liupan1890** [comment]
https://ae02.alicdn.com/kf/H80cf2330ebcc47e28268d7a84c485298Z.jpg

**Comment by liupan1890** [comment]
rss里，小白羊操作帮助，批量重命名  不是有教程吗，没有看到？

**Comment by jzysl123** [comment]
选择是可以一个一个的点选 但是如果几十个的话 也只能一个个点选
选择多个  意思就是先点选第一个 然后按住shift 点选后面的某一个  这样中间的就全部选中了

**Comment by jzysl123** [comment]
![2020-12-13_200856](https://user-images.githubusercontent.com/51441378/102011452-2f619f80-3d7f-11eb-814a-1f79e37e2d42.jpg)

**Comment by liupan1890** [comment]
哦，你这样说我就明白了，现在确实没有这个功能，我需要去研究研究，应该不难实现，争取下个版本就加上

**Comment by liupan1890** [comment]
另外，一般来讲，有几十个，你就先点全选，然后再点击不要的，把不要的去掉。这样操作也挺快

**Comment by liupan1890** [comment]
![Uploading 无标题.png…]()

**Comment by liupan1890** [comment]
那个啥，新版本已上传，已增加shift键多选

https://ae02.alicdn.com/kf/H864ad8b784ae4482ab3d69980e3d9b3ez.jpg

**Comment by jzysl123** [comment]
感谢 另外百度链接的格式能不能加入这种  就是自己分享的链接复制的 例如下面
链接: https://pan.baidu.com/s/1claBggTeO7oJENatd_8fOw 提取码: 29nm 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by liupan1890** [comment]
eeeee好吧这又是一个BUG，，，我去改

**Comment by Qixingchen** [comment]
多选之后似乎没有下载按钮？  
目前只能单个文件夹或者文件进行下载

**Comment by liupan1890** [comment]
是的，原因是，假设有“”批量下载按钮“”  比如你勾选了几个文件夹，然后点击“”批量下载“” 

程序需要去一个一个的遍历每一个文件夹，以及每一个文件夹下面的所有文件和文件夹，

考虑到可能会因为短时间（1-2秒）内大量请求文件列表（6盘的api是每一个文件夹都要请求一次，不支持直接返回子文件夹的内容），被6盘限制，所以没有添加“”批量下载“”按钮

**Comment by liupan1890** [comment]
举个实际的例子，我的网盘内约有1万个文件，3000个文件夹（各种层级嵌套导致文件夹真的很多），如果我点击根目录的下载按钮（其实并没有根目录的下载按钮，也是这个考虑），golang我写的是协程并发的列文件，会在极短时间内（2-3秒内），发出3000个列文件的请求，我估计时间长了6盘肯定会说，怎么这么多请求？会给我屏蔽掉

所以，就没有提供，批量下载按钮，

小白羊是完全开源的，你可以拉一份代码自己实现批量下载按钮这个功能，我已经留好了接口啦，很容易就实现了

**Comment by Qixingchen** [comment]
如果是因为这个原因的话 在批量选择中只有文件时提供下载是不会有影响的。  
嗯嗯 目前不影响我的使用

**Comment by liupan1890** [comment]
稍后我再想想怎么处理合适吧，总感觉，选了一堆文件，显示了批量下载按钮，然后又选了一个文件夹，批量下载按钮就消失了，这个操作逻辑不优雅。我再想想

**Comment by liupan1890** [comment]
有问题发新的issue啊，这个留言太长了，百度链接BUG已修复，关了
