### ISSUE TITLE
关于最小化的问题

### ISSUE THREAD

**Issue by yongqingxie** [liupan1890/xiaobaiyang2#47]
大佬能增加最小化到托盘的功能吗 当前的最小化并非最小化到托盘  关闭按钮直接关闭前台程序

**Comment by liupan1890** [comment]
你好

1. 最小化按钮
最小化到任务栏

2.关闭按钮
最小化到托盘

3.关闭
右键托盘图标，点击《彻底退出并停止下载》

所以现在的关闭按钮，就是你想要的最小化按钮

**Comment by yongqingxie** [comment]
> 你好
> 
> 1. 最小化按钮
>    最小化到任务栏
> 
> 2.关闭按钮
> 最小化到托盘
> 
> 3.关闭
> 右键托盘图标，点击《彻底退出并停止下载》
> 
> 所以现在的关闭按钮，就是你想要的最小化按钮

哦 看到了  没有注意到
