### ISSUE TITLE
远程管理如何使用？

### ISSUE THREAD

**Issue by RheumGitHub** [liupan1890/xiaobaiyang2#48]
跪求大佬解答，远程管理的作用是什么呢？如何使用？

**Comment by liupan1890** [comment]
远程管理功能介绍：

是指本机运行小白羊，然后在其他电脑通过浏览器管理。
除了在线预览图片、视频、音频、上传文件功能外，其他功能均支持远程管理
一般都用不到此功能，主要是vps用户使用无UI的linux系统才会用到此功能


远程管理功能教程：
注：下面提到的 1111111111111111 只是举例，实际操作时请用自己的密码（长度16位的字符串）

---  windows  ----

1.cmd下打开 6盘小白羊版win64\electron\resources\
执行命令  6panserver.exe --isremote=true --password=1111111111111111
2.在其他电脑使用浏览器打开 http://IP:29375/
3.在远程管理密码弹窗里填写1111111111111111
4.可以远程管理使用了

----  mac ox  ----

1.终端里打开 6盘小白羊版.app\Contents\Resources\
执行命令  .\6panserver --isremote=true --password=1111111111111111
2.在其他电脑使用浏览器打开 http://IP:29375/
3.在远程管理密码弹窗里填写1111111111111111
4.可以远程管理使用了

----  linux  ----

1.终端里打开 6盘小白羊版linux64\electron\resources\
执行命令  .\6panserver --isremote=true --password=1111111111111111
2.在其他电脑使用浏览器打开 http://IP:29375/
3.在远程管理密码弹窗里填写1111111111111111
4.可以远程管理使用了


----  无UI的Linux（比如一台vps）  ----

0.在其他电脑里，打开 6盘小白羊版linux64\electron\resources\
把 ''6panserver'' , 'AppData' 用ftp上传到 vps，并修改上传的 ''6panserver'' 文件权限为可执行
1.ssh连接到vps，找到刚刚上传的文件
执行命令  .\6panserver --isremote=true --password=1111111111111111
2.在其他电脑使用浏览器打开 http://IP:29375/
3.在远程管理密码弹窗里填写1111111111111111
4.可以远程管理使用了

5.可以创建一个脚本文件，里面包含命令  .\6panserver --isremote=true --password=1111111111111111
然后把此脚本文件设置成服务并开机启动，以后就不需要重复连接vps执行命令了

**Comment by liupan1890** [comment]
我在所有的压缩包里面都打包了远程管理帮助.txt
另外在蓝奏里，还有 

作教程.zip            20.6 M                2020-10-27

这个文件，里面有2.1.1版本的远程管理教程录像

**Comment by RheumGitHub** [comment]
好的 感谢开发者热心解答！

**Comment by liupan1890** [comment]
嗯，留意2.1版本和最新版2.2版本细微差别即可，整体上思路一样的
