### ISSUE TITLE
Windows Defender 警告

### ISSUE THREAD

**Issue by skyhow** [liupan1890/xiaobaiyang2#49]
約從今天早上開始，Windows defender 便會提出警告(Trojan:Win32/Spursint.F!cl) 要求移除資料夾內的 小白羊 和 electron，
我不明白它怎麼了。

**Comment by liupan1890** [comment]
你好

这是非常常见的，小白羊第一版也遇到了此问题

问题描述：微软杀毒软件将小白羊检测为病毒程序

问题原因：小白羊程序本身未经过任何证书签名，且未经过任何认证，且程序内部通过命令行方式调用第三方软件（mpv播放器）

解决方案
1. 购买证书签名，一年约5000元
2. 在微软杀毒申诉页面上传小白羊程序并进行申诉，等待微软杀毒的过签（每一次升级都需要重新申诉---因为文件MD5值改变了）

注意，不仅仅是微软杀毒，360杀毒，卡巴斯基，等等等等，所有的杀毒软件都可能会对未签名的程序进行误杀。

我懒得弄，所以最终解决方案就是，在微软杀毒软甲里，将小白羊加入到信任名单，这样就可以继续使用了

**Comment by liupan1890** [comment]
请参阅  https://blog.csdn.net/qq_43453731/article/details/104722165

**Comment by skyhow** [comment]
明白了，主要是前一個版本，沒有發生這個警告，更新後出現，才產生的疑問，謝謝解答
