### ISSUE TITLE
小白羊一版一直提示没有离线次数

### ISSUE THREAD

**Issue by t1a1** [liupan1890/xiaobaiyang2#5]
你好，小白羊一版一直提示没有离线次数，不管几点下载全显示这个信息。使用搜索、百度网盘的地址，下载时一直提示没有离线次数。请问是否是工具的问题？还是服务器端进行了限制？希望有空能够解决，谢谢

**Comment by liupan1890** [comment]
因为某些原因，我已经被迫关闭掉了内置的账号，现在使用小白羊是无法使用内置账号的，又因为我写死了百度链接调用内置账号，所以下载的小白羊是无法离线百度连接的，只能离线磁力、电驴等。（你可以在6盘官网提交百度链接，然后用小白羊下载）

因为某些原因，小白羊第二版，已经彻底屏蔽了搜索功能，你可以自己搜索链接提交，但不能使用小白羊搜索了

**Comment by t1a1** [comment]
感谢回复！可是之前使用小白羊一版时，用搜索功能找到了一些资源还没有下载完成！在百度网盘资源的搜索网站又找不到，不知能否对小白羊一版的用户放开一定的时间，能让有这种情况的用户下载完这些资源。
建议告知大家一个时间点，之后就不开放了。当然这只是个建议，如不方便就算了。谢谢
