### ISSUE TITLE
帐号登录失败，提示read connection refused

### ISSUE THREAD

**Issue by yi0332** [liupan1890/xiaobaiyang2#50]
报错提示
帐号登录失败: Post "https://account.2dland.cn/v3/oauth/login": dial tcp: lookup account.2dland.cn on [::1]:53: read udp [::1]:xxxxx->[::1]:53: read: connection refused

请问能指定端口登录吗？
随机端口我不知道防火墙要允许那一个范围的

**Comment by Qixingchen** [comment]
53 是 DNS 端口
访问的 HTTPS 是 443

**Comment by yi0332** [comment]
> 报错提示
> 帐号登录失败: Post "https://account.2dland.cn/v3/oauth/login": dial tcp: lookup account.2dland.cn on [::1]:xxxxx->[::1]:53: read: connection refused
> 
> 请问能指定端口登录吗？
> 随机端口我不知道防火墙要允许那一个范围的
> 

这里的xxxxx是不停改变的5位数数字（3-5开始的）

**Comment by liupan1890** [comment]
1.  报错提示
理解为无法访问网络，可能是当时的网络有问题，或者是6盘的这个域名当时有问题，也肯能是你本地路由设置的问题，总之，是无法访问网络

2. 随机端口
你的理解不全面，
现在是访问外网，端口就是随机的，是无法指定的。
只有从外网访问你，才需要指定一个端口，小白羊，默认使用本地端口29375，外网无法访问。当使用命令行参数启动远程管理模式时，是使用外网端口29375，外部才能访问你

总之，说了半天都是废话，你就说你是什么系统，我告诉你怎么设置你系统的防火墙试试吧

**Comment by liupan1890** [comment]
另外你试试直接使用浏览器，打开6盘官网，可以登陆吗？

因为一般的防火墙，都不限制任何程序去主动访问外网，防火墙都是限制外网主动访问程序的。就是不限制出站，限制入站。所以理论上不应该遇到因为防火墙不能访问的时候，除非你  特意的、手动的、主动地   去设置防火墙禁止指定的程序（6panserver.exe）访问外网。只要你没有特意的、手动的、主动地   去设置防火墙，那就可能不是防火墙的问题

**Comment by yi0332** [comment]
> 1.  报错提示
> 理解为无法访问网络，可能是当时的网络有问题，或者是6盘的这个域名当时有问题，也肯能是你本地路由设置的问题，总之，是无法访问网络
> 
> 2. 随机端口
> 你的理解不全面，
> 现在是访问外网，端口就是随机的，是无法指定的。
> 只有从外网访问你，才需要指定一个端口，小白羊，默认使用本地端口29375，外网无法访问。当使用命令行参数启动远程管理模式时，是使用外网端口29375，外部才能访问你
> 
> 总之，说了半天都是废话，你就说你是什么系统，我告诉你怎么设置你系统的防火墙试试吧

应该是GCP那边有问题（暂时无法连上，但VPS上的Aria2c正常运行.）

我刚刚下了win64版本来测试是成功登录的
应该就你所说是vps的问题

官网确定是可以正常登录［6pan/win64]

**Comment by liupan1890** [comment]
有的时候确实会遇到，临时性的，域名不可访问，可能简单的就是网络问题，DNS解析问题，会自动恢复的，不需要自己手动修改什么。如果你是使用的远程管理模式，也仅仅是需要注意在防火墙里允许6panserver.exe通过，开放29375端口即可。并不需要其他的特殊设置了

**Comment by yi0332** [comment]
> 有的时候确实会遇到，临时性的，域名不可访问，可能简单的就是网络问题，DNS解析问题，会自动恢复的，不需要自己手动修改什么。如果你是使用的远程管理模式，也仅仅是需要注意在防火墙里允许6panserver.exe通过，开放29375端口即可。并不需要其他的特殊设置了

报告情况
发生问题的原因是6pan太多档案下载失败
结果系统空间不足出现的错误（下载不成功的档案被占用空间）
所以不能一次性下太大的档案

**Comment by liupan1890** [comment]
为什么会有很多文件下载失败呢？你是用的VIP账号还是免费账号？下载失败的报错是什么？

我知道免费账号肯定会有很多下载失败，因为6盘限制是免费用户，同一个域名，最多同时有2个链接，假设你设置为4线程并发，将导致全部文件下载失败，没有一个可以成功下载。假设你设置为单线程下载，3文件同时下载，将会出现一部分文件下载失败。只有你设置单线程单文件，才能减少下载失败的数量。。但是免费用户又有限速，冷文件单线程限速200kb/s这样，热文件是5MB/s这样

但是我再用VIP账号时基本遇不到下载失败，

另外是 “下载不成功的档案被占用空间”“” 问题
下载不成功，你也下载了一部分，重新开始会断点续传。因为断点续传功能，所以不能说把下载失败的文件删除掉

所以从逻辑上将， “下载不成功的档案被占用空间”“” 问题无解啊

**Comment by liupan1890** [comment]
越是下载失败的文件，越说明这个文件比较难下，越需要断点续传，一遍遍的重试直到最后成功对吧

**Comment by yi0332** [comment]
> 为什么会有很多文件下载失败呢？你是用的VIP账号还是免费账号？下载失败的报错是什么？
> 
> 我知道免费账号肯定会有很多下载失败，因为6盘限制是免费用户，同一个域名，最多同时有2个链接，假设你设置为4线程并发，将导致全部文件下载失败，没有一个可以成功下载。假设你设置为单线程下载，3文件同时下载，将会出现一部分文件下载失败。只有你设置单线程单文件，才能减少下载失败的数量。。但是免费用户又有限速，冷文件单线程限速200kb/s这样，热文件是5MB/s这样
> 
> 但是我再用VIP账号时基本遇不到下载失败，
> 
> 另外是 “下载不成功的档案被占用空间”“” 问题
> 下载不成功，你也下载了一部分，重新开始会断点续传。因为断点续传功能，所以不能说把下载失败的文件删除掉
> 
> 所以从逻辑上将， “下载不成功的档案被占用空间”“” 问题无解啊

我大约安排了500个档案在一个资料夹下载
主要是6pan官方太多EOF错误导致的问题
500个档案都下了部份就报错跳下一个任务
结果储存空间不足死机了

**Comment by liupan1890** [comment]
6pan官方太多EOF错误

这个真无解，原因很多，主体上还是6盘缓存节点从数据源拉取  跟  你下载速度 之间的冲突，比如他拉取的慢但你下的快，比如他线路波动了  

6盘早期经常在cnblog上说一下遇到的各种线路问题，现在转到客服上去了，细节都不给说了


可以讨论一下错误的处理机制，现在是，

1. 先把大文件分片（比如100MB一片），按顺序去一片一片的下载，
2. 每一片下载时出错了就立即重试（4MB每小片，断点续传），连续重试5次都失败就跳过这个分片
3. 等全部分片都下载结束，判断是否全部成功，有出错的显示报错，反之显示成功
4. 下载下一个文件

但是实际上，如果遇到了EOF，立即重试一般也还是EOF，所以很多时候并不是重试了就成功了

是不是有更好的机制去容错呢？

另外出错与否，跟文件关系很大，下载这个文件就不出错，下载那个文件，就容易出错，应该是跟文件在6盘的存储位置有关，6盘说过文件是分片存储的，并不是一个文件整体的保存在那，而是把文件分成很多片，把片存储在那里，不知道是为什么这么设计，减少重复文件的空间占用？
