### ISSUE TITLE
验证码登录的问题

### ISSUE THREAD

**Issue by TIANCHENWEI609** [liupan1890/xiaobaiyang2#52]
V2.2不准备做验证码登录的功能吗？

**Comment by liupan1890** [comment]
你好

嗯，从一开始就不打算做验证码登录功能，以后也不会支持

**Comment by liupan1890** [comment]
虽然我没有提供验证码登录，但是提供了cookie登录啊，你可以直接在官网登录。然后复制粘贴cookie就好了，就等于是验证码登陆了，只是多了一步复制粘贴

**Comment by TIANCHENWEI609** [comment]
在官网用验证码登录的也能用cookie吗？

发自我的荣耀手机


-------- 原始邮件 --------
发件人： liupan1890 <notifications@github.com>
日期： 2020年12月18日周五 09:44
收件人： liupan1890/xiaobaiyang2 <xiaobaiyang2@noreply.github.com>
抄送： TIANCHENWEI609 <TIANCHENWEI609@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [liupan1890/xiaobaiyang2] 验证码登录的问题 (#52)

虽然我没有提供验证码登录，但是提供了cookie登录啊，你可以直接在官网登录。然后复制粘贴cookie就好了，就等于是验证码登陆了，只是多了一步复制粘贴

―

**Comment by Qixingchen** [comment]
官网任意方法登入后的 Cookie 都能用

**Comment by TIANCHENWEI609** [comment]
我看有教程，但是找了半天没看到教程，这个是需要自己百度吗？还是有相关的帖子。

发自我的荣耀手机


-------- 原始邮件 --------
发件人： qixingchen <notifications@github.com>
日期： 2020年12月18日周五 10:35
收件人： liupan1890/xiaobaiyang2 <xiaobaiyang2@noreply.github.com>
抄送： TIANCHENWEI609 <TIANCHENWEI609@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [liupan1890/xiaobaiyang2] 验证码登录的问题 (#52)

官网任意方法登入后的 Cookie 都能用

―

**Comment by Qixingchen** [comment]
https://wws.lanzous.com/iMQD1hsaqde

**Comment by TIANCHENWEI609** [comment]
非常感谢，大佬请收下我的膝盖。

发自田先生的OUTLOOK邮箱


-------- 原始邮件 --------
发件人： qixingchen <notifications@github.com>
日期： 2020年12月18日周五 10:42
收件人： liupan1890/xiaobaiyang2 <xiaobaiyang2@noreply.github.com>
抄送： TIANCHENWEI609 <TIANCHENWEI609@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [liupan1890/xiaobaiyang2] 验证码登录的问题 (#52)

https://wws.lanzous.com/iMQD1hsaqde

―

**Comment by TIANCHENWEI609** [comment]
这个cookie提示格式化错误：请问一下是什么原因。是从F12里面直接复制的
cookie: locale=zh-cn; token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6MTQwODIsIm5hbWUiOiJhZHNuZiIsInZlcnNpb24iOjIsInNzaWQiOiIxZjk4YjA1OS01NWYzLTQ4N2ItYjg0ZC05OWNjZTY0OTExZWMiLCJkZXZpY2UiOiJXaW5kb3dzIENocm9tZSA4Ny4wLjQyODAuODgiLCJwZXJtaXNzaW9uIjozLCJzaWduVGltZSI6MTYwODI5Njg2OTk2OCwibG9naW5UaW1lIjoxNjA4Mjk2ODY5OTYxLCJsb2dpbkFkZHIiOiIxMjEuNzEuNzguOCIsInJlZnJlc2hUaW1lIjowLCJjayI6IjE0MDgyXzNhNTY1NGE5Y2NjOSIsImlhdCI6MTYwODI5Njg2OSw
iZXhwIjoxNjEwODg4ODY5fQ.GL8YAtpnOIftLVSquUskR2gMS2NrAxed5rdD_LdPd2Y; token.sig=-g9h94MCQC6_SQ8x_0VYNCyUmJSEIrhOcOtxrkYp10g
发件人: qixingchen <notifications@github.com>
发送时间: 2020年12月18日 10:43
收件人: liupan1890/xiaobaiyang2 <xiaobaiyang2@noreply.github.com>
抄送: TIANCHENWEI609 <TIANCHENWEI609@outlook.com>; Author <author@noreply.github.com>
主题: Re: [liupan1890/xiaobaiyang2] 验证码登录的问题 (#52)


https://wws.lanzous.com/iMQD1hsaqde

**Comment by liupan1890** [comment]
是我的锅，cookie: locale=zh-cn; token=把最开头的cookie:  改成Cookie:  就好了（c-->C）

下个版本我会修正此BUG，小写的也可以

**Comment by TIANCHENWEI609** [comment]
好的🤓

发自田先生的OUTLOOK邮箱


-------- 原始邮件 --------
发件人： liupan1890 <notifications@github.com>
日期： 2020年12月19日周六 09:58
收件人： liupan1890/xiaobaiyang2 <xiaobaiyang2@noreply.github.com>
抄送： TIANCHENWEI609 <TIANCHENWEI609@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [liupan1890/xiaobaiyang2] 验证码登录的问题 (#52)

是我的锅，cookie: locale=zh-cn; token=把最开头的cookie: 改成Cookie: 就好了（c-->C）

下个版本我会修正此BUG，小写的也可以
