### ISSUE TITLE
请求加入磁力连结批量导出功能

### ISSUE THREAD

**Issue by BlackMickey** [liupan1890/xiaobaiyang2#54]
由于部分种子6盘无法离线，想批量导出磁力连结，尝试使用其他网盘离线，目前已支援单一种子的磁力连结导出，希望能够添加批量导出的功能。

**Comment by liupan1890** [comment]
好的，会在下个版本增加此功能

注意：6盘会对你提交的离线链接格式化，因此，复制的链接，可能和你输入的原始链接不完全相同

**Comment by BlackMickey** [comment]
Thanks
