### ISSUE TITLE
下载一直403错误是为什么呢？

### ISSUE THREAD

**Issue by ecgz88** [liupan1890/xiaobaiyang2#56]
下载一直403错误是为什么呢？浏览器登录6盘以后下载也是403错误，才用了2天，没有任何敏感资源，只是个普通日剧

谢谢！

403
Forbidden
Error Times: Sun, 20 Dec 2020 03:36:58 GMT
IP: 50.98.121.103Node information: PSmgdfDEN1oj58
URL: https://cold3.qiecdn.com/***

**Comment by liupan1890** [comment]
参阅   https://0e0e083932c23d0f.kf5.com/hc/kb/article/1436630/

你好
小白羊只是第三方UI，403是6盘官方政策、限制，所以我也无法告诉你为什么会403，哪些文件会403，请在6盘官方网页版里发工单，请6盘官方客服回复
