### ISSUE TITLE
多选文件一键下载可以出一个吗

### ISSUE THREAD

**Issue by Sailing168** [liupan1890/xiaobaiyang2#57]
受限于硬盘空间，有点时候下载剧集不能一次下完
每当多选的时候，却只能一个一个点击下载，就不方便

**Comment by liupan1890** [comment]
自2020/12/13起增加了按住shift多选的功能
自2020/12/19起增加了批量下载功能

所以下载最新版，点击选择一个文件，按住Shift键，点击选择另一个文件，此时会自动选中2个文件之间的全部文件，并在顶部显示“”批量下载按钮“”，点击批量下载即可

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/102761529-fdb98b80-43b1-11eb-8444-ceb7c38e931e.png)

**Comment by Sailing168** [comment]
好的，3Q，确实不知道这个操作
