### ISSUE TITLE
您好，下载的mac版本，打开依旧是2.2.0，并非2.2.1

### ISSUE THREAD

**Issue by HaitaoShi** [liupan1890/xiaobaiyang2#59]
我用的是M1芯片的Macbook Pro. 打开后发现仍旧是2.2.0.
下载的时候‘全部暂停’并不能暂停全部任务，而只能暂停正在运行中的任务。
希望您能修改这一点以及提升对于M1芯片Mac的兼容性，非常感谢！

**Comment by liupan1890** [comment]
#### 打开后发现仍旧是2.2.0
只要你是19日以后下载的，就没事，显示2.2.0是因为我忘了修改配置文件，你在程序坞里面的6图标上，右键鼠标，显示的菜单里，会显示2.2.1，下个版本发布时我会修正配置文件

#### 下载的时候‘全部暂停’并不能暂停全部任务，而只能暂停正在运行中的任务
看来是有BUG，我去修正

#### 提升对于M1芯片Mac的兼容性
我比较穷，没有钱买mac，也没有钱买m1，m1是arm的跟其他确实不太一样，我发布的mac版本都是虚拟机里测试的，无法模拟m1,所以无法针对的去测试兼容

**Comment by HaitaoShi** [comment]
非常感谢您的回复！arm的除了一打开会报错，接下来使用并没有任何问题。另外，我说的‘全部暂停’的问题可能并不出现在intel的mac上。至少我在用intel mac的时候（上一版的小白羊）是没有这个bug的。再次感谢！保重！

**Comment by liupan1890** [comment]
12月22日 v2.2.2
1. 全部暂停已修复
2. 版本号已修正
