### ISSUE TITLE
作者你好,有个问题

### ISSUE THREAD

**Issue by GodOfKiller** [liupan1890/xiaobaiyang2#6]
我这边浏览器打开,页面排版混乱,换了一个浏览器也是这样也

**Comment by GodOfKiller** [comment]
![image](https://user-images.githubusercontent.com/44692789/97132500-19256300-1782-11eb-8d9f-ca4ee5b8552a.png)

**Comment by GodOfKiller** [comment]
![捕获](https://user-images.githubusercontent.com/44692789/97132568-538f0000-1782-11eb-949d-1a2f06456f6f.PNG)

**Comment by liupan1890** [comment]
报一下系统和浏览器，是本地访问还是远程管理，我去检查

我本地测试的是win7（360急速浏览器）和win10（EDGE）和ubuntu 20.04（火狐浏览器），并没有发现排版错乱的情况，我看截图，感觉应该是css没加载啊，反倒不像是浏览器兼容问题

**Comment by liupan1890** [comment]
另，试一下今天刚上传的版本看看

**Comment by GodOfKiller** [comment]
> 另，试一下今天刚上传的版本看看

你好,我是用的win10(谷歌和edge),用了新的版本了还是一样,是本地访问的地址
![image](https://user-images.githubusercontent.com/44692789/97185252-cb891480-17da-11eb-891b-d2fdbd1b6bfe.png)
![image](https://user-images.githubusercontent.com/44692789/97185310-dd6ab780-17da-11eb-8d93-2d94ecaa3eee.png)

**Comment by liupan1890** [comment]
哎呀，这是奇了怪了，我得研究研究，，，，，
1.我把所有的资源打包到www.db这个文件里了（html,js,css）
2.程序启动后加载读取这些(html,js,css)
3.没理由能读取到html,却读取不到css啊，你看截图，真是一个css也没加载到啊，

**Comment by GodOfKiller** [comment]
> 哎呀，这是奇了怪了，我得研究研究，，，，，
> 1.我把所有的资源打包到www.db这个文件里了（html,js,css）
> 2.程序启动后加载读取这些(html,js,css)
> 3.没理由能读取到html,却读取不到css啊，你看截图，真是一个css也没加载到啊，

作者辛苦了哈,慢慢来.

**Comment by liupan1890** [comment]
![网络图](https://github.com/liupan1890/xiaobaiyang2/raw/main/image/%E6%97%A0%E6%A0%87%E9%A2%98.png)


辛苦一下，帮我借一个网络图吧，，浏览器，打开小白羊，按F12，显示开发人员工具，点击Network，按F5刷新，我看一下是否是有css404了

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97187137-1dcb3500-17dd-11eb-8332-3339c47ee832.png)

**Comment by GodOfKiller** [comment]
> ![网络图](https://github.com/liupan1890/xiaobaiyang2/raw/main/image/%E6%97%A0%E6%A0%87%E9%A2%98.png)
> 
> 辛苦一下，帮我借一个网络图吧，，浏览器，打开小白羊，按F12，显示开发人员工具，点击Network，按F5刷新，我看一下是否是有css404了

![image](https://user-images.githubusercontent.com/44692789/97187356-5539e180-17dd-11eb-99d7-442512833d4a.png)

**Comment by liupan1890** [comment]
心态炸了，，，，，，没问题，全部正常加载，就是没有样式，今天整了一天的Ubuntu，，没心情了，，我明天认真调一下，没有直接想到是哪里的问题，，，，

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97188409-6e8f5d80-17de-11eb-9d29-ce8fa6155606.png)
看到有个js报错，是不是他的问题？帮我看一下错误信息呗？？？

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97188647-b57d5300-17de-11eb-82ee-4ec4ed0c3a53.png)
点它！！！

**Comment by liupan1890** [comment]
今天又发新版本了，试试

1.  我今天专门用vm装了一台全新的win10+edge，没能重现此BUG
2. 我今天重新修改了打包策略，之前是全部文件打在一起(一个css文件，一个js文件)。新版本是把用到的antd,vue,vuex,axios都使用官方发布的最新完整版本，独立文件，会减少打包可能会导致的问题

想了想，可能是某个插件的BUG，又因为打包在一起。都是猜测，我留意到你的截图中比正常的多了一个文件118.fb73b062.js，是不是安装了广告拦截插件误拦了？但是又想到你是edge和chrome都不行，，，，郁闷

**Comment by GodOfKiller** [comment]
我下了新版本试试

**Comment by GodOfKiller** [comment]
> ![无标题](https://user-images.githubusercontent.com/67817756/97188647-b57d5300-17de-11eb-82ee-4ec4ed0c3a53.png)
> 点它！！！

![image](https://user-images.githubusercontent.com/44692789/97291364-caacbd00-1884-11eb-95d4-809b0d819a9c.png)
还是yi'ya一样....我这个edge是没有装任何插件的

**Comment by GodOfKiller** [comment]
> ![无标题](https://user-images.githubusercontent.com/67817756/97188647-b57d5300-17de-11eb-82ee-4ec4ed0c3a53.png)
> 点它！！！

![image](https://user-images.githubusercontent.com/44692789/97291511-ffb90f80-1884-11eb-9a2b-d45790ef756d.png)

**Comment by GodOfKiller** [comment]
> 今天又发新版本了，试试
> 
> 1. 我今天专门用vm装了一台全新的win10+edge，没能重现此BUG
> 2. 我今天重新修改了打包策略，之前是全部文件打在一起(一个css文件，一个js文件)。新版本是把用到的antd,vue,vuex,axios都使用官方发布的最新完整版本，独立文件，会减少打包可能会导致的问题
> 
> 想了想，可能是某个插件的BUG，又因为打包在一起。都是猜测，我留意到你的截图中比正常的多了一个文件118.fb73b062.js，是不是安装了广告拦截插件误拦了？但是又想到你是edge和chrome都不行，，，，郁闷

![image](https://user-images.githubusercontent.com/44692789/97291741-47d83200-1885-11eb-920b-4deadadd6ab2.png)
这是谷歌的console

**Comment by GodOfKiller** [comment]
谷歌的有安装插件..

**Comment by liupan1890** [comment]
FixMIME  https://cowtransfer.com/s/497f4f92305b47

啊哈，很高兴看到你的反馈，我想我找到原因了，黄色警告中说css返回的mime是applocation/x-css

可能是go的mime.TypeByExtension 返回的有问题，我修改成直接判断url强制返回正确的Content-Type了（mime）

请从上面的奶牛快传地址，下载修正的版本（只有6panserver.exe）替换掉旧版试试，，感觉是可以的

**Comment by liupan1890** [comment]
网上搜到的解释是，TypeByExtension时会读取windows注册表，根据注册表里的值返回type。所以可能是你的电脑注册表.css这一项的值是x-css，而我的注册表里面是text/css---我感觉一般都是这个值。反正最终就是我这里正常返回（text/css）你那里返回(x-css)导致的此问题，因为6panserver.exe运行在你的电脑上。总之我改成根据url强制判断，不用TypeByExtension，应该就正常了

**Comment by liupan1890** [comment]
我改了我的注册表，测试了一下，完美重现了无css样式BUG：  

![x-css](https://user-images.githubusercontent.com/67817756/97335673-11b4a580-18b9-11eb-8bcd-7a95129330e2.png)

使用奶牛链接里的6panserver.exe后，显示正常了  


![text/css](https://user-images.githubusercontent.com/67817756/97335685-14af9600-18b9-11eb-88a7-1f74f817cf5c.png)

**Comment by GodOfKiller** [comment]
> 我改了我的注册表，测试了一下，完美重现了无css样式BUG：
> 
> ![x-css](https://user-images.githubusercontent.com/67817756/97335673-11b4a580-18b9-11eb-8bcd-7a95129330e2.png)
> 
> 使用奶牛链接里的6panserver.exe后，显示正常了
> 
> ![text/css](https://user-images.githubusercontent.com/67817756/97335685-14af9600-18b9-11eb-88a7-1f74f817cf5c.png)

谢谢作者耐心的回复啊,替换后可以用了!!!感谢感谢

**Comment by xiaosongmao123** [comment]
也感谢你帮我发现BUG

**Comment by GodOfKiller** [comment]
> 也感谢你帮我发现BUG

作者能否在离线任务那一栏,添加一个按照创建时间排序呢?

**Comment by GodOfKiller** [comment]
> 也感谢你帮我发现BUG

![image](https://user-images.githubusercontent.com/44692789/97528536-f1840400-19e8-11eb-8349-4896c291740a.png)
就是这个排序,能看到最近离线的任务进度,感谢作者了!

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97561985-edbda500-1a1b-11eb-8a5d-a9550abcaac1.png)

离线、回收站、网盘内文件夹   都有排序功能啊，

文件大小、创建时间、文件名
正序，倒序

。。。

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97562497-ac79c500-1a1c-11eb-8b26-2fd70189f737.png)

同理，左侧树，顶部路径，都是可以点击的，比如想返回上级文件夹，直接点顶部路径就可以了（点左侧树也行）

**Comment by GodOfKiller** [comment]
> ![无标题](https://user-images.githubusercontent.com/67817756/97561985-edbda500-1a1b-11eb-8a5d-a9550abcaac1.png)
> 
> 离线、回收站、网盘内文件夹 都有排序功能啊，
> 
> 文件大小、上传时间、文件名
> 正序，倒序
> 
> 。。。
> 
> 看截图，当前是按照 上传时间（离线就是指创建离线任务的时间），倒序排序，
> 
> 再点一下“”上传时间“”这几个字就是正序。
> 点一下“”大小“”就是按文件体积倒序、正序
> 点一下“”文件名“”，就是按照文件名称正序、倒序

![image](https://user-images.githubusercontent.com/44692789/97604307-49058c80-1a48-11eb-85d3-da0033ddbdac.png)
![image](https://user-images.githubusercontent.com/44692789/97604339-50c53100-1a48-11eb-947d-b42a3f66c1f4.png)
第一幅图片是我新添加的任务,第二幅图片是按上传时间倒序的,而两个任务是不一样的

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97779003-33ae7080-1bb6-11eb-995a-692042c56857.png)

我这里显示是正确的

你第一张图里，创建时间是2020-10-29，第二张图里时间是2020-10-12
说明是第二张图（小白羊）是按照时间升序排列的，所以可能是排序的图标刷新的错误，我去检查一下有问题的话会在下个版本里修正。你再点一下上传时间，让他重新排一下序就好了
