### ISSUE TITLE
Mac版下载文件暂停后再开始会从头开始下

### ISSUE THREAD

**Issue by williamqdd** [liupan1890/xiaobaiyang2#62]
如题

**Comment by liupan1890** [comment]
可能是有BUG，我去试一下

已知：
1.处于性能考虑，只有2%以上或者实际写入硬盘时才会保存断点进度（有几十兆的内存缓存）
2.本地临时文件（.td）不存在,或未能成功预分配全部文件空间时，无法断点续传

不过感觉肯能就是遇到BUG了，我试试去

**Comment by liupan1890** [comment]
已经确认了，是BUG，win和linux没事，就是mac，我实现了预分配硬盘空间，但mac调用文件信息时返回的是实际写入的体积，并不是预分配的体积，看文件的体积，大小有2个数字（xxxx硬盘上的nnnMB）

总之下个版本会修正此问题

**Comment by liupan1890** [comment]
已修正，已重新上传mac版，重新下载替换即可

**Comment by williamqdd** [comment]
刚刚重新下载了一下， 貌似问题依旧存在

**Comment by liupan1890** [comment]
![macduandian](https://user-images.githubusercontent.com/67817756/103083502-89802180-4617-11eb-86ce-4909e8f20575.gif)


感觉是你没替换成功

尝试，重启电脑，下载解压替换，运行  ---是为了确保替换成功

**Comment by williamqdd** [comment]
已解决， 感谢！！
