### ISSUE TITLE
最新win64版在线播放有问题

### ISSUE THREAD

**Issue by ymg0827965** [liupan1890/xiaobaiyang2#63]
在线播放拖动进度条就闪退

**Comment by liupan1890** [comment]
遇到播放闪退，可以试着切换成其他的播放软件，

设置---播放器文件---选择---（找你自己的播放软件.exe）---保存

这个属于网络或视频文件本身有问题或播放软件BUG，不属于小白羊的BUG，没有办法去修复

**Comment by ymg0827965** [comment]
> 
> 
> 遇到播放闪退，可以试着切换成其他的播放软件，
> 
> 设置---播放器文件---选择---（找你自己的播放软件.exe）---保存
> 
> 这个属于网络或视频文件本身有问题或播放软件BUG，不属于小白羊的BUG，没有办法去修复

不是吧，之前看都好好的，但是现在是所有视频都不行呀，还有就是我没说清楚，只要不拖动进度条就没事，能正常播放，之前的版本不会，我先换播放器试试，谢谢回复

**Comment by liupan1890** [comment]
仅从技术上去理解，当你点击播放时，小白羊解析出一个下载地址(url)，然后把这个地址发给播放器，播放器去播放


所以，只要能成功播放，小白羊的工作就完成了，剩下的全是播放器的事了

像网络缓冲时间长，播放卡顿，闪退，部分文件不能播放，播放速度，字幕大小，音量大小，音轨等等，都是播放器的操作、设置

所以当你遇到托进度闪退，也是托播放器的进度，当然问题出在播放器上

之前没事，现在有事，说明是你现在播放的这个文件本身有问题，可能文件是损坏的，可能文件格式比较特殊播放器不支持


所以，
1. 换个播放器试试
2. 换其他文件试试

只有这2个解决方案，而不是我去修改小白羊就能怎么样了，你说对吧

**Comment by liupan1890** [comment]
另外还有一点，不管用哪个播放器，都是  播放器下载--播放---播放器下载---播放

如果是你播放的文件本身网络速度很慢，比如你是免费会员，比如你看的文件本身速度慢，，那播放器卡顿，闪退，都是正常的，下载不到数据，播放器能怎么办

**Comment by ymg0827965** [comment]
> 
> 
> 另外还有一点，不管用哪个播放器，都是 播放器下载--播放---播放器下载---播放
> 
> 如果是你播放的文件本身网络速度很慢，比如你是免费会员，比如你看的文件本身速度慢，，那播放器卡顿，闪退，都是正常的，下载不到数据，播放器能怎么办

嗯，potplayer没问题。那多半是mpv的问题

**Comment by liupan1890** [comment]
嗯
