### ISSUE TITLE
没有限速的设置吗

### ISSUE THREAD

**Issue by tujidelv** [liupan1890/xiaobaiyang2#65]
我看官方的客户端还有个下载限速的设置啊，能不能加个这样的设置呢，平时有多人使用同一个网络，需要针对某些应用进行限速的

**Comment by liupan1890** [comment]
呃，确实有这样的需求，

你现在可以先通过设置为单文件同时下载，每个文件1线程下载，这样变相的实现限速的目的

后期我研究一下，看能不能实现设置最大下载速度

**Comment by liupan1890** [comment]
我试了一下，限速功能确实太复杂，不搞了

1. 小白羊是每个文件单独计速的，如果要增加限速功能，就要增加全局计速（计算当前全部文件的总的下载速度），限速时又要去考虑限制哪个文件的速度，因为有的文件下载快有的下载速度慢，总之是很乱，不好去规划
2. 大部分情况还是不需要去限速的，限速只是少数情况
3. 多人公用同一网络，最好还是在路由器里去设置每个人的最大速度，现在的路由器都可以非常方便的设置每个人的最大下载速度（登录路由器，找到当前下载速度最快的IP，限速，填一个数，好了）
4. 有很多软件可以实现限速功能（记得比如360网络管家，，这类软件都比较久远了，因为现在很少有人需要用到这类软件了）

总之：太复杂，不搞了

**Comment by Qixingchen** [comment]
360和火绒都有限速功能,如果需要专用软件 也可以考虑 NetLimiter

**Comment by liupan1890** [comment]
你知道的好多。。。。

**Comment by liupan1890** [comment]
本周会更新2.2.3，会增加限速功能，耐心等等看
