### ISSUE TITLE
Mac版当下载到外置硬盘的时候提示F_ALLOCATEALL Fail

### ISSUE THREAD

**Issue by williamqdd** [liupan1890/xiaobaiyang2#66]
<img width="1443" alt="Screen Shot 2020-12-30 at 8 50 29 PM" src="https://user-images.githubusercontent.com/60841319/103352334-ec266100-4ae0-11eb-9eba-df7c16a64d36.png">

**Comment by liupan1890** [comment]
真奇怪，我昨晚还看了一眼，没有issue，怎么这条issue显示15小时以前发布的呢，，，网络问题？

回到问题，提示F_ALLOCATEALL Fail 说明是预分配硬盘空间失败

比如你要下载一个1GB的文件，下载前会现在硬盘上创建此文件.td（空的，但体积是1GB）,下载结束会自动去掉.td后缀，下载成功

问题就是创建这个1GB的文件失败了

但是为什么会失败，这个情况就比较复杂了

1.是否你移动硬盘剩余空间不足？
2.是否你移动硬盘的分区格式是FAT32，而要下载的文件体积大于4GB？
3.是否有写入权限？

我看了你的截图了---看个截图都得挂VPN，这个网络啊。。。

那么小的文件都写入失败，那就不是上面的原因了，可能就单纯的是系统问题了，我没有mac，没有试过往mac的移动硬盘上下载文件，确实是没能预料到会出现此问题，

今晚我会重新上传一份mac版，你下载新版就可以了，解决办法是分配空间出错，忽略掉错误继续下载（会导致断点续传功能失效）

**Comment by liupan1890** [comment]
已更新，重新下载替换即可，新版已测试可以正常下载到外置U盘中

提示一下，据说
> mac把最近打开过的文件缓存放在内存中以便下次加速打开

所以有时候刚刚替换了一遍新文件，重新运行还是旧版，会提示那个错误，
此时需要重启mac，重新替换文件，再运行新版

**Comment by williamqdd** [comment]
已解决， 十分感谢！！！
