### ISSUE TITLE
403错误 Google无果

### ISSUE THREAD

**Issue by mchotdograp** [liupan1890/xiaobaiyang2#67]
![image](https://user-images.githubusercontent.com/48815225/103431636-3eb16b80-4c0e-11eb-85aa-3aed5e92bad3.png)
好几天了 一个都下不了 之前是没问题的

**Comment by liupan1890** [comment]
403错误需要具体的去分析，总之是6盘限制，并不是小白羊的问题。我刚刚去测试了一下，我可以正常的的下载，没有403错误


### 仅针对免费用户，导致403错误的原因
6盘已公告停止免费用户，所以免费用户下载很多文件时

1.文件本身是冷文件，会403错误
----除了一些带颜色的文件，绝大部分文件都属于冷文件，6盘对冷文件分为普通冷文件，存放在大陆，还有特殊冷文件存放在境外，根据6盘官方的公告，现在免费用户仍然可以下载普通冷文件，绝对不能下载境外冷文件（403）

2.免费用户的并发限制
----6盘对免费用户下载时，限制了，同一个域名最多2个连接，如果频繁的超过2个连接，IP或用户ID 会被打入黑名单，显示403.

总之免费用户出现403，**是常规操作，换IP，或者下载其他的文件，尤其注意设置成单文件下载，每文件1个线程下载**


### 针对VIP和免费用户，导致403错误的原因

1.6盘的下载地址本身有时效，一般是超过4小时后失效
----使用小白羊会自动刷新下载地址，所以无视

2.6盘的下载地址里包含了IP限制，如果下载途中，你的IP换了，会显示403错误
----使用小白羊，暂停，重新开始会自动刷新下载地址，可以继续下载

3.6盘官方公告说了是限制用户当日总流量的，如果你当日下载的特别多（1TB？）会被限制，明天再试

### 以上限制仅为我自己推测，不能代表官方，小白羊并不是官方，如果你是VIP用户，且遇到403问题，请直接联系官方客服，找我一点帮助也没有


#### 提示
你只给了一个截图，我也不知道你是为什么403

**Comment by Qixingchen** [comment]
我试过250mbps 下了4天没遇到403，流量限制应该比2TB/天大

**Comment by liupan1890** [comment]
![Uploading 无标题.png…]()

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/103433970-0cffcb00-4c35-11eb-85d3-9aafaea2afe3.png)

**Comment by liupan1890** [comment]
我专门去找阳光电影这个测试了，可以下载哦

流量限制应该比2TB/天大----会员订阅那里写的是1T/天，实际上6盘给的多

**Comment by liupan1890** [comment]
> 我试过250mbps 下了4天没遇到403，流量限制应该比2TB/天大

你的网速挺快的啊。。。。。

**Comment by Qixingchen** [comment]
300m 的网😂

**Comment by mchotdograp** [comment]
晕 根据你的描述 我觉得最有可能是这个：
同一个域名最多2个连接，如果频繁的超过2个连接，IP或用户ID 会被打入黑名单，显示403
我下载的总量也没有到2T。。。看样子只能换id了？

**Comment by Qixingchen** [comment]
下载量是vip 用户的限制，免费用户根本下不到这个量
免费用户的话，你等一天然后再单线程下载吧

**Comment by Qixingchen** [comment]
看了会员购买说明,月费购买的流量是1T/天 年费购买是 3T/天
