### ISSUE TITLE
能加一个每日上传和下载显示的数据吗

### ISSUE THREAD

**Issue by saludossol** [liupan1890/xiaobaiyang2#68]
如题

**Comment by liupan1890** [comment]
你想要哪些数据呢？

今日上传、下载的  流量，文件数，文件夹数？

1.这些统计数据十分的不精准
比如上传，有的文件是秒传的，那么怎么算？是算成0还是算成文件体积？
比如下载，有的时候会失败重试，那是按照成功下载的文件体积算还是按照实际下载流量算？
比如只能计算这一个客户端的数据（比如你复制了好几份小白羊在不同的文件夹，多开）


2.这些统计数据时间上没啥效用
统计数据什么时间清零？比如每日0点清零，那么你在不同的时间去看这个数据，意义不是很大，你也不想每日0点去看一眼当日的总数据吧，所以是不是还需要保存下来每日的数据，最后做日，周，月的数据报表？

如果不做日，周，月的数据报表，只今日的流量数据，你需要吗？我感觉就没啥用了

3.这些数据在哪里显示呢
总是要有一小块地方让数据显示出来的，考虑到每个人的屏幕大小并不可控，需要想象屏幕非常小（800*600像素）的时候，
放在哪里，比如截图，总感觉很挤，并且字不能再多了（只挤下一个总流量，没有总文件数）

![无标题](https://user-images.githubusercontent.com/67817756/103435189-3e34c700-4c46-11eb-92c7-a6dbde33c147.png)



#### 只要确实有用，我一般都会采纳增加对应的功能的，但我没感觉这个数据有啥用，请认真回复我，睡服我

**Comment by saludossol** [comment]
比如可以设计成这样的？
![借鉴](https://user-images.githubusercontent.com/76832306/103454427-ecac3b00-4d1e-11eb-9fa8-963f6722f345.png)

**Comment by saludossol** [comment]
历史流量下可以展开几个选项，今天  7天  30天  全部
统计的数据肯定是按流量来确定数据的

**Comment by saludossol** [comment]
rss订阅是啥，是可以在线观看影视的网站，还是搜集磁力百度云资源这种的网站？

**Comment by saludossol** [comment]
线程数可调节的数量能多开一些吗，下载大文件速度有些慢，只有6Mb/s
同个文件idm能到35Mb/s

**Comment by saludossol** [comment]
还有就是下载过程中点全部删除按键删除不了，得点暂停或者全部暂停才能删除，且删除的光是历史记录，实际的文件并不能删除

**Comment by liupan1890** [comment]
额，我喜欢简单型的，所以所有功能都平铺出来一眼可见，但又不能太多导致拥挤，所以就尽量的去精简功能，让界面符合我的审美（简单，少）

但是这个功能重点不在审美，重点是我感觉这个功能没啥用，这才是重点，想和你探讨的啊。。。
审美那是后期，总能想办法的，但这个功能我觉得没啥用，费尽去折腾一顿，没意思啊


#### 问1.上传流量，有什么作用呢？
你上传，需要先选择要上传的文件夹（考虑到这个功能，必须是连续的，大量的上传才有意义）。那你上传前，在要文件夹上右键属性，就看到了总体积了。操作简单并且谁都会，那么我再统计一遍你的上传流量，作用是什么？

（包括上传成功后，大概一天时间，网盘里的文件夹的体积就显示出来了，网盘的已用总体积也显示正确了，那不管你是看一眼网盘总体积，还是看文件夹体积，你也知道自己上传了多少了）

####同问2.上传的历史（7天1月）有什么作用呢？



#### 问3.下载流量，有什么作用呢？
你下载是把文件下载到你的硬盘上，不管当时下载了多少文件，还有多少文件再等待下载，你直接找到电脑上的下载文件夹，右键属性，不就看到已下载的总体积了？小白羊里统计一遍下载流量，跟这个总体积相差不会很大，也就是几十MB或几百MB的误差而已

####同问4.下载的历史（7天1月）有什么作用呢？



#### 问4：当时总下载速度，有啥作用呢？
我留意到你的截图中有当前总下载速度和总上传速度，那么比如总下载速度有什么意义呢？
首先限制了最多10文件同时下载---实际上推荐5文件以内，，总下载速度其实就是这几个数相加一下，一眼看过去心里就立马有估算了（大概5MB/s  ,大概10MB/s），所以又显示一下具体的总下载速度干啥？

不管当时的总下载速度是多少，其实真正关心的还是每个文件的下载速度对吧？------这个文件怎么没速度?那个文件是满速下载吧？



从技术上去讲，统计数据本身也不准确，包括你看到的下载速度，本身也是非常不精准的，只能大概的一看，比如说你安装一个网速监控软件，再跟小白羊里显示的一个文件的下载速度去比较，误差会很大的。上传速度更是一点都不准，因为上传好多时候都在等待CDN合并文件，创建分片，瞬时速度经常是0000


每个人观念不同，大家互相探讨，我是感觉没啥用

**Comment by liupan1890** [comment]
rss订阅是啥，是可以在线观看影视的网站，还是搜集磁力百度云资源这种的网站？


都有，最近因为找不到工作心态崩了，所以没时间去做程序，本来规划的是挺丰富，以后看时间吧，RSS订阅功能现在并未正式上线

**Comment by liupan1890** [comment]
线程数可调节的数量能多开一些吗，下载大文件速度有些慢，只有6Mb/s
同个文件idm能到35Mb/s

可以的，以前是因为有免费用户，线程多了6盘就500错误，现在6盘关闭免费用户了，以后更新时会放开这里。不过6盘官方客户端也修改为限制并发数很小了，所以调多了可能会遇到6盘的限制，直到有这个事就行

**Comment by liupan1890** [comment]
还有就是下载过程中点全部删除按键删除不了，得点暂停或者全部暂停才能删除，且删除的光是历史记录，实际的文件并不能删除、

1. 小白羊所有操作，都不会涉及到删除用户的文件。删除只是删除下载、上传记录
2. 删除只能删除已停止的任务---就是先暂停，再删除。因为下载中的任务会锁定文件，需要先暂停释放文件引用，再删除任务

**Comment by liupan1890** [comment]
小白羊已全部开源，有能力的话也可以自行修改，符合自己的需求

**Comment by liupan1890** [comment]
因长时间未回复，已关闭此Issue，如有问题请发新的issue
