### ISSUE TITLE
Du盘资源搜索功能是否下线？

### ISSUE THREAD

**Issue by ciddiaz** [liupan1890/xiaobaiyang2#69]
您好，我记得八月份使用的时候，有一个搜索Du盘资源的功能，现在的RSS搜索结果少多了，是否是因为外界压力不得已移除了呢？还是我没找对地方？

**Comment by liupan1890** [comment]
是的

你说的是第一版，已经因为某些原因关闭服务并停止更新了

**Comment by ciddiaz** [comment]
Oh, what a pity
