### ISSUE TITLE
解压后的6盘小白羊版.exe打不开

### ISSUE THREAD

**Issue by MXtremist** [liupan1890/xiaobaiyang2#7]
打开后浏览器跳出http://localhost:2020/%20--with-chrome-plus-plus%20--disable-features=RendererCodeIntegrity,FlashDeprecationWarning
是因为还没正式使用么

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97251240-71239e80-1842-11eb-96d5-e8eb70bcc42b.png)


如果是显示404，就直接删除掉后面的url，只保留http://localhost:2020/   然后回车就好了，就是直接在浏览器打开http://localhost:2020/


如果没显示404，那就是程序BUG了，，

**Comment by MXtremist** [comment]
> ![无标题](https://user-images.githubusercontent.com/67817756/97251240-71239e80-1842-11eb-96d5-e8eb70bcc42b.png)
> 
> 如果是显示404，就直接删除掉后面的url，只保留http://localhost:2020/ 然后回车就好了，就是直接在浏览器打开http://localhost:2020/
> 
> 如果没显示404，那就是程序BUG了，，

删除后面的url就好了，感谢
