### ISSUE TITLE
Arm64 编译相关

### ISSUE THREAD

**Issue by ryukenji3** [liupan1890/xiaobaiyang2#70]
作者你好，

看到之前的讨论 #43 ，依赖浏览器的版本我觉得非常适合丢到arm64上默默挂机下载，尝试编译了下丢到树莓派4上可以正常工作：
`CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags '-s -w --extldflags "-static -fpic"' main.go`

但远程访问时，点击视频文件等操作时会提示没有 electron，我本来想着或许能从你之前提供的旧版安装包里面把electron的依赖拿出来，但旧版安装包被移除了；再来amd64的electron可能arm64不适用。请教下这部份该如何加上？

**Comment by liupan1890** [comment]
哦，是这样，远程操作不支持视频在线预览

概念：安装了6panserver的电脑，称为**远程**
概念：使用浏览器远程管理的电脑，称为**本地**

1.在线预览是调用**远程**上面的播放器软件去播放
你在windows上，**非**远程管理时，点击视频，会调用win上的播放器去播放（本地的播放器）
同理，远程管理时，你在**本地**上，点击视频，理论上是调用**远程**上的播放器去播放，但你看不到播放的界面啊，因为你是远程管理只能看到**本地**上的浏览器，看不到**远程**的桌面

所以远程管理模式下，调用远程电脑上的播放器去播放没有意义，看不到播放界面

2.浏览器不能直接调用本地的软件
所有的浏览器都不支持直接调用本机的播放软件播放（除非你在本地注册了第三方协议等等等等，不讨论），总之就简单理解，出于安全限制，远程管理模式因为是浏览器，无法直接调用本机的播放软件去播放视频

3.electron可以调用本地的软件，但是6盘对IP有限制，无法使用
如果你通过套用electron壳，确实可以强制实现，远程管理模式下，调用本地播放软件播放，但是又遇到了新问题，6盘的下载地址有IP限制，假设你的远程机IP=220.220.220.220，远程管理模式下，你的6盘账号是在远程机上登录的（220.220.220.220），当你点击复制下载链接按钮或者视频预览按钮或者图片预览按钮，都需要先创建一条下载链接（此链接绑定了220.220.220.220），此链接必须用220.220.220.220去访问，否则会返回403.

所以最常见的操作，本机IP=110.110.110.110，，远程管理220.220.220.220，然后点击视频，获取了下载链接，此链接不能在本机下载，不能在本机播放。只能在远程机上下载。。

这个限制就不能突破了，除非在本机重新登录一遍你的6盘账号，并在本机创建下载链接，这个链接才能在本机播放-----你直接在本机安装小白羊不就好了，还远程管理个啥。


综上，远程管理不支持  在线播放，在线预览图片 这两个功能

**Comment by ryukenji3** [comment]
感谢回复，理解作者大大的意思了。关于第三点，我做了这些尝试：
- v2.2.1, macOS 中点击「复制文件下载链接」，将该链接在其他公网IP的电脑中打开可以正常下载；
- v2.2.0,arm64 树莓派上的版本，通过远程管理访问， 点击「复制文件下载链接」该文件也是可以正常在Mac上用IINA播放或直连下载。

**Comment by liupan1890** [comment]
https://download2.99store.cn/ori3Store/**********fz=9hzdvl&ts=c8ajfhr4dblb&i=13.198.12.168&ck=649180a9943eb9eedaba5da5dc7d7802&store=0


难道6盘还区别对待？我也没怎么测试过6盘的IP限制，以前是没有这个限制的，大概自7月左右才有的IP限制，上面是点击  复制下载链接  按钮，复制的下载链接，可以明确地看到&i=13.198.12.168这一段，这是我本机公网IP，复制此地址后我立即使用自己的其他主机（上海阿里云，香港腾讯）都无法下载（403），所以我才说有这个IP限制，另外以前我也测试过，复制链接，IDM下载，到30%，暂停，断网换IP，继续下载---403


当然6盘政策经常变动，可能你的地区不受此限制？

**Comment by liupan1890** [comment]
我去试了一下，确实不限了，6盘不知道什么时候关闭了此限制了，，但是也说不准以后还会不会恢复

**Comment by ryukenji3** [comment]
从我的使用，大概11-12月这段时间似乎是没有IP限制的。另外远程管理，我认为比较合理的应该有两种使用场景：
- 在同一局域网，拥有相同的公网IP，理论上没有IP限制问题；
- 不在同一局域网，通过远程管理访问。这里主要讨论第二种。


首先出于安全和隐私考虑，不管小白羊无UI的服务端是在家里的树莓派还是VPS上，我认为都不应该对公网直接开放管理端口，通过公网IP或域名不能够直接访问。

**通过代理隧道访问是相对前者是更安全合理的方式**。在这种情况下，即使6盘官方日后将「IP限制」再次打开，在电脑或手机端访问小白羊服务端时可以很轻松的加一条代理规则将6盘的连接指定用代理隧道访问，这样访问https://download2.99store.cn 这个链接的仍然是同一个IP地址，我觉得这种情况下视频预览也是合理的，感觉把2.2.0其他版本的 electron 套用一下或许就可以了。

**Comment by ryukenji3** [comment]
功能在逻辑上可行，现在不过手动操作起来麻烦些：通过远程管理访问家里树莓派上的小白羊， 点击「复制文件下载链接」在Mac上用IINA播放，想放啥视频了就得手动复制粘贴点一遍...

**Comment by liupan1890** [comment]
**通过代理隧道访问是相对前者是更安全合理的方式**

1. 这就要增加一堆跟小白羊完全无关的，设置步骤繁琐的，VPS架设代理步骤+本机代理规则设置步骤。
2. 这需要考虑到代理的网速---播放视频本质上也是下载，通过代理可以解决IP限制，但如果本机和远程机之间网速不够足够快，播放会卡
3. 实际使用还是只有局域网内，才远程预览可行
  
  
关于安全方面的考虑：
1. 现在的远程模式端口必须是用户手动指定的，那么除非有人扫描一遍你的全部端口，否则不用有安全方面的顾虑
2. 远程管理需要指定很长的密码，增强了安全性
3. 即使有**任何未考虑到**的漏洞，最坏的结果也只是涉及到网盘内的文件丢失，不会有其他实质损失（谁会把重要文件上传到6盘呢）

所以安全从技术上去分析，是不用去顾虑的  
  
  
实际上远程管理模式，很少有人用，我感觉没有强制上线在线预览的必要，你的动手能力比较强对此没感觉，

1. 对于用到了远程模式的用户，大部分实际上就是挂机下载
2. 想要在线预览就在本机安装小白羊，并重新登录一遍，就可以在线预览了

所以为什么要折腾一遍，强制实现远程管理时的在线预览呢？
注：6盘对账号登录状态有许多限制，所以会登录失效，但6panserver会自动重新登录（这也是为什么推荐用户名+密码、手机+密码登录，不推荐Cookie登录的原因，cookie登录的话，会经常遇到提示：登录状态失效请重新登录）

**Comment by liupan1890** [comment]
是否把2.2.0其他版本的 electron 套用一下或许可以了


1.下载一份2.2.2 win64版（哪个版本都一样，js，不管平台、版本）
2.找到6盘小白羊版win64\electron\resources\app.asar
这个是electron的主代码文件，使用asar解压，得到源代码，找到main.js
`````` javascript
function createWindow() {
......
mainWindow.loadURL("http://localhost:29375",........
}
``````
把http://localhost:29375替换成你实际的远程管理的地址

3.用asar打包源代码，得到新的app.asar
4.把新的app.asar复制回6盘小白羊版win64\electron\resources\，替换旧的

理论上，此时，你执行6盘小白羊版win64\6盘小白羊版.exe 就好了，调用的是远程服务，可以在win上远程预览视频了

仅仅是理论上，因为细节上，以前的代码并没有考虑到会被这样使用，可能有细微的地方需要调整，你先试试吧

**Comment by liupan1890** [comment]
还是推荐，直接在win上重新下载一份小白羊，然后登陆跟远程上同一个账号，直接在线预览，而不是远程预览，简单，无错，可行

**Comment by ryukenji3** [comment]
谢谢回复。

- "用asar打包源代码，得到新的app.asar"
- 看起来目前只能打包成2.2.1以后独立app形式的小白羊了是吗？小

- "还是推荐，直接在win上重新下载一份小白羊，然后登陆跟远程上同一个账号，直接在线预览"
- 谢谢，这样的确是目前最方便的方案了。不折腾的情况下，小白羊arm64版丢在家里下载的功能的确已经够用了。

**Comment by liupan1890** [comment]
小白羊的代码分为3部分
1.UI代码(js)，打包在www.db,（已上传github）
2.server代码(go)，打包成6panserver,（已上传github）
3.electron代码(js)，打包成app.asar

electron代码只有2个文件，也只有简单的显示窗口功能，所以并未上传，但是可以直接通过asar解压，得到源代码
