### ISSUE TITLE
批量移动文件(夹)时文件重复

### ISSUE THREAD

**Issue by ryukenji3** [liupan1890/xiaobaiyang2#71]
环境：v2.2.1 macOS
现象：假设A目录下有20个文件(夹)，均为15GB左右的单个文件，将A目录下所有文件批量移动至与A同级的B目录时：
- A目录中的文件(夹)不会全部移动过去，此时可能剩余3个文件(夹)；
- 再次将剩余的3个文件(夹)全选移动至B时，提示目的端已有该文件(夹)。
- 尝试将剩余3个文件(夹)手动依次移动至B时，其中的2个文件(夹)可以被移动到B，只有一个提示目的端已有该文件。

以上数字仅为假设，可能不精准，但现象是存在的，感觉像是官方服务本身的问题。

**Comment by liupan1890** [comment]
嗯，你说的应该是异步延迟问题


6盘官方的，移动文件夹操作（**改名操作，复制操作，剪切操作**）都可能会异步执行

比如你移动一个文件夹，不管你移动到哪里啊，就看这个文件夹里面有多少个文件，只要文件比较多（没有具体的数字，6盘服务器去判断多不多），就会异步执行，小白羊也会有明确的提示：：

> 由于文件较多，此操作正在异步处理中，请几分钟后再刷新页面查看结果  

所以如果文件夹里面的文件比较多，需要几分钟到十几分钟，才能移动完成。在移动完成之前，会在2个地方都显示这个文件夹。也就是你说的文件没有移动----移动了，只是有2个副本（原地，移动到的位置），只是没有全部移动完成，只移动了文件夹里面的部分文件

这个异步操作，完全不可控，可不可检查---无法检查这个文件夹是否在移动中，
你只能在几秒钟后刷新，或者几分钟后刷新，或者十几分钟后刷新，才会发现文件夹不见了，被移动了


这是因为6盘本身架构设计问题，不是技术问题，除非6盘更改架构，不采用异步操作了，不然就一直是这样。尤其是当你批量移动文件夹时，延迟会更久


所以，当你移动文件夹后，刷新，看到文件夹没有移动时，不要管他，也不要尝试再次移动，因为6盘的服务器正在操作中，耐心等着就好

**Comment by liupan1890** [comment]
遇到异步操作，你可以

方案一：不管他，无视他

方案二：手动点击顶部的刷新按钮，刷新一次，或者间隔刷新好几次

方案三：小白羊会每40s自动刷新一次

总之6盘会后台处理，不知道什么时候就显示正常了

**Comment by ryukenji3** [comment]
收到，谢谢回复。
