### ISSUE TITLE
is:issue is:open 你好，就是可以在返回上一层目录时记住那个打开的文件夹，而不是又跳转到顶部，还有一个就是小建议可以让文件夹默认排序在最前面，这是我使用中发现的可以优化的地方。也不知道大家觉得怎么样呢？0-0

### ISSUE THREAD

**Issue by Hsoraa** [liupan1890/xiaobaiyang2#72]

**Comment by liupan1890** [comment]
#### 让文件夹默认排序在最前面
现在是默认文件名排序，没有区分是文件还是文件夹。如果改为文件夹默认排序在最前面，就不能有现在的按文件名排序功能了，

就是
（1先排序文件夹名，再排序文件名）
（2全部按照文件名排序）
这两个功能只能要一个。

其实我自己用都是按照时间排序的---因为旧文件我都看过了，就基本再也不看了，按照时间降序就是最新离线的文件排在最前面了

我是感觉没啥必要改成先排序文件夹，再排序文件。有啥区别呢？总是要找半天才能找到的
  
  
####就是可以在返回上一层目录时记住那个打开的文件夹，而不是又跳转到顶部
这个我没看明白你的意思
1. 没有返回上一层目录的按钮，所以你是说的顶部路径导航？还是左侧文件夹树？
2. 记住那个打开的文件夹，是什么意思？在哪记住？是在哪里显示吗？
3. 跳转到顶部，呃，你是说左侧文件夹树自动滚动到选中的文件夹吗？

**Comment by liupan1890** [comment]
因长期未回复被关闭，如有问题请发新的issue
