### ISSUE TITLE
是否有使用检查 MD5 等等的方法较验文件的完整性？

### ISSUE THREAD

**Issue by hsa00000** [liupan1890/xiaobaiyang2#74]

**Comment by liupan1890** [comment]
1. 在程序上讲，确实有方法，6盘自己的校验算法
2. 在使用上讲，不好用，所以没有启用
3. 在逻辑上讲一般不会出现数据损坏，也是没有启用的原因


会在下个版本增加启用的设置项，自己选择是否启用



#### 备注一下
校验文件完整性，需要读取一遍你下载的文件，并进行复杂的sha1计算---6盘就是用的这个，不能换其他的
举例子：
你的网速是20MB/s下载了一个6GB的电影，下载大概需要6分钟
1下载完需要校验，也就是从硬盘上重新读取一遍这个文件，（SSD硬盘平均300MB/s，需要读取30秒，机械硬盘平均80MB/s,需要1分钟多，移动硬盘usb2平均30MB/s，需要读取4分钟）
2读取的同时需要计算数据的sha1 ,  6GB数据，普通的笔记本cpu大概需要10-30秒，高级的台式机cpu大概需要5-10秒
最终下载一个文件需要7-10分钟

另外，当你下载多个文件时，会遇到同时写入硬盘和读取硬盘，导致硬盘读写速度减半，最终导致校验时间延长

所以对于大部分人，并不推荐开启校验

**Comment by liupan1890** [comment]
新版已增加
