### ISSUE TITLE
为什么要下载根本目录

### ISSUE THREAD

**Issue by liveskai** [liupan1890/xiaobaiyang2#75]
**为什么要下载根本目录
为什么要下载根本目录
为什么要下载根本目录**

**Comment by liupan1890** [comment]
你好，我没看明白你的问题，请详细描述一下

**Comment by liveskai** [comment]
> 你好，我没看明白你的问题，请详细描述一下

下载文件会下载根本目录的文件夹

**Comment by liupan1890** [comment]
我理解的是，你想说，当你下载文件时，会在你硬盘上按照6盘的目录去保存是吗？
比如：
下载6盘里的/move/test/一秒钟.mp4  
 保存位置是D:\Download\   
最终会得到D:\Download\move\test\一秒钟.mp4   

是这个意思吗？

如果不按照这样保存，你是想最终得到D:\Download\一秒钟.mp4   
我理解的对吗？

**Comment by liupan1890** [comment]
呃，最好说一下，你想要干什么，而不是提问：为什么要下载根本目录
直接说我不想要下载根本目录（我理解的是6盘的根目录），想要保存成xxx，我更好理解

**Comment by mawaya** [comment]
所以能改一下这愚蠢且多餘的储存路径吗

**Comment by liupan1890** [comment]
嗯，可以啊，但是请回复一下，你想要最终实现的方式，我好按照你的想法去改进对吧

举例子：
你的网盘内现在有如下文件，咱们全部下载，下载目录为   D:\Download\    请回复一下你认为合适的最终下载保存路径
``````
/movie/周星驰/大话西游.MKV
/movie/周星驰/百变星君.MKV
/pic/柚木/20100811/0001.jpg
/pic/柚木/20100811/0002.jpg
/pic/柚木/20100811/0003.jpg
/pic/柚木/20100811/0005.jpg
/pic/柚木/20100811/0004.jpg
/数据.txt
``````

**Comment by liupan1890** [comment]
当前最终结果为：
``````
D:\Download\movie\周星驰\大话西游.MKV
D:\Download\movie\周星驰\百变星君.MKV
D:\Download\pic\柚木\20100811\0001.jpg
D:\Download\pic\柚木\20100811\0002.jpg
D:\Download\pic\柚木\20100811\0003.jpg
D:\Download\pic\柚木\20100811\0005.jpg
D:\Download\pic\柚木\20100811\0004.jpg
D:\Download\数据.txt
``````

请回复你想要的结果

**Comment by liveskai** [comment]
> 呃，最好说一下，你想要干什么，而不是提问：为什么要下载根本目录
> 直接说我不想要下载根本目录（我理解的是6盘的根目录），想要保存成xxx，我更好理解

不下载根本目录，不下载6盘的根本目录，就下载文件或文件夹

**Comment by liveskai** [comment]
> 我理解的是，你想说，当你下载文件时，会在你硬盘上按照6盘的目录去保存是吗？
> 比如：
> 下载6盘里的/move/test/一秒钟.mp4
> 保存位置是D:\Download\
> 最终会得到D:\Download\move\test\一秒钟.mp4
> 
> 是这个意思吗？
> 
> 如果不按照这样保存，你是想最终得到D:\Download\一秒钟.mp4
> 我理解的对吗？

是的

**Comment by liupan1890** [comment]
我想我明白了，你是想，最终下载结果是这样：
``````
D:\Download\大话西游.MKV
D:\Download\百变星君.MKV
D:\Download\0001.jpg
D:\Download\0002.jpg
D:\Download\0003.jpg
D:\Download\0005.jpg
D:\Download\0004.jpg
D:\Download\数据.txt
``````

也就是说下载时，去掉全部路径，只按照文件名保存
#### 因为会有重名文件，所以这样，需要在每一次下载时，手动选择一遍下载目录
1. 下载/movie/周星驰/大话西游.MKV，，弹窗，，选择D:\Download\下载
2. 下载pic\柚木\20100811\0001.jpg，，弹窗，，选择D:\Download\下载  

<br><br>
对于大部分人，不喜欢每次下载都要选择下载目录，太麻烦  
所以不采纳

**Comment by liupan1890** [comment]
比如你网盘里有如下文件
``````
/pic/柚木/20100811/0001.jpg
/pic/柚木/20101208/0001.jpg
/pic/柚木/20110101/0001.jpg
``````

在网盘里会有很多重名文件，你也无法记住你本地是否已经有重名文件了，如果不是每次下载时都重新选择下载目录，那就只能自动在文件名上加数字，用来区分了。所以比如你下载了一堆文件，结果是001.jpg  001(1).jpg  001(2).jpg


另外因为有搜索功能，并且可以在搜索结果上多选，点击批量下载
这个时候，那就需要一个文件弹窗一次，让你手动选择下载目录，这就更麻烦了


我没有想到办法实现，点击一次下载按钮，最终得到
``````
/柚木/20100811/0001.jpg
/柚木/20101208/0001.jpg
/柚木/20110101/0001.jpg
``````
  
如果你有方案，可以告诉我，我按照你的思路去实现

**Comment by liupan1890** [comment]
因长期未回复已关闭
