### ISSUE TITLE
超长路径档案的下载位置?

### ISSUE THREAD

**Issue by BlackMickey** [liupan1890/xiaobaiyang2#77]
请问小白羊在下载超长路径档案时，是否会自动将档案放置上一层目录中?
有发现几次这情形，不确定是否为正常的。

例如:
A/B/C/photo.jpg 下载时移动至 A/B/photo.jpg

**Comment by liupan1890** [comment]
是的，
#### 首先系统限制了路径长度
window限制路径最长为255字符（实际上win10之类都支持超长路径，但是程序设计上为了兼容，都是主动限制为最长255）
linux和mac最长限制多少字符我忘了，比win长，所以一般都是按照win的最保守值255去限制
’
#### 然后小白羊下载时，遇到超长路径就会自动截取
截取方式为,比如原路径A/B/C/D/E/F/photo.jpg
1. 截取出上级文件夹路径A/B/C/D/E/photo.jpg，判断是否《255，如果不是继续截取
2. 截取出上级文件夹路径A/B/C/D/photo.jpg，判断是否《255，如果不是继续截取
3. 截取出上级文件夹路径A/B/C/photo.jpg，判断是否《255，如果不是继续截取
最终得到合法路径


#### 这个路径问题我也没有好的解决方案
问题是路径太长，那么太长怎么办？
1.想办法让程序支持长路径
2.主动截取为短路径

因为涉及到多系统(win,linux,mac)，是配上并不满意，所以采用的主动截取方案

如果你有好的解决办法，可以跟我说

直接附上准确的代码
1. go语言，怎么样访问超长路径
2. nodejs怎么样访问超长路径
