### ISSUE TITLE
Windows版本命令行启动无错误提示

### ISSUE THREAD

**Issue by Reapers702** [liupan1890/xiaobaiyang2#78]
**作者在蓝奏云上传的Win64 v2.2.2版本，在命令行使用"6panserver.exe --isremote=true --password=1234"启动不会提示密码过短，log中也没有相应记录，但是我自己编译源码后运行确实有相应提示。**

另外想问一下，有必要非得固定16位那么长的密码吗，我觉得太长挺不方便的。

**Comment by liupan1890** [comment]
#### 我自己编译源码后运行确实有相应提示
xiaobaiyang2/source-6panserver/src/main.go 
`````` golang
func main() {
	flag.Parse()
	fmt.Println("\n6panserver start ", " lancher=", lancher, " isremote=", isremote, " password=", password)
	fmt.Println(utils.ExePath())
	if isremote {
		password = strings.Trim(password, " ")
		if len(password) < 16 {
			fmt.Println("Start Break RemotePassword too short ", password)
			log.Println("Start Break RemotePassword too short ", password)
			return
		}
``````

自己修改此处即可

**Comment by liupan1890** [comment]
如果没有固定16位长度，会有人提建议说不安全，所以才这么长

另外一般都是写个bat文件，以后直接双击bat运行，只需要填写一次密码，长度自然就无所谓了，比如32位长度，也只是复制一遍就好了，以后又不会轻易改

**Comment by liupan1890** [comment]
因长期未回复被关闭，如有问题请发新的issue
