### ISSUE TITLE
新建百度网盘离线下载后一直显示排队中是怎么回事

### ISSUE THREAD

**Issue by hutaoze1** [liupan1890/xiaobaiyang2#79]

**Comment by liupan1890** [comment]
你好
1. 小白羊是第三方，百度网盘显示一直排队，这是6盘的问题，需要咨询6盘的客服（或者发工单）
2. 6盘之前公告过https://0e0e083932c23d0f.kf5.com/hc/kb/article/1444233/


所以要不耐心等者，要不咨询6盘，我也帮不到你啊

**Comment by liupan1890** [comment]
因长期未回复被关闭，如有问题请发新的issue
