### ISSUE TITLE
Linux开启无ui模式，Nginx反代ssl出现拉取rss数据失败

### ISSUE THREAD

**Issue by SkfyZ** [liupan1890/xiaobaiyang2#80]
使用https访问出现rss拉取失败的情况
![Screenshot_20210110-233238](https://user-images.githubusercontent.com/77238265/104127270-24a92300-539c-11eb-8a80-28e3b5778e49.jpg)
但http访问可以正常访问
我预估是密码访问的问题，有没有方法可以使用无密码或者解决rss拉取失败问题的方法。感谢

**Comment by SkfyZ** [comment]
主要是因为我的网站没有备案，所以想使用ssl绕过备案

**Comment by liupan1890** [comment]
你好，

#### 跟远程，密码，都无关。是因为小白羊并未支持https

1.可以自己修改小白羊的代码，配置自己的ssl证书，使小白羊支持https
xiaobaiyang2/source-6panserver/src/localhost/Server.go
``````golang
func ListenServer() {
	port := "localhost:" + Port
	if data.Remote.IsRemote {
		port = ":" + Port
	}
	srv = &http.Server{Addr: port, Handler: &Router{}}
	log.Println("Port:", port)
	println("Port:", port)
//
//在这里增加配置ssl证书的代码
//
	err := srv.ListenAndServe()
``````

具体的go代码，请自行百度，我也没做过，但是非常简单，10行代码搞定，关键是输入正确的，你的证书文件的路径
  
<br>  
<br>  
2.可以自己修改Nginx的设置，通过https访问nginx，nginx转发请求（http）到小白羊
推荐使用这种方式，简单易行
修改nginx.conf
``````nginx
    server {
//增加自己的转发规则
        location / {
            proxy_pass   http://xxx.xxx.xxx.xxx:129375;
            proxy_redirect off;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Original-For $remote_addr;
            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
``````

<br>
<br>
#### 为什么小白羊不支持https？
在golang代码里，如果增加支持https，那么需要设置你的ssl证书完整路径，并配置你的ssl证书。但大部分人没有ssl证书，我也没研究过通用证书或自定义证书，  
主要是https没啥用，很少有人用远程模式，用了远程模式的人也不需要https加密，ui传输的数据不需要加密，因为没有那么重要的数据  
 <br>
 <br> 
#### 主要是因为我的网站没有备案，所以想使用ssl绕过备案
这一句我没理解到你的意思
1.使用ssl绕过备案
这是个伪命题吧？国内的备案是指，如果你不备案，域名不能解析，也不能绑定到你的vps的IP上。  
理论上只要你的vps在国内，是国内IP，不管是http还是https，域名没有备案，就不能通过域名方式去访问  
**只能通过IP的方式去访问**
<br>
 <br> 
<br>
划重点1：比如你有一个阿里云的主机，IP是40.40.40.40，你的域名是xx.baidu.com
域名未备案，只能通过http://40.40.40.40去访问主机上的网站
域名已备案，可以通过http://40.40.40.40去访问主机上的网站，也可以通过http://xx.baidu.com去访问主机上的网站
<br>
<br>
所以你说使用ssl绕过备案是个伪命题
<br>
<br>
划重点2：比如你有一个阿里云的主机，IP是40.40.40.40
当你在主机上运行了小白羊后，直接在手机、电脑的浏览器 输入http://40.40.40.40:端口    就可以了，跟ssl，跟https，跟nginx都没关系啊，就这么简单。。。。。。。。

**Comment by SkfyZ** [comment]
好的谢谢，不过目前可以通过HTTPS来跳过备案

**Comment by SkfyZ** [comment]
主要是因为不经常使用电脑，用手机放问一下然后下个资源就结束了

**Comment by liupan1890** [comment]
嗯，解决办法，最简单的就是上面说的
> 当你在主机上运行了小白羊后，直接在手机、电脑的浏览器 输入http://40.40.40.40:端口 就可以了
直接通过IP，http访问

**Comment by xiaokaixuan** [comment]
@SkfyZ 这个问题是前端的问题，js里写死了后端访问http协议的29375端口，改下就好了。[https://6pan.go-back.cf](https://6pan.go-back.cf)
