### ISSUE TITLE
资源站投稿

### ISSUE THREAD

**Issue by saludossol** [liupan1890/xiaobaiyang2#81]
2021.1.22更新

在线观看无水印网址

1080影视               https://www.k1080.net/

蒙面大侠               https://www.mengmiandaxia.com/

在线之家                https://www.zxzj.me/

素白白                   https://www.subaibai.com/

真不卡影院            https://www.zhenbuka.com/

age动漫                  https://www.agefans.net/  动漫网站/可在线和百度云下载

乌龟影视                https://www.wuguiyy.com/

哔嘀影视               https://bde4.cc/            磁力+在线观看/不支持广告插件

4k鸭奈飞资源站     https://4kya.com/        资源站采集

1090影视                http://1090ys1.com/

秋霞电影                https://www.7xiady.cc/       啥都能看（滑稽.jpg）

9亿看看                  http://www.9ekk.com/

暮光影视                 https://www.muguangys.com/

简影                        https://tv.syrme.top/            页面ui漂亮 

magedn                  https://www.magedn.com/       磁力+在线

555电影                   https://www.o8tv.com/

优质电影网              http://www.youzhidy.com/      影视直链下载+磁力+在线

zzzfun动漫影视          http://www.zzzfun.com/      需验证/动漫在线

奇米直播                    http://www.qimizb.com/       韩国女主播&女团&国内女主播的录播——在线

视频学习

网易公开课                https://open.163.com/                 国内外名校公开课,涉及广泛的学科.（在线观看）

金榜题名                  http://qzbltushu.ys168.com/          考研+各种专业课全部免费/百度云链接

爱课程                   http://www.icourses.cn/home/             教育部主办的高等教育网络课程共享平台（注册账号，在线观看）

百度网盘搜索  
罗马盘                  https://www.luomapan.com/   

影视磁力采集
uump4                 https://www.uump4.net/

bt天堂                  https://www.jsr9.com/

bt迷                       https://www.poxiaody.com/

片库                      https://www.pianku.li/ 或https://www.pianku.me          

acg.rip                  https://acg.rip/1 /动漫（磁力+百度云+种子，部分百度云资源得补充添加pan.baidu.com/s/）   

国内综合搜索磁力

色花堂                https://www.98qewq12bo.xyz/index.php   （在线+磁力+115sha1+百度云+小说你懂的）

搜多多                 https://duo123.xyz:99/

磁力蜘蛛             http://www.eclzz.info/

雨花阁                 https://www.yhg66c.xyz/

BT1207                https://bt1207018.xyz/

磁力柠檬              https://lemon007.xyz/

skrbt                     https://skrbt063.xyz/

吃力网                  https://www.sokankan17.xyz/

老王磁力             https://laowang56.icu/

btfox                   http://btfox8.me/

磁力星球             https://cilixingqiu.com/           内有app下载

磁力湾                 http://www.berrl1.xyz

bt哈哈                  HTTPS：//glz.bthaha.monster或HTTPS：//pue.bthaha.buzz或HTTPS：//bthaha.men

撩人搜索              http://www.lrcili.xyz/          （移动网已屏蔽）

磁力蚂蚁              http://www.eclmy.space/

sbt                        http://sbt510.xyz/

国外综合搜索磁力（国内都可访问，不用注册，免费）

btsow               HTTPS：//btsow.cam 或 HTTPS：//btsow.com

torrent kitty          https://cn.torrentkitty.app/search   或    https://www.torrentkitty.lol      网站自带中文

zoople                https://zooqle.com    界面舒服

anirena            https://www.anirena.com/          动漫磁力

海盗湾             https://piratebayproxy.info         （ 代理站点，内有可访问节点选择）

1337x             https://1337x.is/   （简洁干净）

kickasstorrents     https://kickasss.to    （好奇怪的名字-。-）    

yts                  https://yts.mx        （电影磁力下载网站，分类清晰）

limetorrents             https://www.limetorrents.info/home/     （收集热门种子/磁力 分类清晰）

**Comment by liupan1890** [comment]
感谢投稿，天哪，你推荐的真多，好多网站我都没见过。。。。。

我会在后期认真跟进的！！！！正好春节期间有空，我会在认真整理，并规划出一个合适、简单易用、的订阅方式后上线！！

**Comment by saludossol** [comment]
音乐资源

无损音乐百度贴吧    资源由吧友提供（）百度云资源https://tieba.baidu.com/f?kw=%E6%97%A0%E6%8D%9F%E9%9F%B3%E4%B9%90

**Comment by saludossol** [comment]
安卓破解软件（蓝奏云链接）破解软件有时效性
兜兜线报               https://www.lanzous.com/b133841/
软科技软件           https://www.lanzous.com/b098unlvi
七月软件库         https://www.lanzous.com/b196932
全网软件合计      https://www.lanzous.com/b66477

**Comment by ZZLLT** [comment]
推荐一个音乐网站：http://tool.liumingye.cn/music/
（免费）这个网站用了两三年，还算稳定。
而且重要的事资源非常多，有在线也可以下载。

**Comment by saludossol** [comment]
电子小说

知轩藏书            http://www.zxcs.info/     （线路二直链下载）

**Comment by saludossol** [comment]
学习版游戏资源

gbt小组             http://gbtgame.ys168.com/    日期分类，种子资源

**Comment by cgf801114** [comment]
喜欢这
