### ISSUE TITLE
关于软件上传实现的问题

### ISSUE THREAD

**Issue by Chlesea** [liupan1890/xiaobaiyang2#82]
声明：我啥也不懂，只是来跟开发大大说下
根据6盘相关人员的说法，小白羊版本似乎没有严格按照网宿的文档进行实现，分块大小必须是4MB的整数倍，但小白羊版本是按50M切分的，会造成分片切割失败，进而导致文件可能只会在6盘服务器上存储几个月，然后就丢失了，再也找不回来了。小白羊上传的文件，基本都是损坏的。
问题的核心是：block的大小必须为4MB的倍数。
希望大大能够尽快更新下代码，因为我个人是真的真的真的很喜欢小白羊客户端，不想因为这个问题，从而导致小白羊版不能使用。
感谢大大，祝大大生活愉快，预祝2021年新年快乐！

**Comment by liupan1890** [comment]
可能是有误会，我稍后回去和6盘核对一下，看问题出在哪

xiaobaiyang2/source-6panserver/src/localhost/sixpanupload.go 14行
`````` golang
func MakeUpload(item *DownFileModel) {
	threadcount := int(4)
	info, err := uploader.NewBigUploadInfoAutoBlock(item.DownID, unsafe.Pointer(item), item.DownSavePath, item.Size, item.Hash, 1024*1024*4, threadcount)
``````

已经设置了按照4MB分片，我在编程时已经参阅了网宿的文档，确实要求按4MB倍数，所以我就直接按照4MB去分割了（也可以8MB，12MB，40MB）


稍后我再调试抓包确认一下

**Comment by Chlesea** [comment]
好的呢，辛苦大大了。
给你比个心❤

**Comment by liupan1890** [comment]
我抓包测试了上传一个11MB的文件
``````
https://api.2dland.cn/v3/file/uploadToken  (获取上传token)
https://upload-vod-v1.qiecdn.com/mkblk/4194304/0  (创建第一个4MB分片4194304，同时上传1MB块数据)
https://upload-vod-v1.qiecdn.com/mkblk/4194304/1  (创建第二个4MB分片4194304，同时上传1MB块数据)
https://upload-vod-v1.qiecdn.com/mkblk/3271175/2  (创建第三个分片，因为不足4MB，所以是剩余全部体积3271175，，同时上传1MB块数据)

......多线程，以1MB为缓存，分多次，上传剩余的块数据
https://upload-vod-v1.qiecdn.com/bput/54ebbd5e8bc712d835ac5a7d528e49c2/1048576 (上传1MB块数据)
......

https://upload-vod-v1.qiecdn.com/mkfile/11659783 (最终合并文件)
``````


根据wc的文档，https://wcs.chinanetcenter.com/document/API/FileUpload/SliceUpload
1. mkblk 先创建4MB倍数的块
2. bput  多线程向每个块，上传块数据(缓存大小随意，小白羊是1MB缓存---网宿叫上传片)
3. mkfile 合并文件

#### 1. 我想说我确实是符合网宿的规范去按照4MB分块上传文件的

#### 2. 我想说文件保存丢失问题与分块大小无关
从我理解的逻辑，我上传文件到网宿，最终调用mkfile合并文件，此时这个文件就已经完整的保存到网宿了，
  
然后6盘会从网宿复制这个文件到6盘的后端存储服务器，最终保存。那么，文件丢失与否 和 文件分块大小逻辑上完全无关
  
如果我上传代码不规范，则最终调用mkfile合并文件会失败，此时会提示文件上传失败，不会保存到网宿，也不会继续执行最终的保存到6盘
  
注意不是我分析他会失败，不按照4MB倍数分块，最后调用mkfile合并文件时，网宿会返回错误信息，合并失败。

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/104318532-82fc1000-551a-11eb-9241-34ce54806f5d.png)

**Comment by Chlesea** [comment]
6盘相关人员让我跟大大说下，他们已经转给网宿了

**Comment by liupan1890** [comment]
你是怎么跟他们沟通的？我想直接和他们去沟通，告诉我联系方式吧

**Comment by liupan1890** [comment]
上传这个是个严重的BUG，如果确实因为小白羊导致，那我必须立即修正此BUG才行

**Comment by Chlesea** [comment]
6盘相关人员QQ：54379063

**Comment by liupan1890** [comment]
嗯，我去加他

**Comment by Chlesea** [comment]
辛苦大大！

**Comment by Chlesea** [comment]
辛苦大大！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liupan1890"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上9:30
收件人: "liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;; 
抄送: "殇璃"<1556792948@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liupan1890/xiaobaiyang2] 关于软件上传实现的问题 (#82)





 
嗯，我去加他

**Comment by kk54250** [comment]
作者您好，请问小白羊上传的问题解决了吗

**Comment by liupan1890** [comment]
嗯
