### ISSUE TITLE
强烈建议出linux-cli版

### ISSUE THREAD

**Issue by cgkings** [liupan1890/xiaobaiyang2#83]
官方出的6pan-cli功能有bug，强烈建议小白杨出个cli版，这样我就可以写脚本，根据下载list，批量换号离线，然后再批量下载到gd挂载盘了

**Comment by liupan1890** [comment]
抱歉，我没有开发cli版本的打算，是因为架构原因

小白羊大部分涉及到6盘的功能，现在都是js，只有上传下载是golang
cli跨平台要求大部分功能都用golang，js无法直接跨平台运行---需要安装nodejs


所以从架构上，小白羊并不支持cli的，这是硬伤，除非重写小白羊70%的代码，不然无法实现

**Comment by cgkings** [comment]
那有接口，可以读取下载任务列表，比如说2W个磁力链，定时任务，每天每个账号自动读取100个离线？

**Comment by liupan1890** [comment]
如果确实想要，可以自己翻一下代码，模拟http调用即可，并没有cli的接口，都是http接口

1.提交磁力任务
xiaobaiyang2/source-www/src/api/offline.ts 

2.列出当前下载中队列，开始、暂停任务
xiaobaiyang2/source-www/src/api/down.ts

3.创建下载任务
xiaobaiyang2/source-www/src/api/file.ts

**Comment by liupan1890** [comment]
如果你熟悉js的话，可以直接自己修改代码，实现自动提交任务（自动读取100离线），自动查询任务进度，配合开启下载完调用sh功能（或者直接自己写js的方法），下载完自动复制文件到GD。都是比较容易的，因为代码是开源的并且行数并不多

但如果你不熟悉js，那就只能分析http调用的接口数据，模拟，直接调用6panserver，也能实现大部分功能

**Comment by yudf56** [comment]
6盘小绵羊不能下载百度云的文件吗？为什么提交离线了，文件一直排队中，一点也没动啊
