### ISSUE TITLE
为什么bdy离线下载一直排队中？

### ISSUE THREAD

**Issue by yudf56** [liupan1890/xiaobaiyang2#84]
为什么bdy离线下载一直排队中？是有啥教程吗？

**Comment by liupan1890** [comment]
你好
小白羊只是第三方UI，百度离线是6盘的功能，为什么一直排队需要咨询6盘官方客服，我也不知道的

**Comment by yudf56** [comment]
请问bdy里资源到底是咋下载的啊？不是新建离线下载吗？为什么提交离线之后就一直排队啊？

**Comment by yudf56** [comment]
6盘官方客服是在哪啊？

**Comment by yudf56** [comment]
好的，谢谢

**Comment by Qixingchen** [comment]
登入 https://2dland.cn/ 然后提交工单  
不过公告说了百度下载已经停用了  
https://0e0e083932c23d0f.kf5.com/hc/kb/article/1444233/

**Comment by liupan1890** [comment]
确实就是，新建离线下载（粘贴百度分享链接即可）

但为什么一直在排队，这需要问一下6盘了啊

**Comment by yudf56** [comment]
好嘞好嘞，谢谢
