### ISSUE TITLE
windows系统无法登录BAI度账户

### ISSUE THREAD

**Issue by GWONG23** [liupan1890/xiaobaiyang2#85]
输入账户提示登录失败  无法登陆账户

**Comment by liupan1890** [comment]
你好，小白羊是6盘的美化版UI，需要配合6盘的账号使用，并不能登录百度账号。另外6盘最近也公告暂停百度网盘链接下载功能了

**Comment by liupan1890** [comment]
6盘网址  https://2dland.cn/

公告https://0e0e083932c23d0f.kf5.com/hc/kb/article/1444233/

**Comment by GWONG23** [comment]
好的&nbsp; 我了解啦 非常感谢 谢谢！祝好！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liupan1890/xiaobaiyang2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 晚上8:37
收件人:&nbsp;"liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;;
抄送:&nbsp;"我。"<2022296769@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liupan1890/xiaobaiyang2] windows系统无法登录BAI度账户 (#85)





 
6盘网址  https://2dland.cn/
 
公告https://0e0e083932c23d0f.kf5.com/hc/kb/article/1444233/
