### ISSUE TITLE
离线文件提示，订阅会员专用功能，在哪可以订阅？

### ISSUE THREAD

**Issue by f863210992** [liupan1890/xiaobaiyang2#86]
![QQ截图20210114221241](https://user-images.githubusercontent.com/74488724/104601805-a27b7000-56b5-11eb-9c2e-631806582fe2.jpg)

**Comment by Qixingchen** [comment]
https://2dland.cn/

**Comment by Qixingchen** [comment]
另请注意,目前百度网盘下载功能是下线状态

**Comment by f863210992** [comment]
> 另请注意，目前百度网盘下载功能是下线状态

收到，是需要开通6盘的官方会员才可以用是吧？

**Comment by Qixingchen** [comment]
根据其他 issue 回馈,现在会员的百度网盘下载并不能正常工作

#84
