### ISSUE TITLE
离线任务最大显示数量

### ISSUE THREAD

**Issue by BlackMickey** [liupan1890/xiaobaiyang2#88]
离线任务最大显示数量
离线任务 > 文件名 (0/1998个)
此处最大仅能显示1998个。

此外，是否考虑添加分页选项(每页100~200个种子之类的)?

**Comment by liupan1890** [comment]
你好

1.离线最多显示1998
是的，6盘分页要求最多一页显示999，小白羊最多会拉取2页，也就是最多显示1998条。因为显示页数多了刷新就比较慢

2.是否考虑添加分页选项(每页100~200个种子之类的)?
没有考虑过分页功能，我是这么想的啊：
6盘一天只能提交100条，1998也就是最近20天每天都提交100条。那么20天以前的离线任务列表有什么用呢？我是想不到20天以前的（甚至是30天以前的）任务有什么作用，注意只是任务信息，文件是离线到你的网盘里的，跟信息无关
  
  
当然我考虑的肯定是大部分人的情况，恰好你需要用到20天以前的任务列表，可以直接登录6盘官方网页版，就能看到啦---肯定也不是每时每刻都需要看20天以前的任务列表，偶尔才需要用到，登一下6盘也不麻烦

  

为什么不上翻页？
因为我比较懒，不喜欢那种点一下翻页，或者滚顶到底部等待它自动加载翻页，我就喜欢一点一次就全部列出来这样的操作，一次就看到了2000条，习惯这样啦

**Comment by BlackMickey** [comment]
好的，感谢你的回覆。
我使用离线的用量很大，每天会用完100条，至今累积超过4000条，目前离线成功的种子不到150个，有大量尚未离线完成的种子(许多种子年龄超过5年以上)，所以才会碰到这状况，不过离线2周都无法成功的种子大概可以视为断种了，其实也可以从任务中移除了。
