### ISSUE TITLE
第二版下載一段時間後會出現讀取任務列表出錯

### ISSUE THREAD

**Issue by waya1s** [liupan1890/xiaobaiyang2#89]
我用第二版下載檔案過一段時間會就無法下載還會跳出讀取任務列表出錯，選網盤會出現拉取文件夾內文件列表出錯。我使用第一版沒有問題。請問是要怎麼弄阿?
![螢幕截圖 2021-01-15 15 34 47](https://user-images.githubusercontent.com/21374616/104702127-8678dc80-5750-11eb-94f2-74bc649cae2d.png)

**Comment by liupan1890** [comment]
你好

出现  读取任务列表，一般是因为6panserver.exe崩溃了，可能是发生了未知的错误，请帮我看一下你的日志文件

6盘小白羊版win64\electron\resources\AppData\debug.log

请把这个文件的内容贴给我看

**Comment by waya1s** [comment]
2020/12/15 13:48:23 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/15 13:48:25 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\6盘小白羊版win64\electron\resources\AppData

2020/12/15 13:48:25 main.go:105: all userdata loaded

2020/12/15 13:48:25 Server.go:36: Port: localhost:29375

2020/12/15 13:49:15 Server.go:53: Shutting down server:  interrupt

2020/12/15 13:49:15 main.go:121: 6panserver exit

2020/12/15 13:49:34 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/15 13:49:37 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\6盘小白羊版win64\electron\resources\AppData

2020/12/15 13:49:37 main.go:105: all userdata loaded

2020/12/15 13:49:37 Server.go:36: Port: localhost:29375

2020/12/15 14:52:23 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/15 14:52:25 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/15 14:52:25 main.go:105: all userdata loaded

2020/12/15 14:52:25 Server.go:36: Port: localhost:29375

2020/12/15 15:51:28 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/15 15:51:30 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/15 15:51:30 main.go:105: all userdata loaded

2020/12/15 15:51:30 Server.go:36: Port: localhost:29375

2020/12/15 15:54:08 Server.go:53: Shutting down server:  interrupt

2020/12/15 15:54:09 main.go:121: 6panserver exit

2020/12/22 11:17:16 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/22 11:17:19 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/22 11:17:20 main.go:105: all userdata loaded

2020/12/22 11:17:20 Server.go:36: Port: localhost:29375

2020/12/22 11:18:38 Server.go:53: Shutting down server:  interrupt

2020/12/22 11:18:39 main.go:121: 6panserver exit

2020/12/22 11:18:55 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/22 11:18:57 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/22 11:18:57 main.go:105: all userdata loaded

2020/12/22 11:18:57 Server.go:36: Port: localhost:29375

2020/12/22 15:18:27 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/22 15:18:30 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/22 15:18:30 main.go:105: all userdata loaded

2020/12/22 15:18:30 Server.go:36: Port: localhost:29375

2020/12/23 07:56:00 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/23 07:56:02 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/23 07:56:02 main.go:105: all userdata loaded

2020/12/23 07:56:02 Server.go:36: Port: localhost:29375

2020/12/23 08:00:20 Server.go:53: Shutting down server:  interrupt

2020/12/23 08:00:20 main.go:121: 6panserver exit

2020/12/23 08:00:50 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/23 08:00:52 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/23 08:00:52 main.go:105: all userdata loaded

2020/12/23 08:00:52 Server.go:36: Port: localhost:29375

2020/12/23 09:10:34 Server.go:53: Shutting down server:  interrupt

2020/12/23 09:10:34 main.go:121: 6panserver exit

2020/12/24 08:50:20 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/24 08:50:22 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/24 08:50:22 main.go:105: all userdata loaded

2020/12/24 08:50:22 Server.go:36: Port: localhost:29375

2020/12/24 11:58:28 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/24 11:58:30 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/24 11:58:30 main.go:105: all userdata loaded

2020/12/24 11:58:30 Server.go:36: Port: localhost:29375

2020/12/25 08:27:10 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 08:27:12 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 08:27:12 main.go:105: all userdata loaded

2020/12/25 08:27:12 Server.go:36: Port: localhost:29375

2020/12/25 08:57:32 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 08:57:35 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 08:57:35 main.go:105: all userdata loaded

2020/12/25 08:57:35 Server.go:36: Port: localhost:29375

2020/12/25 10:44:47 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 10:44:50 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 10:44:50 main.go:105: all userdata loaded

2020/12/25 10:44:50 Server.go:36: Port: localhost:29375

2020/12/25 11:28:10 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 11:28:13 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 11:28:13 main.go:105: all userdata loaded

2020/12/25 11:28:13 Server.go:36: Port: localhost:29375

2020/12/25 13:31:24 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 13:31:27 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 13:31:27 main.go:105: all userdata loaded

2020/12/25 13:31:27 Server.go:36: Port: localhost:29375

2020/12/25 15:17:49 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 15:17:51 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 15:17:51 main.go:105: all userdata loaded

2020/12/25 15:17:51 Server.go:36: Port: localhost:29375

2020/12/25 17:31:40 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 17:31:43 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 17:31:43 main.go:105: all userdata loaded

2020/12/25 17:31:43 Server.go:36: Port: localhost:29375

2020/12/25 17:47:45 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 17:47:48 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 17:47:48 main.go:105: all userdata loaded

2020/12/25 17:47:48 Server.go:36: Port: localhost:29375

2020/12/25 19:21:17 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 19:21:20 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 19:21:20 main.go:105: all userdata loaded

2020/12/25 19:21:20 Server.go:36: Port: localhost:29375

2020/12/25 20:31:43 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/25 20:31:45 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/25 20:31:45 main.go:105: all userdata loaded

2020/12/25 20:31:45 Server.go:36: Port: localhost:29375

2020/12/26 19:59:28 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/26 19:59:30 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/26 19:59:30 main.go:105: all userdata loaded

2020/12/26 19:59:30 Server.go:36: Port: localhost:29375

2020/12/27 09:13:42 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/27 09:13:44 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/27 09:13:44 main.go:105: all userdata loaded

2020/12/27 09:13:44 Server.go:36: Port: localhost:29375

2020/12/27 09:48:12 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/27 09:48:14 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/27 09:48:14 main.go:105: all userdata loaded

2020/12/27 09:48:14 Server.go:36: Port: localhost:29375

2020/12/27 17:10:49 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/27 17:10:52 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/27 17:10:52 main.go:105: all userdata loaded

2020/12/27 17:10:52 Server.go:36: Port: localhost:29375

2020/12/27 19:14:39 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/27 19:14:41 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/27 19:14:41 main.go:105: all userdata loaded

2020/12/27 19:14:41 Server.go:36: Port: localhost:29375

2020/12/28 08:40:16 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2020/12/28 08:40:19 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2020/12/28 08:40:19 main.go:105: all userdata loaded

2020/12/28 08:40:19 Server.go:36: Port: localhost:29375

2020/12/28 08:45:05 Server.go:53: Shutting down server:  interrupt

2020/12/28 08:45:05 main.go:121: 6panserver exit

2021/01/14 07:51:42 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 07:51:45 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 07:51:46 main.go:105: all userdata loaded

2021/01/14 07:51:46 Server.go:36: Port: localhost:29375

2021/01/14 08:20:06 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 08:20:08 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 08:20:09 main.go:105: all userdata loaded

2021/01/14 08:20:09 Server.go:36: Port: localhost:29375

2021/01/14 08:36:55 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 08:36:57 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 08:36:57 main.go:105: all userdata loaded

2021/01/14 08:36:57 Server.go:36: Port: localhost:29375

2021/01/14 10:39:38 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 10:39:41 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 10:39:41 main.go:105: all userdata loaded

2021/01/14 10:39:41 Server.go:36: Port: localhost:29375

2021/01/14 10:42:39 Server.go:53: Shutting down server:  interrupt

2021/01/14 10:42:40 main.go:121: 6panserver exit

2021/01/14 10:42:56 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 10:42:58 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 10:42:58 main.go:105: all userdata loaded

2021/01/14 10:42:58 Server.go:36: Port: localhost:29375

2021/01/14 11:58:29 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 11:58:32 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 11:58:32 main.go:105: all userdata loaded

2021/01/14 11:58:32 Server.go:36: Port: localhost:29375

2021/01/14 13:27:15 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 13:27:17 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 13:27:17 main.go:105: all userdata loaded

2021/01/14 13:27:17 Server.go:36: Port: localhost:29375

2021/01/14 17:01:25 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/14 17:01:27 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/14 17:01:27 main.go:105: all userdata loaded

2021/01/14 17:01:27 Server.go:36: Port: localhost:29375

2021/01/15 07:54:36 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/15 07:54:39 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/15 07:54:39 main.go:105: all userdata loaded

2021/01/15 07:54:39 Server.go:36: Port: localhost:29375

2021/01/15 09:23:03 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/15 09:23:05 DBHelper.go:22: Start Path C:\Users\User\Downloads\新增資料夾\6盘小白羊版win64\electron\resources\AppData

2021/01/15 09:23:05 main.go:105: all userdata loaded

2021/01/15 09:23:05 Server.go:36: Port: localhost:29375

2021/01/15 15:42:25 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/15 15:42:27 DBHelper.go:22: Start Path C:\Users\User\Downloads\1\win64\electron\resources\AppData

2021/01/15 15:42:27 main.go:105: all userdata loaded

2021/01/15 15:42:27 Server.go:36: Port: localhost:29375

2021/01/15 16:20:27 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/15 16:20:29 DBHelper.go:22: Start Path C:\Users\User\Downloads\1\win64\electron\resources\AppData

2021/01/15 16:20:29 main.go:105: all userdata loaded

2021/01/15 16:20:29 Server.go:36: Port: localhost:29375

2021/01/15 16:29:37 Server.go:53: Shutting down server:  interrupt

2021/01/15 16:29:40 main.go:121: 6panserver exit

2021/01/15 16:29:47 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/15 16:29:49 DBHelper.go:22: Start Path C:\Users\User\Downloads\1\win64\electron\resources\AppData

2021/01/15 16:29:49 main.go:105: all userdata loaded

2021/01/15 16:29:49 Server.go:36: Port: localhost:29375

2021/01/15 20:27:04 main.go:74: 
6panserver start   lancher= electron  isremote= false  password= 

2021/01/15 20:27:06 DBHelper.go:22: Start Path C:\Users\User\Downloads\1\win64\electron\resources\AppData

2021/01/15 20:27:06 main.go:105: all userdata loaded

2021/01/15 20:27:06 Server.go:36: Port: localhost:29375

麻煩了

**Comment by liupan1890** [comment]
可惜的是，我在日志里也没找到有用的错误信息（应该是还没来得及记录日志就崩溃了）

**第一问：**请问，你提到，下載檔案過一段時間會就無法下載還會跳出讀取任務列表出錯
  
这个时候，是不是一定要重新启动小白羊，才能继续下载？不能自动恢复正常，必须手动双击重新打开小白羊，才能继续下载对吧？
  
**第二问：**你的6盘账号是VIP账号吗？还是免费账号？
  
**第三问：**什么时候开始的？是很早就这样了，还是最近2天突然这样以前都是正常的？
   
**第四问：**是否是在下载某个文件才会出错？还是不论下载什么文件，都会出错？
   
**第五问：**你的下载速度平均是多少？出错的频率多吗？是经常出错还是偶尔出错还可以勉强用？
    
因为是未知的BUG，我也没遇到过这种情况，无法有效的去分析，所以只能多问问你了解一下  ，谢谢

**Comment by waya1s** [comment]
**第一问：**请问，你提到，下載檔案過一段時間會就無法下載還會跳出讀取任務列表出錯

这个时候，是不是一定要重新启动小白羊，才能继续下载？不能自动恢复正常，必须手动双击重新打开小白羊，才能继续下载对吧？

對一定要關掉現有的重新啟動小白羊才能繼續下載

**第二问：**你的6盘账号是VIP账号吗？还是免费账号？

免費賬號

**第三问：**什么时候开始的？是很早就这样了，还是最近2天突然这样以前都是正常的？

改用第二版就這樣了。

**第四问：**是否是在下载某个文件才会出错？还是不论下载什么文件，都会出错？

我都是下載影片都這樣

**第五问：**你的下载速度平均是多少？出错的频率多吗？是经常出错还是偶尔出错还可以勉强用？

下載數度有時200多K有時80多K，差不多下載2~3個檔案就要重新啟動一次，差不多30~40分鐘重新啟動一次。

因为是未知的BUG，我也没遇到过这种情况，无法有效的去分析，所以只能多问问你了解一下 ，谢谢

**Comment by liupan1890** [comment]
對一定要關掉現有的重新啟動小白羊才能繼續下載---证实了，就是6panserver进程崩溃了
  
但我还没找到为什么崩溃，未知的BUG
  
免費賬號--可能与导致崩溃的BUG有关系

因为6盘自公告关闭免费用户以后，对免费用的限制非常多，对免费用户的请求返回的数据并不符合预期（举个例子，有部分文件6盘对VIP账号，下载时支持断点续传，对免费账号不支持断点续传，对VIP账号允许多线程同时下载，对免费账号不允许，有部分文件对免费账号直接就禁止下载了）

  
我下个版本会针对此问题，将下载引擎更换为更加成熟稳定的aria，这样就能避免自动崩溃的情况了，现在因为我没能准确的找到BUG在哪，无能为力了，抱歉，等我发布下个版本啊

**Comment by waya1s** [comment]
好的再麻煩了感謝。

**Comment by liupan1890** [comment]
此BUG已经在v2.2.3修正，关闭issue
