### ISSUE TITLE
第二版没有第一版下载速度快

### ISSUE THREAD

**Issue by malou9** [liupan1890/xiaobaiyang2#9]
同一台电脑，同一个资源，同一个网络测试发现第二版的下载速度没有第一版快，是不是换了下载引擎的缘故？还是优化得不够好？

**Comment by xiaosongmao123** [comment]
规则确实改了

第一版是20MB一个分片，5线程同时下载。但是6盘有一段时间针对调整了限制，会出现下载一段时间后断流或限速的情况

第二版因此改成了根据文件体积智能分段且最多不超过4线程下载---主要是20MB-50MB的小文件受影响比较大，100MB以上差别不大


我自己测试每次都是跑满速（VIP），30MB/s 很少出现不能满速的时候，所以没感觉到慢。这个也是没办法，因为6盘限速一直在调整。但是第一版只有一个文件下载，第二版最多可以4个文件下载，如果出现4个文件总速度还不满速，那不是下早引擎的问题，纯粹是网络、文件、线路、时间的问题。

免费用户我没怎么测试过，肯定会被限速的

**Comment by malou9** [comment]
我也是VIP，我是用1-2G的文件下载测试的，那我再继续测试看看。还有，做成网页版的，关掉网页似乎没有在后台下载了，然后我再打开续传，就出错了。其实我想大多数用户还是喜欢像第一版那样软件的形式吧。

**Comment by liupan1890** [comment]
关掉网页似乎没有在后台下载了，然后我再打开续传，就出错了


1. 关掉网页会继续下载，网页只是UI显示，真正下载是6panserver.exe在下载，只要你没点击任务栏里6盘图标的退出按钮，就会一直后台运行（下载）

2. 出的什么错？告诉我错误信息，我看是否是程序的BUG

3. 3文件同时下载能满速吗？

**Comment by liupan1890** [comment]
![无标题](https://user-images.githubusercontent.com/67817756/97658425-3d957e00-1aa7-11eb-965e-2d9a81cdc204.png)

**Comment by liupan1890** [comment]
我有测试了一下，在我电脑上同时下载同一个6GB的视频。第一版和第二版，速度都是不太稳定，有快有慢。但最终下载用时，只相差了约1分钟，因为两个程序同时下载对网速是竞争关系，总下载时间相差一分钟也是合理的

另外我倒是注意到一点，就是第二版，4个文件同时下载，有一个文件10MB-16MB/s，剩下3个文件只有1-2MB/s，有时候确实达不到我宽带的满速（30MB/s），CPU占用率一直很低（1%-2%），所以下载速度我分析还是纯粹的属于网络，因为网络每秒都在变的，这个cpu占用，也确实没有啥优化空间了，单文件多线程确实会快一点，但6盘限制经常调整，我还是愿意把线程设置的少一点，

**Comment by malou9** [comment]
你提的3个问题我测试后再回答你。

现在发现2个小BUG
1、公告不能跟随官网实时更新，官网已经发了新公告，第二版还是显示旧公告。
2、第二版正在下载中里面删除了文件，本机的文件未被删除，是不是网页版只是个UI的原因，只是删除了记录，实际文件是操作不了的？而第一版点删除，本机的文件也跟着删除了。

**Comment by malou9** [comment]
![QQ图片20201030232947](https://user-images.githubusercontent.com/62864035/97724493-f390b480-1b07-11eb-83c0-7f5f8e7a2aa0.png)
下载中关闭UI界面，再冲右下角打开UI，显示出错。也就是我前面提到的续传出错问题

**Comment by liupan1890** [comment]
嗯，
1. 公告，6盘官方是把公告写死在网页的js里，因为我还没上线服务器，所以现在公告是我手动跟随更新的，我现在去更新一下

2. 删除按钮的提示是“”删除记录“”，并不是删除文件，仅仅是删除下载记录。文件需要用户手动管理，并不是不能删除文件，是故意设计成这样的

第一版我记得也是不会删除文件的啊？可能我记错了，时间久了，总之应该都是不删除文件才对，

这是因为有个“”删除全部按钮“”，如果你一点，全部文件都被删除掉了，那不合理吧（会有人误点）

一般大家下载的比较多，就会有一堆下载记录，那肯定不喜欢一条一条的删除（尤其是下载电视剧有几十集），删除全部这个按钮就是清空下载记录用的，删除按钮是删除一条记录用的

**Comment by liupan1890** [comment]
再说报错这个截图，我看了看，错误提示是api.6pan.cn这个域名无法解析,一般出现在断网，并不是域名真的不能解析了，是你本机临时断网了，导致不能解析。

这个断网可能是比如你关机休眠，那开机后的1-2秒就是断网状态（之后网络就恢复了），错误信息的显示时间是6秒。


断网会导致下载失败，所以你会遇到最开始说的，关了UI，下载就停止了，这个可以理解

但关了UI就会断网这个我还没想到是为什么，是不是你开了代理？或者你关闭wifi了？单纯从程序上，我没想到哪里能导致断网，没有这个功能的，我再想想

**Comment by malou9** [comment]
第二版离线百度网盘的密码在哪输入？
![QQ图片20201031234523](https://user-images.githubusercontent.com/62864035/97783494-2a7fcc80-1bd3-11eb-819c-efb51b09fee2.png)

**Comment by liupan1890** [comment]
当你粘贴进去标准的百度链接时，就显示提取码输入框了

**Comment by malou9** [comment]
我发现了，只识别原始的https://pan.baidu.com/s/XXXXXXXXX  这样的链接，如果是已经打开了的，变成了输入密码入口的链接，例如https://pan.baidu.com/share/init?surl=XXXXXX  这样的就识别不了。建议增加识别百度盘2种形式的网址或者在“最近保存位置”旁边增加一个输入密码的框框。

**Comment by liupan1890** [comment]
嗯，我下个版本会修正识别https://pan.baidu.com/share/init?surl=XXXXXX这样的
