### ISSUE TITLE
下载中的单个文件删除后，下载的临时数据不会自动删除

### ISSUE THREAD

**Issue by yangziqin** [liupan1890/xiaobaiyang2#90]

**Comment by liupan1890** [comment]
嗯，是的，当前版本，并不会涉及到任何删除文件操作，需要用户手动删除文件（包括未下载的临时文件）

因为删除操作，本身比较危险，不敢自动删除，要求用户手动删除

下个版本会考虑支持自动清理临时文件

**Comment by yangziqin** [comment]
在线预览视频图片，是直接缓存在内存里吗？我看了一下在线看视频并没有磁盘写入

**Comment by yangziqin** [comment]
在线预览视频图片，是直接缓存在内存里吗？我看了一下在线看视频并没有磁盘写入




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liupan1890/xiaobaiyang2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 下午4:06
收件人:&nbsp;"liupan1890/xiaobaiyang2"<xiaobaiyang2@noreply.github.com&gt;;
抄送:&nbsp;"野蛮小怪兽"<3065095106@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liupan1890/xiaobaiyang2] 下载中的单个文件删除后，下载的临时数据不会自动删除 (#90)





 
嗯，是的，当前版本，并不会涉及到任何删除文件操作，需要用户手动删除文件（包括未下载的临时文件）
 
因为删除操作，本身比较危险，不敢自动删除，要求用户手动删除
 
下个版本会考虑支持自动清理临时文件

**Comment by liupan1890** [comment]
1. 在线预览图片

是浏览器正常在线显示图片，所以理论上是缓存到浏览器（electron）的缓存里，浏览器自动管理缓存

2.在线预览txt
是直接缓存在6panserver的进程内存里，自动管理缓存

3.在线预览视频
默认是调用mpv播放器在线预览，则数据缓存在mpv播放器的进程内存里。如果你设置为其他的播放软件，则数据缓存在其他播放器的进程内存里（也能能会缓存到系统临时文件夹，具体看播放器的实现）

4.在线预览pdf,word,xls,ppt等
是直接浏览器打开在线预览，数据缓存在浏览器的缓存里

**Comment by liupan1890** [comment]
此BUG已经在v2.2.3修正，关闭issue
