### ISSUE TITLE
图标变成X除了六盘自己的LOGO

### ISSUE THREAD

**Issue by fallenveda** [liupan1890/xiaobaiyang2#91]
如题，请问这个原因是字体或者使用Mactray渲染造成的么？自己热替换了SimSun，NSimSun，MS Serif这三个字体。如果不是的话，麻烦有空可以帮我查看下原因，谢谢。

**Comment by liupan1890** [comment]
你好，能否截个图呢？我没能很好的理解你的意思

**Comment by fallenveda** [comment]
> 你好，能否截个图呢？我没能很好的理解你的意思
> 
> 图标是指哪里的图标？文件图标？界面所有图标？还是截个图我就看明白了

![批注 2021-01-18 084707](https://user-images.githubusercontent.com/77566655/104861347-6c1a4b00-596a-11eb-9026-6c19485f08b3.jpg)

第一次用github，之前想附图在对话框顶部没找到，才注意到原来是在对话框底下……情况如图，进到根目录也是同样所有的图标都会变成X。

**Comment by liupan1890** [comment]
我需要去检查一遍，看问题出在哪

问题：未能正确的加载内置的icon.css

但是为什么未能正确加载，就不知道了，我去试试

回复我一下，你下载的版本（win、linux、mac）（是1月13日的，还是12月23日的那个？）（试一下12月23日版，是否也是X）

>开饭中，最新2.2.0版全部开源代码已上传

>01月13日13点 v2.2.2 https://wws.lanzous.com/b01npsg8h

>12月23日 https://wws.lanzous.com/b01nqc4gd 旧版链接备用

>win、linux、mac 均已发布，再接下来要整RSS订阅功能，这是个大项目了。。。。

**Comment by fallenveda** [comment]
感谢回复，目前使用的系统环境为win10 20H2, 系统号为19042.746，常规的运行库都已安装。

目前存在问题的版本，1223 win64, 1223 win32(未测), 0113 win64以及win32

之前的2.1.1依托浏览器打开，所有并没有出现任何问题。

原本以为其他人也会遇到同样问题上来反馈，但是从目前来看，这个也可能只是我的个例。今晚回去我会试试把Mactray卸载后再给个反馈，因为我的公司电脑同上述系统环境也安装了Mactray后测试这三个版本也是遇到了同样的问题。

**Comment by liupan1890** [comment]
我没用过MacTray，我稍后会去安装测试一下，看看是哪里导致的不兼容
  
>请教下小白羊2启动后在win任务管理器里的exe进程除了6panserver.exe还有其他我没有注意到的吗？
  
v2.2.2，win，启动后只有electron.exe和6panserver.exe 两个进程（electron会有多个）

> 因为试过把6panserver.exe添加到MacTray配置文件里的UnloadDll以及ExcludeSub中排除掉，但是都没有成功
  
因为6panserver.exe只是后台服务，不显示，跟字体无关。真正显示的是electron，所以不兼容是electron和MacTray不兼容，研究方向应该放在electron上

**Comment by fallenveda** [comment]
感谢提示，经过测试，目前解决方法是在MacTray的配置文件内将electron.exe添加到ExcludeSub(不进行热替换字体的进程)中排除掉即可解决。至于代码这些东西我就不太懂了，后续版本我同样会继续关注下。

**Comment by liupan1890** [comment]
我用window7安装了MacTray 2019.1-beta6（测试用的，干净的新系统）

选择默认配置里面的  Name=LCD.W7.默认字体.仿Mac  作为案例

安装后直接启用，LCD.W7.默认字体.仿Mac，小白羊显示正常
``````
; 【字体轮廓】
; 数字越大字体就越粗越黑
RenderWeight=1.8

FontSubstitutes=1

[FontSubstitutes]
SimSun-ExtB=楷体
SimSun=楷体
``````


``````
; 【字体轮廓】
; 数字越大字体就越粗越黑
RenderWeight=1.8


; 【强制使用某一个字体】
; 无视所有其他字体，全系统的字体都会被这里设置的字体代替
ForceChangeFont=楷体
``````

  
启动MacTray后，再启动小白羊。
1.系统内大部分文字都变成楷体粗了--说明MacTray已生效
2.小白羊字体没变--还是原来的细字

就是没配置，electron都不生效。。。
把你的 字体ini配置文件 贴一下，我试试（要图标变成X的，不要正常显示的）

**Comment by liupan1890** [comment]
![屏幕截图 2021-01-18 170918](https://user-images.githubusercontent.com/67817756/104895049-5b8cc380-59b0-11eb-8d51-bf9a9369694d.png)

**Comment by fallenveda** [comment]
[General]
Name=DIY
Icon=..\mactray.exe.ico,0

;【自动挂钩子进程】
;[0:Disable]  1:Enable
HookChildProcesses=1

;【字距微调】
;0:关 1:开
EnableKerning=1

;【字体微调】
;0:Normal 1:NoHinting 2:AutoHinting 3:Light+AutoHinting
HintingMode=1

;【抗锯齿方式】
;-1:Disable 0:Normal 1:Light 2:LCD(RGB) 3:LCD(GBR) 4:Light-LCD(RGB) 5:Light-LCD(GBR)
AntiAliasMode=4

;【常规体调整】
;-32:+32
NormalWeight=16

;【粗体字的调整】
;-16:+16
BoldWeight=2

;【斜体字的倾斜角度微调】
;-16:+16
ItalicSlant=0

;【只有在FontLoader=0（在下面）时此项设置才有效。建议选0，选1会占用大量内存，也没看出有什么好处。】
;0:Disable 1:Enable
UseMapping=0

;【Gamma模式开关】
;-1：关闭；0：使用设置的Gamma值（GammaValue）；1：使用sRGB的Gamma值；2：不明
GammaMode=0

;【Gamma值】
;GammaMode=0的时候此项设置才有效
;sRGB ≒ 2.2 CT-Default = 1.4
;windows的cleartype的Gamma值是1.4
GammaValue=1.5

;【对比度】
;数字越大越锐利，数字越小越发虚
Contrast=1.7

;【字体轮廓】
;数字越大字体就越粗越黑
RenderWeight=1.5
; DirectWrite 支持；DirectWrite support
DirectWrite=1

;【文字边界设置】
;数字越大越强调背景（类似文字边界被侵蚀的感觉），强调背景会有中字体锐利的感觉。适当降低对比度，提高TextTuning，可以使文字周围的颜色看起来“淡一点”
;再加上RenderWeight，把这三个设置的微妙平衡调节好的话，能得到不输给Mac的效果
;0:12

;AntiAliasMode=1时，通过TextTuning分量来调节
TextTuning=0

;AntiAliasMode=2时，通过TextTuning的RGB分量来调节
TextTuningR=4
TextTuningG=4
TextTuningB=4

;【字体加粗模式】
;对NormalWeight和BoldWeight有效
;0：Weight值大时横向加粗，值小时双向加粗，主要是避免Weight值过大时，模式3中在小字号时加粗过度出现斩头的现象；
;1：总是横向加粗；
;2：总是双向加粗，也就是freetype本身的粗体渲染。
;注意：通过加大GammaValue、TextTuning的值，可以减少Weight值过大的造成的效果问题，即可以在BolderMode=2时也可以避免转接头
NormalWeight=0
BolderMode=0

;【字体的载入方法】
;（注意是载入方法，不是渲染方法）
;0：用freetype载入字体
;1：用windows的绘图核心载入字体
;很多freetype的设置需要此项选0才能生效
FontLoader=0

;【字体链接】
;当FontLoader=0时
;0：什么都不做；
;1：使用注册表里的字体链接设置，通过FreeType的字符表进行查找
;2：使用注册表里的字体链接设置，使用Windows的转换函数直接查找
;当FontLoader=1时
;会保持启用的状态，但是所有字体链接的处理会交由WIN32API完成。
FontLink=2

;【字体替代】
;当FontLoader=0时
;0：什么都不做；
;1：安全替换方案（兼容性较好），根据以下FontSubstitutes的配置进行替换；
;2：完全替换方案（效果较全面，如替换后出现乱码，请尝试使用1），根据以下FontSubstitutes的配置进行替换；
;当FontLoader=1时
;会保持启用的状态，但是所有字体替代的处理会交由WIN32API完成
FontSubstitutes=1

;【让freetype处理的最大的字体尺寸，单位是像素，0的话就是全尺寸】
;交付 gdi++ 处理的最大尺寸（单位为像素）
;0-2147483647
MaxHeight=0

;【阴影设置】
;格式：水平偏移,垂直偏移,阴影深度（值越大，越浅）	
;Shadow=0,0,6

;【液晶显示器的优化配置】
;[0:None]  1:Default  2:Light  16:Legacy
LcdFilter=1

;【字体缓存、内存的设置】
LoadOnDemand=1
CacheMaxFaces=256
CacheMaxSizes=6140
CacheMaxBytes=20485760

;【强制使用某一个字体】
;无视所有其他字体，全系统的字体都会被这里设置的字体代替
;ForceChangeFont=Microsoft YaHei UI

[DirectWrite]
;渲染模式，0=默认，1=锯齿，2=经典，3=经典自然，4=自然，5=自然对称，6=字体原型
RenderingMode=6
;Gamma值，不写则根据上面的GammaValue自动计算
GammaValue=1.5
;对比度，默认为1
Contrast=1.0
;抗锯齿程度，默认1
ClearTypeLevel=1

[Individual]
;【单独设置的字体】
;格式＝Hinting, AAMode, NormalWeight, BoldWeight, ItalicSlant, Kerning
Aqua Kana=,,28,,,
Arial=,,28,,,
Batang=,,28,,,
Calibri=,,28,,,
Cambria=,,28,,,
Candara=,,28,,,
Consolas=,,28,,,
Courier New=,,28,,,
Courier Std=,,28,,,
Courier=,,28,,,
FOT-TsukuMinPr6N LB=,,28,,,
FOT-TsukuMinPr6N RB=,,28,,,
FZLanTingKanHei=,,28,,,
Gen Jyuu Gothic Normal=,,28,,,
Gen Jyuu Gothic Regular=,,28,,,
Gen Shin Gothic Normal=,,28,,,
Gen Shin Gothic Regular=,,28,,,
GenRyuMin JP R=,,28,,,
GenRyuMin TW R=,,28,,,
GenSekiGothic JP R=,,28,,,
GenSekiGothic TW R=,,28,,,
GenYoGothic JP N=,,28,,,
GenYoGothic JP R=,,28,,,
GenYoGothic TW N=,,28,,,
GenYoGothic TW R=,,28,,,
GenYoMin JP R=,,28,,,
GenYoMin TW R=,,28,,,
Georgia=,,28,,,
Helvetica CE 55 Roman=,,28,,,
Helvetica Narrow=,,28,,,
Helvetica=,,28,,,
Hiragino Kaku Gothic Pro W3=,,28,,,
Hiragino Kaku Gothic ProN W3=,,28,,,
Hiragino Mincho Pro W3=,,28,,,
Hiragino Mincho ProN W3=,,28,,,
H-冬青黑体传统中文-W3=,,28,,,
Kozuka Gothic Pro R=,,28,,,
Kozuka Mincho Pr6N R=,,28,,,
Kozuka Mincho Pro R=,,28,,,
LiHei Pro=,,28,,,
LiSong=,,28,,,
Microsoft JhengHei=,,28,,,
Microsoft YaHei UI=,,28,,,
Microsoft YaHei=,,28,,,
MingLiU_HKSCS=,,28,,,
MingLiU=,,28,,,
MS Gothic=,,28,,,
MS Mincho=,,28,,,
MS Outlook=,,28,,,
MS PGothic=,,28,,,
MS PMincho=,,28,,,
MS UI Gothic=,,28,,,
PMingLiU_HKSCS=,,28,,,
PMingLiU=,,28,,,
PMingLiU-CN=,,28,,,
PMingLiU-TW=,,28,,,
Roboto=,,28,,,
Roman=,,28,,,
Sarasa Fixed CL=,,28,,,
Sarasa Fixed HC=,,28,,,
Sarasa Fixed J=,,28,,,
Sarasa Fixed K=,,28,,,
Sarasa Fixed SC=,,28,,,
Sarasa Fixed Slab CL=,,28,,,
Sarasa Fixed Slab HC=,,28,,,
Sarasa Fixed Slab J=,,28,,,
Sarasa Fixed Slab K=,,28,,,
Sarasa Fixed Slab SC=,,28,,,
Sarasa Fixed Slab TC=,,28,,,
Sarasa Fixed TC=,,28,,,
Sarasa Gothic CL=,,28,,,
Sarasa Gothic HC=,,28,,,
Sarasa Gothic J=,,28,,,
Sarasa Gothic K=,,28,,,
Sarasa Gothic TC=,,28,,,
Sarasa Mono CL=,,28,,,
Sarasa Mono HC=,,28,,,
Sarasa Mono J=,,28,,,
Sarasa Mono K=,,28,,,
Sarasa Mono Slab CL=,,28,,,
Sarasa Mono Slab HC=,,28,,,
Sarasa Mono Slab J=,,28,,,
Sarasa Mono Slab K=,,28,,,
Sarasa Mono Slab TC=,,28,,,
Sarasa Mono T CL=,,28,,,
Sarasa Mono T HC=,,28,,,
Sarasa Mono T J=,,28,,,
Sarasa Mono T K=,,28,,,
Sarasa Mono T TC=,,28,,,
Sarasa Mono TC=,,28,,,
Sarasa Term CL=,,28,,,
Sarasa Term HC=,,28,,,
Sarasa Term J=,,28,,,
Sarasa Term K=,,28,,,
Sarasa Term SC=,,28,,,
Sarasa Term Slab CL=,,28,,,
Sarasa Term Slab HC=,,28,,,
Sarasa Term Slab J=,,28,,,
Sarasa Term Slab K=,,28,,,
Sarasa Term Slab SC=,,28,,,
Sarasa Term Slab TC=,,28,,,
Sarasa Term TC=,,28,,,
Sarasa UI CL=,,28,,,
Sarasa UI HC=,,28,,,
Sarasa UI J=,,28,,,
Sarasa UI K=,,28,,,
Sarasa UI TC=,,28,,,
Segoe Print=,,28,,,
Segoe Script=,,28,,,
Segoe UI=,,28,,,
SL-Simplified Regular=,,28,,,
SL-Traditional Regular=,,28,,,
Source Han Sans HC Normal=,,28,,,
Source Han Sans HC Regular=,,28,,,
Source Han Sans HC=,,28,,,
Source Han Sans HW Normal=,,28,,,
Source Han Sans HW Regular=,,28,,,
Source Han Sans K Normal=,,28,,,
Source Han Sans K Regular=,,28,,,
Source Han Sans Normal=,,28,,,
Source Han Sans Regular=,,28,,,
Source Han Sans Serif K Regular=,,28,,,
Source Han Sans Serif Regular=,,28,,,
Source Han Sans TC Normal=,,28,,,
Source Han Sans TC Regular=,,28,,,
Source Han Serif CN for Display=,,28,,,
Source Han Serif K=,,28,,,
Source Han Serif=,,28,,,
Source Sans Pro=,,28,,,
Source Serif Pro=,,28,,,
Tahoma=,,28,,,
Times New Roman=,,28,,,
Tsentsiu HG=,,28,,,
Verdana=,,28,,,
YaHei Consolas Hybrid=,,28,,,
YaHeiConsola=,,28,,,
Yu Gothic=,,28,,,
等距更纱黑体 SC=,,28,,,
等距更纱黑体 Slab SC=,,28,,,
等距更纱黑体 Slab UI SC=,,28,,,
等距更纱黑体 T SC=,,28,,,
等距更纱黑体 T UI SC=,,28,,,
等距更纱黑体 UI SC=,,28,,,
冬青黑体简体中文 W6=,,28,,,
方圆兰黑体=,,28,,,
方圆准黑GBK=,,28,,,
方正北魏楷书繁体=,,28,,,
方正北魏楷书简体=,,28,,,
方正风雅宋简体=,,28,,,
方正兰亭黑_GB18030=,,28,,,
方正兰亭黑_GBK=,,28,,,
方正兰亭黑_YS_BIG5=,,28,,,
方正兰亭黑_YS_GB18030=,,28,,,
方正兰亭黑Pro_GB18030=,,28,,,
方正兰亭黑繁体=,,28,,,
方正兰亭黑简体=,,28,,,
方正兰亭刊黑_GBK=,,28,,,
方正兰亭刊黑繁体=,,28,,,
方正兰亭刊宋_GBK=,,28,,,
方正兰亭刊宋繁体=,,28,,,
方正兰亭纤黑_GBK=,,28,,,
方正兰亭纤黑繁体=,,28,,,
方正兰亭中黑_GBK=,,28,,,
方正兰亭中黑繁体=,,28,,,
方正兰亭准黑_GBK=,,28,,,
方正兰亭准黑繁体=,,28,,,
方正兰亭准黑简体=,,28,,,
方正蘭亭特黑_TC=,,28,,,
方正书宋简体=,,28,,,
方正细黑_YS=,,28,,,
仿宋=,,28,,,
更纱黑体 SC=,,28,,,
更纱黑体 UI SC=,,28,,,
黑体=,,28,,,
华文仿宋=,,28,,,
华文行楷=,,28,,,
华文黑体=,,28,,,
华文楷体=,,28,,,
华文隶书=,,28,,,
华文宋体=,,28,,,
华文中宋=,,28,,,
楷体=,,28,,,
隶书=,,28,,,
俪宋体=,,28,,,
苹方-繁=,,28,,,
苹方-港=,,28,,,
苹方-简=,,28,,,
思源黑体 HW=,,28,,,
思源黑体=,,28,,,
思源黑體 HW=,,28,,,
思源黑體 香港=,,28,,,
思源黑體=,,28,,,
思源屏显臻宋 CN=,,28,,,
思源宋体=,,28,,,
思源宋體=,,28,,,
宋体=,,28,,,
微软雅黑=,,28,,,
小米兰亭=,,28,,,
新宋体=,,28,,,

[Exclude]
;【不渲染的字体】

[ExcludeModule]
;【不渲染的程序，但仍会加载DLL】



[FontSubstitutes]
;【字体替代】
;用等号后的字体替换等号前的字体
SimSun=思源屏显臻宋 CN
@SimSun=@思源屏显臻宋 CN
NSimSun=思源屏显臻宋 CN
@NSimSun=@思源屏显臻宋 CN
MS Serif=思源屏显臻宋 CN
MS Sans Serif=等距更纱黑体 SC


[UnloadDll]
;【不加载的程序】
fontview.exe
AxureRP.exe
FontCreator.exe
FontCreator.cn.exe
notecaselauncher.exe
notecase.exe
gnucash-bin.exe
bleachbit.exe
Fontforge_TC.exe
Fontforge_SC.exe
Fontforge_EN.exe
dwm.exe
xdict.exe
ollyice.exe
sc2.exe
avgnt.exe
SynTPHelper.exe
SynTPEnh.exe
SearchFilterHost.exe
SearchProtocolHost.exe
mspdbsrv.exe
kinza.exe
115chrome.exe
360chrome.exe
6panserver.exe

[ExcludeSub]
;【不进行字体热替换的进程】
javaw.exe
PPLive.exe
QQGame.exe
devenv.exe
OUTLOOK.EXE
EXCEL.EXE
WINWORD.EXE
POWERPNT.EXE
ONENOTE.EXE
ONENOTEM.EXE
cmd.exe
Thunder.exe
6panserver.exe
electron.exe

[Experimental@Firefox.exe]
ClipBoxFix=1
[FontSubstitutes@Explorer.exe]
Microsoft Sans Serif=微软雅黑



_我最终排查的问题是出在SimSun字体的热替换上，只要把electron.exe的进程排除或者直接不替换SimSun字体，就不会出现图标变X了_

**Comment by liupan1890** [comment]
我今天用了很长时间去测试，一台win10，日常使用了半年。一台win7，纯净新装

测试步骤：
1.复制你的ini（删除了[ExcludeSub] 下面的electron.exe）
2.安装思源屏显臻宋 CN字体
3.安装MacTray 
4.使用MacTray 的注册表模式，启用DIY.ini，启动小白羊
5.使用MacTray 的托盘加载模式（独立加载），选择DIY.ini，启动小白羊

结果都无法复现图标X的BUG。所以我最终也没能去调试程序查找BUG，我已经放弃了，还是将electron.exe排除吧，感觉不是必然的BUG，不去理会了

**Comment by fallenveda** [comment]
> 我今天用了很长时间去测试，一台win10，日常使用了半年。一台win7，纯净新装
> 
> 测试步骤：
> 1.复制你的ini（删除了[ExcludeSub] 下面的electron.exe）
> 2.安装思源屏显臻宋 CN字体
> 3.安装MacTray
> 4.使用MacTray 的注册表模式，启用DIY.ini，启动小白羊
> 5.使用MacTray 的托盘加载模式（独立加载），选择DIY.ini，启动小白羊
> 
> 结果都无法复现图标X的BUG。所以我最终也没能去调试程序查找BUG，我已经放弃了，还是将electron.exe排除吧，感觉不是必然的BUG，不去理会了

感谢测试，那看来确实是个例，而且是其他因素关联到SimSun热替换导致的问题，以后如果找到具体原因我再给个答复。
