### ISSUE TITLE
三个小问题

### ISSUE THREAD

**Issue by taptictop** [liupan1890/xiaobaiyang2#93]
1.同时选中文件和文件夹,然后批量下载,只有文件被下载下来了.

2.如果路径中win系统不允许作为名称的特殊字符,下载会失败,是否可以考虑自动替换成 下划线 或类似的字符

3.追加一个, 删除账号可否添加一个确认提示,往往想点标题栏把窗口切出来,却点到了删除账号....又要重登orz

**Comment by liupan1890** [comment]
1.同时选中文件和文件夹,然后批量下载,只有文件被下载下来了

批量下载功能只能下载文件，会自动跳过文件夹（因为可能会因为有太多文件夹多级嵌套，导致长时间显示下载中---最终可以下载，但长时间显示加载信息，流程很难看），这是正常的，当你把鼠标移动到  批量下载按钮上不动，提示信息已说明，不包括文件夹

  
2.如果路径中win系统不允许作为名称的特殊字符,下载会失败,

实际上有自动替换，可能你遇到的特殊字符我没替换到，下个版本我修正一下，确保全部特殊字符都替换掉

**Comment by liupan1890** [comment]
3.删除账号可否添加一个确认提示
好的，我会在下个版本中增加确认提示

**Comment by taptictop** [comment]
谢谢~
