### ISSUE TITLE
离线下载磁力链接不可以直接粘贴特征码，6盘网页可以

### ISSUE THREAD

**Issue by yangziqin** [liupan1890/xiaobaiyang2#96]
最近下载动漫，相关网站只有特征码，发现用小白羊得补全磁力

**Comment by yangziqin** [comment]
还有格式化，预解析，可以在提前任务时，自动进行吗

**Comment by liupan1890** [comment]
你好

1我会在下次更新时支持自动补全磁力的功能

2格式化，预解析，不可以自动进行
正确的操作流程：
1.复制，粘贴链接，回车，继续复制粘贴其他的链接，重复一直到全部链接都粘贴完
2.点击 格式化预解析，点击提交离线

为什么不能，只有一个提交离线按钮（点击提交按钮自动执行格式化预解析）
第一是因为很多人粘贴的链接不合法，所以需要用户最终再确认一遍自己想提交的链接6盘是否支持，是否正常--格式化预解析

第二是部分人习惯粘贴，格式化，粘贴第二条，格式化，粘贴第三条，格式化这种操作，他不喜欢粘贴，回车，粘贴第二条，回车，粘贴第三条这种操作

所以，流程上，必须有格式化这个操作。
方案一：只有一个按钮，先显示格式化，用户点击后变成提交链接
方案二：一个格式化按钮，一个提交链接按钮


方案一容易让人误会：找不到提交按钮，无法提交，所以是方案二

**Comment by liupan1890** [comment]
此BUG已经在v2.2.3修正，关闭issue
