### ISSUE TITLE
能不能加入同步盘功能，那就完美了

### ISSUE THREAD

**Issue by fanzhuoxuan** [liupan1890/xiaobaiyang2#98]

**Comment by liupan1890** [comment]
你好

同步盘功能，涉及到一个版本覆盖的问题，假如出错会导致用户文件丢失（以为是最新版本，结果只有旧版），另外6盘本身也不提供版本记录功能（记录某个文件每一次更新记录、恢复到指定日期版本）

所以，并不会有同步盘功能，只要是涉及到用户文件的功能，都会慎重考虑安全性（包括用户误操作可能导致的安全性）

**Comment by liupan1890** [comment]
长期未回复，已关闭
