### ISSUE TITLE
新版的6和8线程没用啊，会自动换到4线程上，下载和上传都是，会员账号

### ISSUE THREAD

**Issue by saludossol** [liupan1890/xiaobaiyang2#99]
https://user-images.githubusercontent.com/76832306/105464394-7e7ae880-5ccc-11eb-937b-d63741baf090.mp4

**Comment by liupan1890** [comment]
你好

是的，这是个BUG，会在下个版本发布时修正--计划是在明天发布

**Comment by saludossol** [comment]
好嘞
